-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity bd_quad_vmix_dp_v_tpg_4_0_tpgBackground is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    height_val : IN STD_LOGIC_VECTOR (15 downto 0);
    width_val : IN STD_LOGIC_VECTOR (15 downto 0);
    patternId_val : IN STD_LOGIC_VECTOR (7 downto 0);
    ZplateHorContStart_val : IN STD_LOGIC_VECTOR (15 downto 0);
    ZplateHorContDelta_val : IN STD_LOGIC_VECTOR (15 downto 0);
    ZplateVerContStart_val : IN STD_LOGIC_VECTOR (15 downto 0);
    ZplateVerContDelta_val : IN STD_LOGIC_VECTOR (15 downto 0);
    motionSpeed_val : IN STD_LOGIC_VECTOR (7 downto 0);
    colorFormat_val : IN STD_LOGIC_VECTOR (7 downto 0);
    bckgndYUV_din : OUT STD_LOGIC_VECTOR (47 downto 0);
    bckgndYUV_full_n : IN STD_LOGIC;
    bckgndYUV_write : OUT STD_LOGIC;
    bckgndYUV_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    bckgndYUV_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    height_val4_c3_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    height_val4_c3_full_n : IN STD_LOGIC;
    height_val4_c3_write : OUT STD_LOGIC;
    height_val4_c3_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    height_val4_c3_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    width_val7_c4_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    width_val7_c4_full_n : IN STD_LOGIC;
    width_val7_c4_write : OUT STD_LOGIC;
    width_val7_c4_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    width_val7_c4_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    motionSpeed_val14_c_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    motionSpeed_val14_c_full_n : IN STD_LOGIC;
    motionSpeed_val14_c_write : OUT STD_LOGIC;
    motionSpeed_val14_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    motionSpeed_val14_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    colorFormat_val17_c5_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    colorFormat_val17_c5_full_n : IN STD_LOGIC;
    colorFormat_val17_c5_write : OUT STD_LOGIC;
    colorFormat_val17_c5_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    colorFormat_val17_c5_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0) );
end;


architecture behav of bd_quad_vmix_dp_v_tpg_4_0_tpgBackground is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv64_2 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000010";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal rampStart : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal blkYuv_address0 : STD_LOGIC_VECTOR (1 downto 0);
    signal blkYuv_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal zonePlateVAddr : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal height_val4_c3_blk_n : STD_LOGIC;
    signal width_val7_c4_blk_n : STD_LOGIC;
    signal motionSpeed_val14_c_blk_n : STD_LOGIC;
    signal colorFormat_val17_c5_blk_n : STD_LOGIC;
    signal colorFormat_val_read_reg_405 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal motionSpeed_val_read_reg_410 : STD_LOGIC_VECTOR (7 downto 0);
    signal width_val_read_reg_415 : STD_LOGIC_VECTOR (15 downto 0);
    signal height_val_read_reg_420 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_reg_425 : STD_LOGIC_VECTOR (6 downto 0);
    signal ZplateVerContDelta_val_read_reg_435 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ZplateVerContStart_val_read_reg_440 : STD_LOGIC_VECTOR (15 downto 0);
    signal ZplateHorContDelta_val_read_reg_445 : STD_LOGIC_VECTOR (15 downto 0);
    signal ZplateHorContStart_val_read_reg_450 : STD_LOGIC_VECTOR (15 downto 0);
    signal patternId_val_read_reg_455 : STD_LOGIC_VECTOR (7 downto 0);
    signal shl_i_fu_317_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_i_reg_463 : STD_LOGIC_VECTOR (15 downto 0);
    signal blkYuv_load_reg_468 : STD_LOGIC_VECTOR (7 downto 0);
    signal y_3_reg_473 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal cmp12_i_fu_340_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp12_i_reg_481 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_ap_start : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_ap_done : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_ap_idle : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_ap_ready : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_bckgndYUV_din : STD_LOGIC_VECTOR (47 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_bckgndYUV_write : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_zonePlateVAddr_loc_1_out_o : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_zonePlateVAddr_loc_1_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_outpix_0_5_0_0_0_load330_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_outpix_0_5_0_0_0_load330_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_outpix_0_4_0_0_0_load328_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_outpix_0_4_0_0_0_load328_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_outpix_0_3_0_0_0_load326_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_outpix_0_3_0_0_0_load326_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_outpix_0_2_0_0_0_load324_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_outpix_0_2_0_0_0_load324_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_outpix_0_1_0_0_0_load322_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_outpix_0_1_0_0_0_load322_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_outpix_0_0_0_0_0_load320_out_o : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_outpix_0_0_0_0_0_load320_out_o_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_zonePlateVAddr : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_zonePlateVAddr_ap_vld : STD_LOGIC;
    signal grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_ap_start_reg : STD_LOGIC := '0';
    signal icmp_ln563_fu_329_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal zonePlateVAddr_loc_0_fu_134 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal outpix_0_5_0_0_0_load331_lcssa349_fu_130 : STD_LOGIC_VECTOR (7 downto 0);
    signal outpix_0_4_0_0_0_load329_lcssa346_fu_126 : STD_LOGIC_VECTOR (7 downto 0);
    signal outpix_0_3_0_0_0_load327_lcssa343_fu_122 : STD_LOGIC_VECTOR (7 downto 0);
    signal outpix_0_2_0_0_0_load325_lcssa340_fu_118 : STD_LOGIC_VECTOR (7 downto 0);
    signal outpix_0_1_0_0_0_load323_lcssa337_fu_114 : STD_LOGIC_VECTOR (7 downto 0);
    signal outpix_0_0_0_0_0_load321_lcssa334_fu_110 : STD_LOGIC_VECTOR (7 downto 0);
    signal idxprom13_1_i186_cast_cast_cast_fu_290_p3 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln750_fu_352_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal y_fu_106 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal y_4_fu_334_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal blkYuv_ce0_local : STD_LOGIC;
    signal cmp6_i182_fu_284_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component bd_quad_vmix_dp_v_tpg_4_0_tpgBackground_Pipeline_VITIS_LOOP_565_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        bckgndYUV_din : OUT STD_LOGIC_VECTOR (47 downto 0);
        bckgndYUV_full_n : IN STD_LOGIC;
        bckgndYUV_write : OUT STD_LOGIC;
        bckgndYUV_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
        bckgndYUV_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
        width_val_cast : IN STD_LOGIC_VECTOR (15 downto 0);
        patternId_val : IN STD_LOGIC_VECTOR (7 downto 0);
        blkYuv_load : IN STD_LOGIC_VECTOR (7 downto 0);
        shl_i : IN STD_LOGIC_VECTOR (15 downto 0);
        ZplateHorContStart_val : IN STD_LOGIC_VECTOR (15 downto 0);
        ZplateHorContDelta_val : IN STD_LOGIC_VECTOR (15 downto 0);
        ZplateVerContStart_val : IN STD_LOGIC_VECTOR (15 downto 0);
        y : IN STD_LOGIC_VECTOR (15 downto 0);
        cmp12_i : IN STD_LOGIC_VECTOR (0 downto 0);
        ZplateVerContDelta_val : IN STD_LOGIC_VECTOR (15 downto 0);
        colorFormat_val : IN STD_LOGIC_VECTOR (7 downto 0);
        empty : IN STD_LOGIC_VECTOR (6 downto 0);
        zonePlateVAddr_loc_1_out_i : IN STD_LOGIC_VECTOR (15 downto 0);
        zonePlateVAddr_loc_1_out_o : OUT STD_LOGIC_VECTOR (15 downto 0);
        zonePlateVAddr_loc_1_out_o_ap_vld : OUT STD_LOGIC;
        outpix_0_5_0_0_0_load330_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        outpix_0_5_0_0_0_load330_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        outpix_0_5_0_0_0_load330_out_o_ap_vld : OUT STD_LOGIC;
        outpix_0_4_0_0_0_load328_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        outpix_0_4_0_0_0_load328_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        outpix_0_4_0_0_0_load328_out_o_ap_vld : OUT STD_LOGIC;
        outpix_0_3_0_0_0_load326_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        outpix_0_3_0_0_0_load326_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        outpix_0_3_0_0_0_load326_out_o_ap_vld : OUT STD_LOGIC;
        outpix_0_2_0_0_0_load324_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        outpix_0_2_0_0_0_load324_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        outpix_0_2_0_0_0_load324_out_o_ap_vld : OUT STD_LOGIC;
        outpix_0_1_0_0_0_load322_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        outpix_0_1_0_0_0_load322_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        outpix_0_1_0_0_0_load322_out_o_ap_vld : OUT STD_LOGIC;
        outpix_0_0_0_0_0_load320_out_i : IN STD_LOGIC_VECTOR (7 downto 0);
        outpix_0_0_0_0_0_load320_out_o : OUT STD_LOGIC_VECTOR (7 downto 0);
        outpix_0_0_0_0_0_load320_out_o_ap_vld : OUT STD_LOGIC;
        zonePlateVAddr : OUT STD_LOGIC_VECTOR (15 downto 0);
        zonePlateVAddr_ap_vld : OUT STD_LOGIC );
    end component;


    component bd_quad_vmix_dp_v_tpg_4_0_tpgBackground_blkYuv_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (1 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    blkYuv_U : component bd_quad_vmix_dp_v_tpg_4_0_tpgBackground_blkYuv_ROM_AUTO_1R
    generic map (
        DataWidth => 8,
        AddressRange => 3,
        AddressWidth => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => blkYuv_address0,
        ce0 => blkYuv_ce0_local,
        q0 => blkYuv_q0);

    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237 : component bd_quad_vmix_dp_v_tpg_4_0_tpgBackground_Pipeline_VITIS_LOOP_565_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_ap_start,
        ap_done => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_ap_done,
        ap_idle => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_ap_idle,
        ap_ready => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_ap_ready,
        bckgndYUV_din => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_bckgndYUV_din,
        bckgndYUV_full_n => bckgndYUV_full_n,
        bckgndYUV_write => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_bckgndYUV_write,
        bckgndYUV_num_data_valid => ap_const_lv5_0,
        bckgndYUV_fifo_cap => ap_const_lv5_0,
        width_val_cast => width_val_read_reg_415,
        patternId_val => patternId_val_read_reg_455,
        blkYuv_load => blkYuv_load_reg_468,
        shl_i => shl_i_reg_463,
        ZplateHorContStart_val => ZplateHorContStart_val_read_reg_450,
        ZplateHorContDelta_val => ZplateHorContDelta_val_read_reg_445,
        ZplateVerContStart_val => ZplateVerContStart_val_read_reg_440,
        y => y_3_reg_473,
        cmp12_i => cmp12_i_reg_481,
        ZplateVerContDelta_val => ZplateVerContDelta_val_read_reg_435,
        colorFormat_val => colorFormat_val_read_reg_405,
        empty => tmp_reg_425,
        zonePlateVAddr_loc_1_out_i => zonePlateVAddr_loc_0_fu_134,
        zonePlateVAddr_loc_1_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_zonePlateVAddr_loc_1_out_o,
        zonePlateVAddr_loc_1_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_zonePlateVAddr_loc_1_out_o_ap_vld,
        outpix_0_5_0_0_0_load330_out_i => outpix_0_5_0_0_0_load331_lcssa349_fu_130,
        outpix_0_5_0_0_0_load330_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_outpix_0_5_0_0_0_load330_out_o,
        outpix_0_5_0_0_0_load330_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_outpix_0_5_0_0_0_load330_out_o_ap_vld,
        outpix_0_4_0_0_0_load328_out_i => outpix_0_4_0_0_0_load329_lcssa346_fu_126,
        outpix_0_4_0_0_0_load328_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_outpix_0_4_0_0_0_load328_out_o,
        outpix_0_4_0_0_0_load328_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_outpix_0_4_0_0_0_load328_out_o_ap_vld,
        outpix_0_3_0_0_0_load326_out_i => outpix_0_3_0_0_0_load327_lcssa343_fu_122,
        outpix_0_3_0_0_0_load326_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_outpix_0_3_0_0_0_load326_out_o,
        outpix_0_3_0_0_0_load326_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_outpix_0_3_0_0_0_load326_out_o_ap_vld,
        outpix_0_2_0_0_0_load324_out_i => outpix_0_2_0_0_0_load325_lcssa340_fu_118,
        outpix_0_2_0_0_0_load324_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_outpix_0_2_0_0_0_load324_out_o,
        outpix_0_2_0_0_0_load324_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_outpix_0_2_0_0_0_load324_out_o_ap_vld,
        outpix_0_1_0_0_0_load322_out_i => outpix_0_1_0_0_0_load323_lcssa337_fu_114,
        outpix_0_1_0_0_0_load322_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_outpix_0_1_0_0_0_load322_out_o,
        outpix_0_1_0_0_0_load322_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_outpix_0_1_0_0_0_load322_out_o_ap_vld,
        outpix_0_0_0_0_0_load320_out_i => outpix_0_0_0_0_0_load321_lcssa334_fu_110,
        outpix_0_0_0_0_0_load320_out_o => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_outpix_0_0_0_0_0_load320_out_o,
        outpix_0_0_0_0_0_load320_out_o_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_outpix_0_0_0_0_0_load320_out_o_ap_vld,
        zonePlateVAddr => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_zonePlateVAddr,
        zonePlateVAddr_ap_vld => grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_zonePlateVAddr_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln563_fu_329_p2 = ap_const_lv1_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln563_fu_329_p2 = ap_const_lv1_0))) then 
                    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_ap_ready = ap_const_logic_1)) then 
                    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    y_fu_106_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                y_fu_106 <= ap_const_lv16_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln563_fu_329_p2 = ap_const_lv1_0))) then 
                y_fu_106 <= y_4_fu_334_p2;
            end if; 
        end if;
    end process;

    zonePlateVAddr_loc_0_fu_134_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                zonePlateVAddr_loc_0_fu_134 <= zonePlateVAddr;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_zonePlateVAddr_loc_1_out_o_ap_vld = ap_const_logic_1))) then 
                zonePlateVAddr_loc_0_fu_134 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_zonePlateVAddr_loc_1_out_o;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                ZplateHorContDelta_val_read_reg_445 <= ZplateHorContDelta_val;
                ZplateHorContStart_val_read_reg_450 <= ZplateHorContStart_val;
                ZplateVerContDelta_val_read_reg_435 <= ZplateVerContDelta_val;
                ZplateVerContStart_val_read_reg_440 <= ZplateVerContStart_val;
                blkYuv_load_reg_468 <= blkYuv_q0;
                patternId_val_read_reg_455 <= patternId_val;
                    shl_i_reg_463(15 downto 8) <= shl_i_fu_317_p3(15 downto 8);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                cmp12_i_reg_481 <= cmp12_i_fu_340_p2;
                y_3_reg_473 <= y_fu_106;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                colorFormat_val_read_reg_405 <= colorFormat_val;
                height_val_read_reg_420 <= height_val;
                motionSpeed_val_read_reg_410 <= motionSpeed_val;
                tmp_reg_425 <= colorFormat_val(7 downto 1);
                width_val_read_reg_415 <= width_val;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_outpix_0_0_0_0_0_load320_out_o_ap_vld = ap_const_logic_1))) then
                outpix_0_0_0_0_0_load321_lcssa334_fu_110 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_outpix_0_0_0_0_0_load320_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_outpix_0_1_0_0_0_load322_out_o_ap_vld = ap_const_logic_1))) then
                outpix_0_1_0_0_0_load323_lcssa337_fu_114 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_outpix_0_1_0_0_0_load322_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_outpix_0_2_0_0_0_load324_out_o_ap_vld = ap_const_logic_1))) then
                outpix_0_2_0_0_0_load325_lcssa340_fu_118 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_outpix_0_2_0_0_0_load324_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_outpix_0_3_0_0_0_load326_out_o_ap_vld = ap_const_logic_1))) then
                outpix_0_3_0_0_0_load327_lcssa343_fu_122 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_outpix_0_3_0_0_0_load326_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_outpix_0_4_0_0_0_load328_out_o_ap_vld = ap_const_logic_1))) then
                outpix_0_4_0_0_0_load329_lcssa346_fu_126 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_outpix_0_4_0_0_0_load328_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_outpix_0_5_0_0_0_load330_out_o_ap_vld = ap_const_logic_1))) then
                outpix_0_5_0_0_0_load331_lcssa349_fu_130 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_outpix_0_5_0_0_0_load330_out_o;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln563_fu_329_p2 = ap_const_lv1_1))) then
                rampStart <= add_ln750_fu_352_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_zonePlateVAddr_ap_vld = ap_const_logic_1))) then
                zonePlateVAddr <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_zonePlateVAddr;
            end if;
        end if;
    end process;
    shl_i_reg_463(7 downto 0) <= "00000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1, ap_CS_fsm_state3, grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_ap_done, icmp_ln563_fu_329_p2, ap_CS_fsm_state4)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln563_fu_329_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    add_ln750_fu_352_p2 <= std_logic_vector(unsigned(rampStart) + unsigned(motionSpeed_val_read_reg_410));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_ap_done)
    begin
        if ((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, height_val4_c3_full_n, width_val7_c4_full_n, motionSpeed_val14_c_full_n, colorFormat_val17_c5_full_n)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (colorFormat_val17_c5_full_n = ap_const_logic_0) or (motionSpeed_val14_c_full_n = ap_const_logic_0) or (width_val7_c4_full_n = ap_const_logic_0) or (height_val4_c3_full_n = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state3, icmp_ln563_fu_329_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln563_fu_329_p2 = ap_const_lv1_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state3, icmp_ln563_fu_329_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln563_fu_329_p2 = ap_const_lv1_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    bckgndYUV_din <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_bckgndYUV_din;
    bckgndYUV_write <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_bckgndYUV_write;
    blkYuv_address0 <= idxprom13_1_i186_cast_cast_cast_fu_290_p3(2 - 1 downto 0);

    blkYuv_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            blkYuv_ce0_local <= ap_const_logic_1;
        else 
            blkYuv_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    cmp12_i_fu_340_p2 <= "0" when (y_fu_106 = ap_const_lv16_0) else "1";
    cmp6_i182_fu_284_p2 <= "1" when (colorFormat_val = ap_const_lv8_1) else "0";

    colorFormat_val17_c5_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, colorFormat_val17_c5_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            colorFormat_val17_c5_blk_n <= colorFormat_val17_c5_full_n;
        else 
            colorFormat_val17_c5_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    colorFormat_val17_c5_din <= colorFormat_val;

    colorFormat_val17_c5_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            colorFormat_val17_c5_write <= ap_const_logic_1;
        else 
            colorFormat_val17_c5_write <= ap_const_logic_0;
        end if; 
    end process;

    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_ap_start <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_237_ap_start_reg;

    height_val4_c3_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, height_val4_c3_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            height_val4_c3_blk_n <= height_val4_c3_full_n;
        else 
            height_val4_c3_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    height_val4_c3_din <= height_val;

    height_val4_c3_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            height_val4_c3_write <= ap_const_logic_1;
        else 
            height_val4_c3_write <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln563_fu_329_p2 <= "1" when (y_fu_106 = height_val_read_reg_420) else "0";
    idxprom13_1_i186_cast_cast_cast_fu_290_p3 <= 
        ap_const_lv64_1 when (cmp6_i182_fu_284_p2(0) = '1') else 
        ap_const_lv64_2;

    motionSpeed_val14_c_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, motionSpeed_val14_c_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            motionSpeed_val14_c_blk_n <= motionSpeed_val14_c_full_n;
        else 
            motionSpeed_val14_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    motionSpeed_val14_c_din <= motionSpeed_val;

    motionSpeed_val14_c_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            motionSpeed_val14_c_write <= ap_const_logic_1;
        else 
            motionSpeed_val14_c_write <= ap_const_logic_0;
        end if; 
    end process;

    shl_i_fu_317_p3 <= (rampStart & ap_const_lv8_0);

    width_val7_c4_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, width_val7_c4_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            width_val7_c4_blk_n <= width_val7_c4_full_n;
        else 
            width_val7_c4_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    width_val7_c4_din <= width_val;

    width_val7_c4_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            width_val7_c4_write <= ap_const_logic_1;
        else 
            width_val7_c4_write <= ap_const_logic_0;
        end if; 
    end process;

    y_4_fu_334_p2 <= std_logic_vector(unsigned(y_fu_106) + unsigned(ap_const_lv16_1));
end behav;
