-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity bd_quad_vmix_dp_v_mix_0_0_v_mix_core_alpha_false_false_21 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    outLayer2_dout : IN STD_LOGIC_VECTOR (47 downto 0);
    outLayer2_empty_n : IN STD_LOGIC;
    outLayer2_read : OUT STD_LOGIC;
    outLayer2_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    outLayer2_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    srcLayer3x_dout : IN STD_LOGIC_VECTOR (47 downto 0);
    srcLayer3x_empty_n : IN STD_LOGIC;
    srcLayer3x_read : OUT STD_LOGIC;
    srcLayer3x_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    srcLayer3x_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    HwReg_width_val : IN STD_LOGIC_VECTOR (11 downto 0);
    HwReg_height_val : IN STD_LOGIC_VECTOR (11 downto 0);
    HwReg_layerEnable_val25_dout : IN STD_LOGIC_VECTOR (4 downto 0);
    HwReg_layerEnable_val25_empty_n : IN STD_LOGIC;
    HwReg_layerEnable_val25_read : OUT STD_LOGIC;
    HwReg_layerEnable_val25_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    HwReg_layerEnable_val25_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    HwReg_layerStartX_3_val28_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    HwReg_layerStartX_3_val28_empty_n : IN STD_LOGIC;
    HwReg_layerStartX_3_val28_read : OUT STD_LOGIC;
    HwReg_layerStartX_3_val28_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    HwReg_layerStartX_3_val28_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    HwReg_layerStartY_3_val32_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    HwReg_layerStartY_3_val32_empty_n : IN STD_LOGIC;
    HwReg_layerStartY_3_val32_read : OUT STD_LOGIC;
    HwReg_layerStartY_3_val32_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    HwReg_layerStartY_3_val32_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    HwReg_layerWidth_3_val_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    HwReg_layerWidth_3_val_empty_n : IN STD_LOGIC;
    HwReg_layerWidth_3_val_read : OUT STD_LOGIC;
    HwReg_layerWidth_3_val_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    HwReg_layerWidth_3_val_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    HwReg_layerHeight_3_val_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    HwReg_layerHeight_3_val_empty_n : IN STD_LOGIC;
    HwReg_layerHeight_3_val_read : OUT STD_LOGIC;
    HwReg_layerHeight_3_val_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    HwReg_layerHeight_3_val_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    HwReg_layerScaleFactor_3_val44_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    HwReg_layerScaleFactor_3_val44_empty_n : IN STD_LOGIC;
    HwReg_layerScaleFactor_3_val44_read : OUT STD_LOGIC;
    HwReg_layerScaleFactor_3_val44_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    HwReg_layerScaleFactor_3_val44_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    outLayer3_din : OUT STD_LOGIC_VECTOR (47 downto 0);
    outLayer3_full_n : IN STD_LOGIC;
    outLayer3_write : OUT STD_LOGIC;
    outLayer3_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    outLayer3_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
    HwReg_layerEnable_val25_c_din : OUT STD_LOGIC_VECTOR (4 downto 0);
    HwReg_layerEnable_val25_c_full_n : IN STD_LOGIC;
    HwReg_layerEnable_val25_c_write : OUT STD_LOGIC;
    HwReg_layerEnable_val25_c_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    HwReg_layerEnable_val25_c_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0) );
end;


architecture behav of bd_quad_vmix_dp_v_mix_0_0_v_mix_core_alpha_false_false_21 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal HwReg_layerEnable_val25_blk_n : STD_LOGIC;
    signal HwReg_layerStartX_3_val28_blk_n : STD_LOGIC;
    signal HwReg_layerStartY_3_val32_blk_n : STD_LOGIC;
    signal HwReg_layerWidth_3_val_blk_n : STD_LOGIC;
    signal HwReg_layerHeight_3_val_blk_n : STD_LOGIC;
    signal HwReg_layerScaleFactor_3_val44_blk_n : STD_LOGIC;
    signal HwReg_layerEnable_val25_c_blk_n : STD_LOGIC;
    signal HwReg_height_val_read_reg_313 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal layerStartY_reg_318 : STD_LOGIC_VECTOR (15 downto 0);
    signal div_cast_i_reg_323 : STD_LOGIC_VECTOR (10 downto 0);
    signal add60_i_fu_208_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal add60_i_reg_328 : STD_LOGIC_VECTOR (16 downto 0);
    signal div65_cast_i_reg_333 : STD_LOGIC_VECTOR (14 downto 0);
    signal div72_cast_i_reg_338 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_6_reg_343 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev13_fu_288_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev13_reg_351 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal cmp61_i_fu_295_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp61_i_reg_356 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_v_mix_core_alpha_false_false_21_Pipeline_VITIS_LOOP_465_3_fu_154_ap_start : STD_LOGIC;
    signal grp_v_mix_core_alpha_false_false_21_Pipeline_VITIS_LOOP_465_3_fu_154_ap_done : STD_LOGIC;
    signal grp_v_mix_core_alpha_false_false_21_Pipeline_VITIS_LOOP_465_3_fu_154_ap_idle : STD_LOGIC;
    signal grp_v_mix_core_alpha_false_false_21_Pipeline_VITIS_LOOP_465_3_fu_154_ap_ready : STD_LOGIC;
    signal grp_v_mix_core_alpha_false_false_21_Pipeline_VITIS_LOOP_465_3_fu_154_outLayer2_read : STD_LOGIC;
    signal grp_v_mix_core_alpha_false_false_21_Pipeline_VITIS_LOOP_465_3_fu_154_srcLayer3x_read : STD_LOGIC;
    signal grp_v_mix_core_alpha_false_false_21_Pipeline_VITIS_LOOP_465_3_fu_154_outLayer3_din : STD_LOGIC_VECTOR (47 downto 0);
    signal grp_v_mix_core_alpha_false_false_21_Pipeline_VITIS_LOOP_465_3_fu_154_outLayer3_write : STD_LOGIC;
    signal grp_v_mix_core_alpha_false_false_21_Pipeline_VITIS_LOOP_465_3_fu_154_ap_start_reg : STD_LOGIC := '0';
    signal icmp_ln463_fu_264_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal y_fu_94 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    signal add_ln463_fu_269_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal HwReg_layerScaleFactor_3_val44_readcast_fu_170_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal HwReg_layerScaleFactor_3_val44_readcast14_fu_180_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal shl_ln449_fu_174_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal layerHeight_cast_i_fu_204_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal hwReg_layerStartY_3_val_cast_i_fu_200_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal shl_ln450_fu_184_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal layerWidth_cast_i_fu_228_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal hwReg_layerStartX_3_val_cast_i_fu_214_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add71_i_fu_232_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln463_2_fu_279_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal ult_fu_283_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln463_fu_275_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component bd_quad_vmix_dp_v_mix_0_0_v_mix_core_alpha_false_false_21_Pipeline_VITIS_LOOP_465_3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        outLayer2_dout : IN STD_LOGIC_VECTOR (47 downto 0);
        outLayer2_empty_n : IN STD_LOGIC;
        outLayer2_read : OUT STD_LOGIC;
        outLayer2_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        outLayer2_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        srcLayer3x_dout : IN STD_LOGIC_VECTOR (47 downto 0);
        srcLayer3x_empty_n : IN STD_LOGIC;
        srcLayer3x_read : OUT STD_LOGIC;
        srcLayer3x_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        srcLayer3x_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        outLayer3_din : OUT STD_LOGIC_VECTOR (47 downto 0);
        outLayer3_full_n : IN STD_LOGIC;
        outLayer3_write : OUT STD_LOGIC;
        outLayer3_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
        outLayer3_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
        div_cast_i : IN STD_LOGIC_VECTOR (10 downto 0);
        div65_cast_i : IN STD_LOGIC_VECTOR (14 downto 0);
        div72_cast_i : IN STD_LOGIC_VECTOR (15 downto 0);
        cmp61_i : IN STD_LOGIC_VECTOR (0 downto 0);
        rev5 : IN STD_LOGIC_VECTOR (0 downto 0);
        empty : IN STD_LOGIC_VECTOR (0 downto 0) );
    end component;



begin
    grp_v_mix_core_alpha_false_false_21_Pipeline_VITIS_LOOP_465_3_fu_154 : component bd_quad_vmix_dp_v_mix_0_0_v_mix_core_alpha_false_false_21_Pipeline_VITIS_LOOP_465_3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_v_mix_core_alpha_false_false_21_Pipeline_VITIS_LOOP_465_3_fu_154_ap_start,
        ap_done => grp_v_mix_core_alpha_false_false_21_Pipeline_VITIS_LOOP_465_3_fu_154_ap_done,
        ap_idle => grp_v_mix_core_alpha_false_false_21_Pipeline_VITIS_LOOP_465_3_fu_154_ap_idle,
        ap_ready => grp_v_mix_core_alpha_false_false_21_Pipeline_VITIS_LOOP_465_3_fu_154_ap_ready,
        outLayer2_dout => outLayer2_dout,
        outLayer2_empty_n => outLayer2_empty_n,
        outLayer2_read => grp_v_mix_core_alpha_false_false_21_Pipeline_VITIS_LOOP_465_3_fu_154_outLayer2_read,
        outLayer2_num_data_valid => ap_const_lv3_0,
        outLayer2_fifo_cap => ap_const_lv3_0,
        srcLayer3x_dout => srcLayer3x_dout,
        srcLayer3x_empty_n => srcLayer3x_empty_n,
        srcLayer3x_read => grp_v_mix_core_alpha_false_false_21_Pipeline_VITIS_LOOP_465_3_fu_154_srcLayer3x_read,
        srcLayer3x_num_data_valid => ap_const_lv3_0,
        srcLayer3x_fifo_cap => ap_const_lv3_0,
        outLayer3_din => grp_v_mix_core_alpha_false_false_21_Pipeline_VITIS_LOOP_465_3_fu_154_outLayer3_din,
        outLayer3_full_n => outLayer3_full_n,
        outLayer3_write => grp_v_mix_core_alpha_false_false_21_Pipeline_VITIS_LOOP_465_3_fu_154_outLayer3_write,
        outLayer3_num_data_valid => outLayer3_num_data_valid,
        outLayer3_fifo_cap => outLayer3_fifo_cap,
        div_cast_i => div_cast_i_reg_323,
        div65_cast_i => div65_cast_i_reg_333,
        div72_cast_i => div72_cast_i_reg_338,
        cmp61_i => cmp61_i_reg_356,
        rev5 => rev13_reg_351,
        empty => tmp_6_reg_343);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln463_fu_264_p2 = ap_const_lv1_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_v_mix_core_alpha_false_false_21_Pipeline_VITIS_LOOP_465_3_fu_154_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_v_mix_core_alpha_false_false_21_Pipeline_VITIS_LOOP_465_3_fu_154_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln463_fu_264_p2 = ap_const_lv1_0))) then 
                    grp_v_mix_core_alpha_false_false_21_Pipeline_VITIS_LOOP_465_3_fu_154_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_v_mix_core_alpha_false_false_21_Pipeline_VITIS_LOOP_465_3_fu_154_ap_ready = ap_const_logic_1)) then 
                    grp_v_mix_core_alpha_false_false_21_Pipeline_VITIS_LOOP_465_3_fu_154_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    y_fu_94_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
                y_fu_94 <= ap_const_lv12_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln463_fu_264_p2 = ap_const_lv1_0))) then 
                y_fu_94 <= add_ln463_fu_269_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                HwReg_height_val_read_reg_313 <= HwReg_height_val;
                add60_i_reg_328 <= add60_i_fu_208_p2;
                div65_cast_i_reg_333 <= HwReg_layerStartX_3_val28_dout(15 downto 1);
                div72_cast_i_reg_338 <= add71_i_fu_232_p2(16 downto 1);
                div_cast_i_reg_323 <= HwReg_width_val(11 downto 1);
                layerStartY_reg_318 <= HwReg_layerStartY_3_val32_dout;
                tmp_6_reg_343 <= HwReg_layerEnable_val25_dout(3 downto 3);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                cmp61_i_reg_356 <= cmp61_i_fu_295_p2;
                rev13_reg_351 <= rev13_fu_288_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1, ap_CS_fsm_state2, grp_v_mix_core_alpha_false_false_21_Pipeline_VITIS_LOOP_465_3_fu_154_ap_done, icmp_ln463_fu_264_p2, ap_CS_fsm_state3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln463_fu_264_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_v_mix_core_alpha_false_false_21_Pipeline_VITIS_LOOP_465_3_fu_154_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;

    HwReg_layerEnable_val25_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, HwReg_layerEnable_val25_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            HwReg_layerEnable_val25_blk_n <= HwReg_layerEnable_val25_empty_n;
        else 
            HwReg_layerEnable_val25_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    HwReg_layerEnable_val25_c_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, HwReg_layerEnable_val25_c_full_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            HwReg_layerEnable_val25_c_blk_n <= HwReg_layerEnable_val25_c_full_n;
        else 
            HwReg_layerEnable_val25_c_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    HwReg_layerEnable_val25_c_din <= HwReg_layerEnable_val25_dout;

    HwReg_layerEnable_val25_c_write_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            HwReg_layerEnable_val25_c_write <= ap_const_logic_1;
        else 
            HwReg_layerEnable_val25_c_write <= ap_const_logic_0;
        end if; 
    end process;


    HwReg_layerEnable_val25_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            HwReg_layerEnable_val25_read <= ap_const_logic_1;
        else 
            HwReg_layerEnable_val25_read <= ap_const_logic_0;
        end if; 
    end process;


    HwReg_layerHeight_3_val_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, HwReg_layerHeight_3_val_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            HwReg_layerHeight_3_val_blk_n <= HwReg_layerHeight_3_val_empty_n;
        else 
            HwReg_layerHeight_3_val_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    HwReg_layerHeight_3_val_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            HwReg_layerHeight_3_val_read <= ap_const_logic_1;
        else 
            HwReg_layerHeight_3_val_read <= ap_const_logic_0;
        end if; 
    end process;


    HwReg_layerScaleFactor_3_val44_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, HwReg_layerScaleFactor_3_val44_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            HwReg_layerScaleFactor_3_val44_blk_n <= HwReg_layerScaleFactor_3_val44_empty_n;
        else 
            HwReg_layerScaleFactor_3_val44_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    HwReg_layerScaleFactor_3_val44_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            HwReg_layerScaleFactor_3_val44_read <= ap_const_logic_1;
        else 
            HwReg_layerScaleFactor_3_val44_read <= ap_const_logic_0;
        end if; 
    end process;

    HwReg_layerScaleFactor_3_val44_readcast14_fu_180_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(HwReg_layerScaleFactor_3_val44_dout),16));
    HwReg_layerScaleFactor_3_val44_readcast_fu_170_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(HwReg_layerScaleFactor_3_val44_dout),16));

    HwReg_layerStartX_3_val28_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, HwReg_layerStartX_3_val28_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            HwReg_layerStartX_3_val28_blk_n <= HwReg_layerStartX_3_val28_empty_n;
        else 
            HwReg_layerStartX_3_val28_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    HwReg_layerStartX_3_val28_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            HwReg_layerStartX_3_val28_read <= ap_const_logic_1;
        else 
            HwReg_layerStartX_3_val28_read <= ap_const_logic_0;
        end if; 
    end process;


    HwReg_layerStartY_3_val32_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, HwReg_layerStartY_3_val32_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            HwReg_layerStartY_3_val32_blk_n <= HwReg_layerStartY_3_val32_empty_n;
        else 
            HwReg_layerStartY_3_val32_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    HwReg_layerStartY_3_val32_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            HwReg_layerStartY_3_val32_read <= ap_const_logic_1;
        else 
            HwReg_layerStartY_3_val32_read <= ap_const_logic_0;
        end if; 
    end process;


    HwReg_layerWidth_3_val_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, HwReg_layerWidth_3_val_empty_n)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            HwReg_layerWidth_3_val_blk_n <= HwReg_layerWidth_3_val_empty_n;
        else 
            HwReg_layerWidth_3_val_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    HwReg_layerWidth_3_val_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            HwReg_layerWidth_3_val_read <= ap_const_logic_1;
        else 
            HwReg_layerWidth_3_val_read <= ap_const_logic_0;
        end if; 
    end process;

    add60_i_fu_208_p2 <= std_logic_vector(unsigned(layerHeight_cast_i_fu_204_p1) + unsigned(hwReg_layerStartY_3_val_cast_i_fu_200_p1));
    add71_i_fu_232_p2 <= std_logic_vector(unsigned(layerWidth_cast_i_fu_228_p1) + unsigned(hwReg_layerStartX_3_val_cast_i_fu_214_p1));
    add_ln463_fu_269_p2 <= std_logic_vector(unsigned(y_fu_94) + unsigned(ap_const_lv12_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_v_mix_core_alpha_false_false_21_Pipeline_VITIS_LOOP_465_3_fu_154_ap_done)
    begin
        if ((grp_v_mix_core_alpha_false_false_21_Pipeline_VITIS_LOOP_465_3_fu_154_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, HwReg_layerEnable_val25_empty_n, HwReg_layerStartX_3_val28_empty_n, HwReg_layerStartY_3_val32_empty_n, HwReg_layerWidth_3_val_empty_n, HwReg_layerHeight_3_val_empty_n, HwReg_layerScaleFactor_3_val44_empty_n, HwReg_layerEnable_val25_c_full_n)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (ap_const_logic_0 = HwReg_layerEnable_val25_c_full_n) or (ap_const_logic_0 = HwReg_layerScaleFactor_3_val44_empty_n) or (ap_const_logic_0 = HwReg_layerHeight_3_val_empty_n) or (ap_const_logic_0 = HwReg_layerWidth_3_val_empty_n) or (ap_const_logic_0 = HwReg_layerStartY_3_val32_empty_n) or (ap_const_logic_0 = HwReg_layerStartX_3_val28_empty_n) or (ap_const_logic_0 = HwReg_layerEnable_val25_empty_n) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state2, icmp_ln463_fu_264_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln463_fu_264_p2 = ap_const_lv1_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln463_fu_264_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (icmp_ln463_fu_264_p2 = ap_const_lv1_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    cmp61_i_fu_295_p2 <= "1" when (unsigned(add60_i_reg_328) > unsigned(zext_ln463_fu_275_p1)) else "0";
    grp_v_mix_core_alpha_false_false_21_Pipeline_VITIS_LOOP_465_3_fu_154_ap_start <= grp_v_mix_core_alpha_false_false_21_Pipeline_VITIS_LOOP_465_3_fu_154_ap_start_reg;
    hwReg_layerStartX_3_val_cast_i_fu_214_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(HwReg_layerStartX_3_val28_dout),17));
    hwReg_layerStartY_3_val_cast_i_fu_200_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(HwReg_layerStartY_3_val32_dout),17));
    icmp_ln463_fu_264_p2 <= "1" when (y_fu_94 = HwReg_height_val_read_reg_313) else "0";
    layerHeight_cast_i_fu_204_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln449_fu_174_p2),17));
    layerWidth_cast_i_fu_228_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln450_fu_184_p2),17));
    outLayer2_read <= grp_v_mix_core_alpha_false_false_21_Pipeline_VITIS_LOOP_465_3_fu_154_outLayer2_read;
    outLayer3_din <= grp_v_mix_core_alpha_false_false_21_Pipeline_VITIS_LOOP_465_3_fu_154_outLayer3_din;
    outLayer3_write <= grp_v_mix_core_alpha_false_false_21_Pipeline_VITIS_LOOP_465_3_fu_154_outLayer3_write;
    rev13_fu_288_p2 <= (ult_fu_283_p2 xor ap_const_lv1_1);
    shl_ln449_fu_174_p2 <= std_logic_vector(shift_left(unsigned(HwReg_layerHeight_3_val_dout),to_integer(unsigned('0' & HwReg_layerScaleFactor_3_val44_readcast_fu_170_p1(16-1 downto 0)))));
    shl_ln450_fu_184_p2 <= std_logic_vector(shift_left(unsigned(HwReg_layerWidth_3_val_dout),to_integer(unsigned('0' & HwReg_layerScaleFactor_3_val44_readcast14_fu_180_p1(16-1 downto 0)))));
    srcLayer3x_read <= grp_v_mix_core_alpha_false_false_21_Pipeline_VITIS_LOOP_465_3_fu_154_srcLayer3x_read;
    ult_fu_283_p2 <= "1" when (unsigned(zext_ln463_2_fu_279_p1) < unsigned(layerStartY_reg_318)) else "0";
    zext_ln463_2_fu_279_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y_fu_94),16));
    zext_ln463_fu_275_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(y_fu_94),17));
end behav;
