-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity bd_quad_vmix_dp_v_tpg_2_0_tpgForeground_Pipeline_VITIS_LOOP_774_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    bckgndYUV_dout : IN STD_LOGIC_VECTOR (47 downto 0);
    bckgndYUV_empty_n : IN STD_LOGIC;
    bckgndYUV_read : OUT STD_LOGIC;
    bckgndYUV_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    bckgndYUV_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    ovrlayYUV_din : OUT STD_LOGIC_VECTOR (47 downto 0);
    ovrlayYUV_full_n : IN STD_LOGIC;
    ovrlayYUV_write : OUT STD_LOGIC;
    ovrlayYUV_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
    ovrlayYUV_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
    width_val_cast : IN STD_LOGIC_VECTOR (15 downto 0);
    conv2_i_i_i : IN STD_LOGIC_VECTOR (7 downto 0);
    patternId_val_load : IN STD_LOGIC_VECTOR (7 downto 0);
    boxSize : IN STD_LOGIC_VECTOR (15 downto 0);
    y : IN STD_LOGIC_VECTOR (15 downto 0);
    boxColorB : IN STD_LOGIC_VECTOR (7 downto 0);
    boxColorG : IN STD_LOGIC_VECTOR (7 downto 0);
    boxColorR : IN STD_LOGIC_VECTOR (7 downto 0);
    pixOut_18 : IN STD_LOGIC_VECTOR (7 downto 0);
    vMax : IN STD_LOGIC_VECTOR (15 downto 0);
    motionSpeed : IN STD_LOGIC_VECTOR (7 downto 0);
    hMax : IN STD_LOGIC_VECTOR (15 downto 0);
    zext_ln1974 : IN STD_LOGIC_VECTOR (8 downto 0);
    crossHairX_val_cast : IN STD_LOGIC_VECTOR (15 downto 0);
    cmp2_i : IN STD_LOGIC_VECTOR (0 downto 0);
    crossHairX : IN STD_LOGIC_VECTOR (15 downto 0);
    whiYuv_load : IN STD_LOGIC_VECTOR (7 downto 0);
    color : IN STD_LOGIC_VECTOR (7 downto 0);
    maskId : IN STD_LOGIC_VECTOR (7 downto 0);
    cmp11_i : IN STD_LOGIC_VECTOR (0 downto 0);
    empty_36 : IN STD_LOGIC_VECTOR (0 downto 0);
    empty_37 : IN STD_LOGIC_VECTOR (0 downto 0);
    empty : IN STD_LOGIC_VECTOR (0 downto 0);
    boxHCoord_loc_1_out_i : IN STD_LOGIC_VECTOR (15 downto 0);
    boxHCoord_loc_1_out_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    boxHCoord_loc_1_out_o_ap_vld : OUT STD_LOGIC;
    boxVCoord_loc_1_out_i : IN STD_LOGIC_VECTOR (15 downto 0);
    boxVCoord_loc_1_out_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    boxVCoord_loc_1_out_o_ap_vld : OUT STD_LOGIC;
    boxVCoord : OUT STD_LOGIC_VECTOR (15 downto 0);
    boxVCoord_ap_vld : OUT STD_LOGIC;
    boxHCoord : OUT STD_LOGIC_VECTOR (15 downto 0);
    boxHCoord_ap_vld : OUT STD_LOGIC );
end;


architecture behav of bd_quad_vmix_dp_v_tpg_2_0_tpgForeground_Pipeline_VITIS_LOOP_774_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv8_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv8_F0 : STD_LOGIC_VECTOR (7 downto 0) := "11110000";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv17_2 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000010";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal icmp_ln774_reg_1065 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln774_fu_445_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal vDir : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal hDir : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal ovrlayYUV_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal bckgndYUV_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal patternId_val_load_read_read_fu_270_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal patternId_val_load_read_reg_1021 : STD_LOGIC_VECTOR (7 downto 0);
    signal cmp11_i7_fu_406_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal cmp11_i7_reg_1032 : STD_LOGIC_VECTOR (0 downto 0);
    signal tobool_fu_412_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tobool_reg_1037 : STD_LOGIC_VECTOR (0 downto 0);
    signal and26_i_fu_418_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and26_i_reg_1047 : STD_LOGIC_VECTOR (0 downto 0);
    signal and10_i_fu_424_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and10_i_reg_1053 : STD_LOGIC_VECTOR (0 downto 0);
    signal and4_i_fu_430_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and4_i_reg_1059 : STD_LOGIC_VECTOR (0 downto 0);
    signal x_2_fu_451_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal x_2_reg_1069 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln1884_fu_461_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1884_reg_1075 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_fu_381_p4 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_1_reg_1097 : STD_LOGIC_VECTOR (14 downto 0);
    signal or_ln1963_fu_591_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1963_reg_1102 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1963_2_fu_611_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1963_2_reg_1109 : STD_LOGIC_VECTOR (0 downto 0);
    signal pixIn_fu_628_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixIn_11_fu_632_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixIn_12_fu_642_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixIn_13_fu_652_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixIn_14_fu_662_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixIn_15_fu_672_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixOut_16_fu_770_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixOut_15_fu_777_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixOut_14_fu_784_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixOut_20_fu_828_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixOut_19_fu_835_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixOut_17_fu_842_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixOut_8_fu_849_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixOut_7_fu_855_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixOut_6_fu_861_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln1974_fu_868_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_pix_10_reg_301 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_pix_10_reg_301 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter2_pix_10_reg_301 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_pix_9_reg_314 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_pix_9_reg_314 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter2_pix_9_reg_314 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_pix_8_reg_327 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_pix_8_reg_327 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter2_pix_8_reg_327 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_pix_7_reg_342 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_pix_7_reg_342 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter2_pix_7_reg_342 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_pix_6_reg_355 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_pix_6_reg_355 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter2_pix_6_reg_355 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_pix_reg_368 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_pix_reg_368 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter2_pix_reg_368 : STD_LOGIC_VECTOR (7 downto 0);
    signal sub_ln1914_fu_479_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln1912_fu_485_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal hDir_load_load_fu_471_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1889_fu_491_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1894_fu_509_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_grp0 : BOOLEAN;
    signal sub_ln1918_fu_537_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln1916_fu_543_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal vDir_load_load_fu_475_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1906_fu_561_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1901_fu_549_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal x_fu_146 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    signal add_ln774_fu_617_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_x_1 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal width_val_cast_cast_fu_402_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal or_ln1884_fu_455_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal motionSpeed_cast_fu_398_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln1974_cast_fu_394_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal crossHairX_val_cast_cast_fu_390_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal icmp_ln1963_fu_585_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1963_1_fu_597_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln1963_1_fu_605_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal boxBottom_fu_715_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln1942_fu_720_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1942_1_fu_731_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1942_fu_725_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal boxRight_fu_710_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln1942_3_fu_747_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1942_2_fu_742_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1942_fu_736_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1942_1_fu_758_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1942_1_fu_752_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1942_2_fu_764_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln_fu_791_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln1942_5_fu_804_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1942_4_fu_798_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1942_3_fu_816_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln1942_2_fu_810_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1942_4_fu_822_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln1993_fu_881_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixOut_27_fu_874_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln1991_fu_902_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln1989_fu_916_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln1991_1_fu_930_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln1993_1_fu_944_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal p_0_5_0_0_0155_fu_888_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_82_fu_909_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_83_fu_923_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_85_fu_951_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_84_fu_937_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal pixOut_28_fu_895_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_332 : BOOLEAN;
    signal ap_condition_339 : BOOLEAN;
    signal ap_condition_272 : BOOLEAN;
    signal ap_condition_757 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component bd_quad_vmix_dp_v_tpg_2_0_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component bd_quad_vmix_dp_v_tpg_2_0_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp0_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0)) then 
                    ap_block_pp0_stage0_subdone_grp0_done_reg <= ap_const_boolean_1;
                end if; 
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter2_pix_10_reg_301_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln774_reg_1065 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (patternId_val_load_read_reg_1021 = ap_const_lv8_1))) then 
                ap_phi_reg_pp0_iter2_pix_10_reg_301 <= pixOut_20_fu_828_p3;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln774_reg_1065 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (or_ln1963_2_reg_1109 = ap_const_lv1_1) and (patternId_val_load_read_reg_1021 = ap_const_lv8_2))) then 
                ap_phi_reg_pp0_iter2_pix_10_reg_301 <= conv2_i_i_i;
            elsif (((not((patternId_val_load_read_reg_1021 = ap_const_lv8_1)) and not((patternId_val_load_read_reg_1021 = ap_const_lv8_2)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln774_reg_1065 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln774_reg_1065 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (or_ln1963_2_reg_1109 = ap_const_lv1_0) and (patternId_val_load_read_reg_1021 = ap_const_lv8_2)))) then 
                ap_phi_reg_pp0_iter2_pix_10_reg_301 <= bckgndYUV_dout(47 downto 40);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                ap_phi_reg_pp0_iter2_pix_10_reg_301 <= ap_phi_reg_pp0_iter1_pix_10_reg_301;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter2_pix_6_reg_355_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln774_reg_1065 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (patternId_val_load_read_reg_1021 = ap_const_lv8_1))) then 
                ap_phi_reg_pp0_iter2_pix_6_reg_355 <= pixOut_15_fu_777_p3;
            elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln774_reg_1065 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (or_ln1963_2_reg_1109 = ap_const_lv1_1) and (patternId_val_load_read_reg_1021 = ap_const_lv8_2)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln774_reg_1065 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (or_ln1963_2_reg_1109 = ap_const_lv1_0) and (patternId_val_load_read_reg_1021 = ap_const_lv8_2)))) then 
                ap_phi_reg_pp0_iter2_pix_6_reg_355 <= pixOut_7_fu_855_p3;
            elsif ((not((patternId_val_load_read_reg_1021 = ap_const_lv8_1)) and not((patternId_val_load_read_reg_1021 = ap_const_lv8_2)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln774_reg_1065 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                ap_phi_reg_pp0_iter2_pix_6_reg_355 <= bckgndYUV_dout(15 downto 8);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                ap_phi_reg_pp0_iter2_pix_6_reg_355 <= ap_phi_reg_pp0_iter1_pix_6_reg_355;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter2_pix_7_reg_342_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln774_reg_1065 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (patternId_val_load_read_reg_1021 = ap_const_lv8_1))) then 
                ap_phi_reg_pp0_iter2_pix_7_reg_342 <= pixOut_16_fu_770_p3;
            elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln774_reg_1065 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (or_ln1963_2_reg_1109 = ap_const_lv1_1) and (patternId_val_load_read_reg_1021 = ap_const_lv8_2)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln774_reg_1065 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (or_ln1963_2_reg_1109 = ap_const_lv1_0) and (patternId_val_load_read_reg_1021 = ap_const_lv8_2)))) then 
                ap_phi_reg_pp0_iter2_pix_7_reg_342 <= pixOut_8_fu_849_p3;
            elsif ((not((patternId_val_load_read_reg_1021 = ap_const_lv8_1)) and not((patternId_val_load_read_reg_1021 = ap_const_lv8_2)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln774_reg_1065 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                ap_phi_reg_pp0_iter2_pix_7_reg_342 <= bckgndYUV_dout(23 downto 16);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                ap_phi_reg_pp0_iter2_pix_7_reg_342 <= ap_phi_reg_pp0_iter1_pix_7_reg_342;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter2_pix_8_reg_327_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln774_reg_1065 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (patternId_val_load_read_reg_1021 = ap_const_lv8_1))) then 
                ap_phi_reg_pp0_iter2_pix_8_reg_327 <= pixOut_17_fu_842_p3;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln774_reg_1065 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (or_ln1963_2_reg_1109 = ap_const_lv1_1) and (patternId_val_load_read_reg_1021 = ap_const_lv8_2))) then 
                ap_phi_reg_pp0_iter2_pix_8_reg_327 <= ap_const_lv8_F0;
            elsif (((not((patternId_val_load_read_reg_1021 = ap_const_lv8_1)) and not((patternId_val_load_read_reg_1021 = ap_const_lv8_2)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln774_reg_1065 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln774_reg_1065 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (or_ln1963_2_reg_1109 = ap_const_lv1_0) and (patternId_val_load_read_reg_1021 = ap_const_lv8_2)))) then 
                ap_phi_reg_pp0_iter2_pix_8_reg_327 <= bckgndYUV_dout(31 downto 24);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                ap_phi_reg_pp0_iter2_pix_8_reg_327 <= ap_phi_reg_pp0_iter1_pix_8_reg_327;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter2_pix_9_reg_314_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln774_reg_1065 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (patternId_val_load_read_reg_1021 = ap_const_lv8_1))) then 
                ap_phi_reg_pp0_iter2_pix_9_reg_314 <= pixOut_19_fu_835_p3;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln774_reg_1065 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (or_ln1963_2_reg_1109 = ap_const_lv1_1) and (patternId_val_load_read_reg_1021 = ap_const_lv8_2))) then 
                ap_phi_reg_pp0_iter2_pix_9_reg_314 <= select_ln1974_fu_868_p3;
            elsif (((not((patternId_val_load_read_reg_1021 = ap_const_lv8_1)) and not((patternId_val_load_read_reg_1021 = ap_const_lv8_2)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln774_reg_1065 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln774_reg_1065 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (or_ln1963_2_reg_1109 = ap_const_lv1_0) and (patternId_val_load_read_reg_1021 = ap_const_lv8_2)))) then 
                ap_phi_reg_pp0_iter2_pix_9_reg_314 <= bckgndYUV_dout(39 downto 32);
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                ap_phi_reg_pp0_iter2_pix_9_reg_314 <= ap_phi_reg_pp0_iter1_pix_9_reg_314;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter2_pix_reg_368_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln774_reg_1065 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (patternId_val_load_read_reg_1021 = ap_const_lv8_1))) then 
                ap_phi_reg_pp0_iter2_pix_reg_368 <= pixOut_14_fu_784_p3;
            elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln774_reg_1065 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (or_ln1963_2_reg_1109 = ap_const_lv1_1) and (patternId_val_load_read_reg_1021 = ap_const_lv8_2)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln774_reg_1065 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (or_ln1963_2_reg_1109 = ap_const_lv1_0) and (patternId_val_load_read_reg_1021 = ap_const_lv8_2)))) then 
                ap_phi_reg_pp0_iter2_pix_reg_368 <= pixOut_6_fu_861_p3;
            elsif ((not((patternId_val_load_read_reg_1021 = ap_const_lv8_1)) and not((patternId_val_load_read_reg_1021 = ap_const_lv8_2)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln774_reg_1065 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                ap_phi_reg_pp0_iter2_pix_reg_368 <= pixIn_fu_628_p1;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                ap_phi_reg_pp0_iter2_pix_reg_368 <= ap_phi_reg_pp0_iter1_pix_reg_368;
            end if; 
        end if;
    end process;

    hDir_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_757)) then
                if (((icmp_ln1894_fu_509_p2 = ap_const_lv1_1) and (hDir_load_load_fu_471_p1 = ap_const_lv1_1))) then 
                    hDir <= ap_const_lv1_0;
                elsif (((icmp_ln1889_fu_491_p2 = ap_const_lv1_1) and (hDir_load_load_fu_471_p1 = ap_const_lv1_0))) then 
                    hDir <= ap_const_lv1_1;
                end if;
            end if; 
        end if;
    end process;

    vDir_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_757)) then
                if (((icmp_ln1906_fu_561_p2 = ap_const_lv1_1) and (vDir_load_load_fu_475_p1 = ap_const_lv1_1))) then 
                    vDir <= ap_const_lv1_0;
                elsif (((icmp_ln1901_fu_549_p2 = ap_const_lv1_1) and (vDir_load_load_fu_475_p1 = ap_const_lv1_0))) then 
                    vDir <= ap_const_lv1_1;
                end if;
            end if; 
        end if;
    end process;

    x_fu_146_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln774_fu_445_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    x_fu_146 <= add_ln774_fu_617_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    x_fu_146 <= ap_const_lv17_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                and10_i_reg_1053 <= and10_i_fu_424_p2;
                and26_i_reg_1047 <= and26_i_fu_418_p2;
                and4_i_reg_1059 <= and4_i_fu_430_p2;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                cmp11_i7_reg_1032 <= cmp11_i7_fu_406_p2;
                icmp_ln1884_reg_1075 <= icmp_ln1884_fu_461_p2;
                icmp_ln774_reg_1065 <= icmp_ln774_fu_445_p2;
                or_ln1963_2_reg_1109 <= or_ln1963_2_fu_611_p2;
                or_ln1963_reg_1102 <= or_ln1963_fu_591_p2;
                tobool_reg_1037 <= tobool_fu_412_p2;
                x_2_reg_1069 <= x_2_fu_451_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_phi_reg_pp0_iter1_pix_10_reg_301 <= ap_phi_reg_pp0_iter0_pix_10_reg_301;
                ap_phi_reg_pp0_iter1_pix_6_reg_355 <= ap_phi_reg_pp0_iter0_pix_6_reg_355;
                ap_phi_reg_pp0_iter1_pix_7_reg_342 <= ap_phi_reg_pp0_iter0_pix_7_reg_342;
                ap_phi_reg_pp0_iter1_pix_8_reg_327 <= ap_phi_reg_pp0_iter0_pix_8_reg_327;
                ap_phi_reg_pp0_iter1_pix_9_reg_314 <= ap_phi_reg_pp0_iter0_pix_9_reg_314;
                ap_phi_reg_pp0_iter1_pix_reg_368 <= ap_phi_reg_pp0_iter0_pix_reg_368;
                tmp_1_reg_1097 <= ap_sig_allocacmp_x_1(15 downto 1);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln1912_fu_485_p2 <= std_logic_vector(unsigned(boxHCoord_loc_1_out_i) + unsigned(motionSpeed_cast_fu_398_p1));
    add_ln1916_fu_543_p2 <= std_logic_vector(unsigned(boxVCoord_loc_1_out_i) + unsigned(motionSpeed_cast_fu_398_p1));
    add_ln774_fu_617_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_x_1) + unsigned(ap_const_lv17_2));
    and10_i_fu_424_p2 <= (empty_37 and cmp11_i);
    and26_i_fu_418_p2 <= (empty_36 and cmp11_i);
    and4_i_fu_430_p2 <= (empty and cmp11_i);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_block_state2_pp0_stage0_iter1, ap_block_state3_pp0_stage0_iter2)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_block_state2_pp0_stage0_iter1, ap_block_state3_pp0_stage0_iter2)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)));
    end process;

        ap_block_pp0_stage0_11001_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_block_state2_pp0_stage0_iter1, ap_block_state3_pp0_stage0_iter2)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)));
    end process;

        ap_block_pp0_stage0_subdone_grp0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state2_pp0_stage0_iter1_assign_proc : process(bckgndYUV_empty_n, icmp_ln774_reg_1065)
    begin
                ap_block_state2_pp0_stage0_iter1 <= ((icmp_ln774_reg_1065 = ap_const_lv1_1) and (bckgndYUV_empty_n = ap_const_logic_0));
    end process;


    ap_block_state3_pp0_stage0_iter2_assign_proc : process(ovrlayYUV_full_n)
    begin
                ap_block_state3_pp0_stage0_iter2 <= (ovrlayYUV_full_n = ap_const_logic_0);
    end process;


    ap_condition_272_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0)
    begin
                ap_condition_272 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_332_assign_proc : process(icmp_ln774_fu_445_p2, patternId_val_load_read_read_fu_270_p2, icmp_ln1884_fu_461_p2, vDir_load_load_fu_475_p1, icmp_ln1906_fu_561_p2, icmp_ln1901_fu_549_p2)
    begin
                ap_condition_332 <= (((icmp_ln774_fu_445_p2 = ap_const_lv1_1) and (icmp_ln1901_fu_549_p2 = ap_const_lv1_1) and (vDir_load_load_fu_475_p1 = ap_const_lv1_0) and (icmp_ln1884_fu_461_p2 = ap_const_lv1_1) and (patternId_val_load_read_read_fu_270_p2 = ap_const_lv8_1)) or ((icmp_ln774_fu_445_p2 = ap_const_lv1_1) and (icmp_ln1906_fu_561_p2 = ap_const_lv1_0) and (vDir_load_load_fu_475_p1 = ap_const_lv1_1) and (icmp_ln1884_fu_461_p2 = ap_const_lv1_1) and (patternId_val_load_read_read_fu_270_p2 = ap_const_lv8_1)));
    end process;


    ap_condition_339_assign_proc : process(icmp_ln774_fu_445_p2, patternId_val_load_read_read_fu_270_p2, icmp_ln1884_fu_461_p2, vDir_load_load_fu_475_p1, icmp_ln1906_fu_561_p2, icmp_ln1901_fu_549_p2)
    begin
                ap_condition_339 <= (((icmp_ln774_fu_445_p2 = ap_const_lv1_1) and (icmp_ln1901_fu_549_p2 = ap_const_lv1_0) and (vDir_load_load_fu_475_p1 = ap_const_lv1_0) and (icmp_ln1884_fu_461_p2 = ap_const_lv1_1) and (patternId_val_load_read_read_fu_270_p2 = ap_const_lv8_1)) or ((icmp_ln774_fu_445_p2 = ap_const_lv1_1) and (icmp_ln1906_fu_561_p2 = ap_const_lv1_1) and (vDir_load_load_fu_475_p1 = ap_const_lv1_1) and (icmp_ln1884_fu_461_p2 = ap_const_lv1_1) and (patternId_val_load_read_read_fu_270_p2 = ap_const_lv8_1)));
    end process;


    ap_condition_757_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, icmp_ln774_fu_445_p2, ap_block_pp0_stage0_11001, patternId_val_load_read_read_fu_270_p2, icmp_ln1884_fu_461_p2)
    begin
                ap_condition_757 <= ((icmp_ln774_fu_445_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln1884_fu_461_p2 = ap_const_lv1_1) and (patternId_val_load_read_read_fu_270_p2 = ap_const_lv8_1));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln774_fu_445_p2)
    begin
        if (((icmp_ln774_fu_445_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_phi_reg_pp0_iter0_pix_10_reg_301 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_pix_6_reg_355 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_pix_7_reg_342 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_pix_8_reg_327 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_pix_9_reg_314 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter0_pix_reg_368 <= "XXXXXXXX";
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_x_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, x_fu_146, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_x_1 <= ap_const_lv17_0;
        else 
            ap_sig_allocacmp_x_1 <= x_fu_146;
        end if; 
    end process;


    bckgndYUV_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, bckgndYUV_empty_n, icmp_ln774_reg_1065, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln774_reg_1065 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            bckgndYUV_blk_n <= bckgndYUV_empty_n;
        else 
            bckgndYUV_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    bckgndYUV_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln774_reg_1065, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln774_reg_1065 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            bckgndYUV_read <= ap_const_logic_1;
        else 
            bckgndYUV_read <= ap_const_logic_0;
        end if; 
    end process;

    boxBottom_fu_715_p2 <= std_logic_vector(unsigned(boxSize) + unsigned(boxVCoord_loc_1_out_i));
    boxHCoord <= boxHCoord_loc_1_out_i;

    boxHCoord_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln774_reg_1065, patternId_val_load_read_reg_1021, icmp_ln1884_reg_1075, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (icmp_ln774_reg_1065 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln1884_reg_1075 = ap_const_lv1_1) and (patternId_val_load_read_reg_1021 = ap_const_lv8_1))) then 
            boxHCoord_ap_vld <= ap_const_logic_1;
        else 
            boxHCoord_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    boxHCoord_loc_1_out_o_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, icmp_ln774_fu_445_p2, boxHCoord_loc_1_out_i, ap_block_pp0_stage0, patternId_val_load_read_read_fu_270_p2, icmp_ln1884_fu_461_p2, sub_ln1914_fu_479_p2, add_ln1912_fu_485_p2, hDir_load_load_fu_471_p1, icmp_ln1889_fu_491_p2, icmp_ln1894_fu_509_p2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (((icmp_ln774_fu_445_p2 = ap_const_lv1_1) and (icmp_ln1889_fu_491_p2 = ap_const_lv1_0) and (hDir_load_load_fu_471_p1 = ap_const_lv1_0) and (icmp_ln1884_fu_461_p2 = ap_const_lv1_1) and (patternId_val_load_read_read_fu_270_p2 = ap_const_lv8_1)) or ((icmp_ln774_fu_445_p2 = ap_const_lv1_1) and (icmp_ln1894_fu_509_p2 = ap_const_lv1_1) and (hDir_load_load_fu_471_p1 = ap_const_lv1_1) and (icmp_ln1884_fu_461_p2 = ap_const_lv1_1) and (patternId_val_load_read_read_fu_270_p2 = ap_const_lv8_1))))) then 
            boxHCoord_loc_1_out_o <= add_ln1912_fu_485_p2;
        elsif ((((icmp_ln774_fu_445_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln1894_fu_509_p2 = ap_const_lv1_0) and (hDir_load_load_fu_471_p1 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln1884_fu_461_p2 = ap_const_lv1_1) and (patternId_val_load_read_read_fu_270_p2 = ap_const_lv8_1)) or ((icmp_ln774_fu_445_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln1889_fu_491_p2 = ap_const_lv1_1) and (hDir_load_load_fu_471_p1 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln1884_fu_461_p2 = ap_const_lv1_1) and (patternId_val_load_read_read_fu_270_p2 = ap_const_lv8_1)))) then 
            boxHCoord_loc_1_out_o <= sub_ln1914_fu_479_p2;
        else 
            boxHCoord_loc_1_out_o <= boxHCoord_loc_1_out_i;
        end if; 
    end process;


    boxHCoord_loc_1_out_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, icmp_ln774_fu_445_p2, ap_block_pp0_stage0_11001, patternId_val_load_read_read_fu_270_p2, icmp_ln1884_fu_461_p2, hDir_load_load_fu_471_p1, icmp_ln1889_fu_491_p2, icmp_ln1894_fu_509_p2)
    begin
        if ((((icmp_ln774_fu_445_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1894_fu_509_p2 = ap_const_lv1_0) and (hDir_load_load_fu_471_p1 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln1884_fu_461_p2 = ap_const_lv1_1) and (patternId_val_load_read_read_fu_270_p2 = ap_const_lv8_1)) or ((icmp_ln774_fu_445_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln1889_fu_491_p2 = ap_const_lv1_1) and (hDir_load_load_fu_471_p1 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln1884_fu_461_p2 = ap_const_lv1_1) and (patternId_val_load_read_read_fu_270_p2 = ap_const_lv8_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (((icmp_ln774_fu_445_p2 = ap_const_lv1_1) and (icmp_ln1889_fu_491_p2 = ap_const_lv1_0) and 
    (hDir_load_load_fu_471_p1 = ap_const_lv1_0) and (icmp_ln1884_fu_461_p2 = ap_const_lv1_1) and (patternId_val_load_read_read_fu_270_p2 = ap_const_lv8_1)) or ((icmp_ln774_fu_445_p2 = ap_const_lv1_1) and (icmp_ln1894_fu_509_p2 = ap_const_lv1_1) and (hDir_load_load_fu_471_p1 = ap_const_lv1_1) and (icmp_ln1884_fu_461_p2 = ap_const_lv1_1) and (patternId_val_load_read_read_fu_270_p2 = ap_const_lv8_1)))))) then 
            boxHCoord_loc_1_out_o_ap_vld <= ap_const_logic_1;
        else 
            boxHCoord_loc_1_out_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    boxRight_fu_710_p2 <= std_logic_vector(unsigned(boxSize) + unsigned(boxHCoord_loc_1_out_i));
    boxVCoord <= boxVCoord_loc_1_out_i;

    boxVCoord_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, patternId_val_load_read_reg_1021, icmp_ln1884_reg_1075, ap_block_pp0_stage0_11001_grp0, ap_block_pp0_stage0_subdone_grp0_done_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp0_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln1884_reg_1075 = ap_const_lv1_1) and (patternId_val_load_read_reg_1021 = ap_const_lv8_1))) then 
            boxVCoord_ap_vld <= ap_const_logic_1;
        else 
            boxVCoord_ap_vld <= ap_const_logic_0;
        end if; 
    end process;


    boxVCoord_loc_1_out_o_assign_proc : process(boxVCoord_loc_1_out_i, sub_ln1918_fu_537_p2, add_ln1916_fu_543_p2, ap_condition_332, ap_condition_339, ap_condition_272)
    begin
        if ((ap_const_boolean_1 = ap_condition_272)) then
            if ((ap_const_boolean_1 = ap_condition_339)) then 
                boxVCoord_loc_1_out_o <= add_ln1916_fu_543_p2;
            elsif ((ap_const_boolean_1 = ap_condition_332)) then 
                boxVCoord_loc_1_out_o <= sub_ln1918_fu_537_p2;
            else 
                boxVCoord_loc_1_out_o <= boxVCoord_loc_1_out_i;
            end if;
        else 
            boxVCoord_loc_1_out_o <= boxVCoord_loc_1_out_i;
        end if; 
    end process;


    boxVCoord_loc_1_out_o_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, icmp_ln774_fu_445_p2, ap_block_pp0_stage0_11001, patternId_val_load_read_read_fu_270_p2, icmp_ln1884_fu_461_p2, vDir_load_load_fu_475_p1, icmp_ln1906_fu_561_p2, icmp_ln1901_fu_549_p2)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (((icmp_ln774_fu_445_p2 = ap_const_lv1_1) and (icmp_ln1901_fu_549_p2 = ap_const_lv1_0) and (vDir_load_load_fu_475_p1 = ap_const_lv1_0) and (icmp_ln1884_fu_461_p2 = ap_const_lv1_1) and (patternId_val_load_read_read_fu_270_p2 = ap_const_lv8_1)) or ((icmp_ln774_fu_445_p2 = ap_const_lv1_1) and (icmp_ln1906_fu_561_p2 = ap_const_lv1_1) and (vDir_load_load_fu_475_p1 = ap_const_lv1_1) and (icmp_ln1884_fu_461_p2 = ap_const_lv1_1) and (patternId_val_load_read_read_fu_270_p2 = ap_const_lv8_1)))) or ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (((icmp_ln774_fu_445_p2 = ap_const_lv1_1) and (icmp_ln1901_fu_549_p2 = ap_const_lv1_1) and (vDir_load_load_fu_475_p1 = ap_const_lv1_0) and (icmp_ln1884_fu_461_p2 = ap_const_lv1_1) and (patternId_val_load_read_read_fu_270_p2 = ap_const_lv8_1)) 
    or ((icmp_ln774_fu_445_p2 = ap_const_lv1_1) and (icmp_ln1906_fu_561_p2 = ap_const_lv1_0) and (vDir_load_load_fu_475_p1 = ap_const_lv1_1) and (icmp_ln1884_fu_461_p2 = ap_const_lv1_1) and (patternId_val_load_read_read_fu_270_p2 = ap_const_lv8_1)))))) then 
            boxVCoord_loc_1_out_o_ap_vld <= ap_const_logic_1;
        else 
            boxVCoord_loc_1_out_o_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    cmp11_i7_fu_406_p2 <= "1" when (color = ap_const_lv8_0) else "0";
    crossHairX_val_cast_cast_fu_390_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(crossHairX_val_cast),17));
    empty_82_fu_909_p3 <= 
        ap_phi_reg_pp0_iter2_pix_9_reg_314 when (tobool_reg_1037(0) = '1') else 
        select_ln1991_fu_902_p3;
    empty_83_fu_923_p3 <= 
        ap_phi_reg_pp0_iter2_pix_8_reg_327 when (tobool_reg_1037(0) = '1') else 
        select_ln1989_fu_916_p3;
    empty_84_fu_937_p3 <= 
        ap_phi_reg_pp0_iter2_pix_6_reg_355 when (tobool_reg_1037(0) = '1') else 
        select_ln1991_1_fu_930_p3;
    empty_85_fu_951_p3 <= 
        ap_phi_reg_pp0_iter2_pix_7_reg_342 when (tobool_reg_1037(0) = '1') else 
        select_ln1993_1_fu_944_p3;
    grp_fu_381_p4 <= ap_sig_allocacmp_x_1(15 downto 1);
    hDir_load_load_fu_471_p1 <= hDir;
    icmp_ln1884_fu_461_p2 <= "1" when (or_ln1884_fu_455_p2 = ap_const_lv16_0) else "0";
    icmp_ln1889_fu_491_p2 <= "1" when (unsigned(boxHCoord_loc_1_out_i) > unsigned(hMax)) else "0";
    icmp_ln1894_fu_509_p2 <= "1" when (unsigned(zext_ln1974_cast_fu_394_p1) > unsigned(boxHCoord_loc_1_out_i)) else "0";
    icmp_ln1901_fu_549_p2 <= "1" when (unsigned(boxVCoord_loc_1_out_i) > unsigned(vMax)) else "0";
    icmp_ln1906_fu_561_p2 <= "1" when (unsigned(zext_ln1974_cast_fu_394_p1) > unsigned(boxVCoord_loc_1_out_i)) else "0";
    icmp_ln1942_1_fu_731_p2 <= "1" when (unsigned(y) < unsigned(boxVCoord_loc_1_out_i)) else "0";
    icmp_ln1942_2_fu_742_p2 <= "1" when (unsigned(x_2_reg_1069) < unsigned(boxHCoord_loc_1_out_i)) else "0";
    icmp_ln1942_3_fu_747_p2 <= "1" when (unsigned(x_2_reg_1069) < unsigned(boxRight_fu_710_p2)) else "0";
    icmp_ln1942_4_fu_798_p2 <= "1" when (unsigned(or_ln_fu_791_p3) < unsigned(boxHCoord_loc_1_out_i)) else "0";
    icmp_ln1942_5_fu_804_p2 <= "1" when (unsigned(or_ln_fu_791_p3) < unsigned(boxRight_fu_710_p2)) else "0";
    icmp_ln1942_fu_720_p2 <= "1" when (unsigned(y) < unsigned(boxBottom_fu_715_p2)) else "0";
    icmp_ln1963_1_fu_605_p2 <= "1" when (or_ln1963_1_fu_597_p3 = crossHairX) else "0";
    icmp_ln1963_fu_585_p2 <= "1" when (ap_sig_allocacmp_x_1 = crossHairX_val_cast_cast_fu_390_p1) else "0";
    icmp_ln774_fu_445_p2 <= "1" when (unsigned(ap_sig_allocacmp_x_1) < unsigned(width_val_cast_cast_fu_402_p1)) else "0";
    motionSpeed_cast_fu_398_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(motionSpeed),16));
    or_ln1884_fu_455_p2 <= (y or x_2_fu_451_p1);
    or_ln1942_1_fu_758_p2 <= (or_ln1942_fu_736_p2 or icmp_ln1942_2_fu_742_p2);
    or_ln1942_2_fu_764_p2 <= (xor_ln1942_1_fu_752_p2 or or_ln1942_1_fu_758_p2);
    or_ln1942_3_fu_816_p2 <= (or_ln1942_fu_736_p2 or icmp_ln1942_4_fu_798_p2);
    or_ln1942_4_fu_822_p2 <= (xor_ln1942_2_fu_810_p2 or or_ln1942_3_fu_816_p2);
    or_ln1942_fu_736_p2 <= (xor_ln1942_fu_725_p2 or icmp_ln1942_1_fu_731_p2);
    or_ln1963_1_fu_597_p3 <= (grp_fu_381_p4 & ap_const_lv1_1);
    or_ln1963_2_fu_611_p2 <= (icmp_ln1963_1_fu_605_p2 or cmp2_i);
    or_ln1963_fu_591_p2 <= (icmp_ln1963_fu_585_p2 or cmp2_i);
    or_ln_fu_791_p3 <= (tmp_1_reg_1097 & ap_const_lv1_1);

    ovrlayYUV_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, ovrlayYUV_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            ovrlayYUV_blk_n <= ovrlayYUV_full_n;
        else 
            ovrlayYUV_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    ovrlayYUV_din <= (((((p_0_5_0_0_0155_fu_888_p3 & empty_82_fu_909_p3) & empty_83_fu_923_p3) & empty_85_fu_951_p3) & empty_84_fu_937_p3) & pixOut_28_fu_895_p3);

    ovrlayYUV_write_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            ovrlayYUV_write <= ap_const_logic_1;
        else 
            ovrlayYUV_write <= ap_const_logic_0;
        end if; 
    end process;

    p_0_5_0_0_0155_fu_888_p3 <= 
        ap_phi_reg_pp0_iter2_pix_10_reg_301 when (tobool_reg_1037(0) = '1') else 
        select_ln1993_fu_881_p3;
    patternId_val_load_read_read_fu_270_p2 <= patternId_val_load;
    patternId_val_load_read_reg_1021 <= patternId_val_load;
    pixIn_11_fu_632_p4 <= bckgndYUV_dout(15 downto 8);
    pixIn_12_fu_642_p4 <= bckgndYUV_dout(23 downto 16);
    pixIn_13_fu_652_p4 <= bckgndYUV_dout(31 downto 24);
    pixIn_14_fu_662_p4 <= bckgndYUV_dout(39 downto 32);
    pixIn_15_fu_672_p4 <= bckgndYUV_dout(47 downto 40);
    pixIn_fu_628_p1 <= bckgndYUV_dout(8 - 1 downto 0);
    pixOut_14_fu_784_p3 <= 
        pixIn_fu_628_p1 when (or_ln1942_2_fu_764_p2(0) = '1') else 
        boxColorR;
    pixOut_15_fu_777_p3 <= 
        pixIn_11_fu_632_p4 when (or_ln1942_2_fu_764_p2(0) = '1') else 
        boxColorG;
    pixOut_16_fu_770_p3 <= 
        pixIn_12_fu_642_p4 when (or_ln1942_2_fu_764_p2(0) = '1') else 
        boxColorB;
    pixOut_17_fu_842_p3 <= 
        pixIn_13_fu_652_p4 when (or_ln1942_4_fu_822_p2(0) = '1') else 
        boxColorR;
    pixOut_19_fu_835_p3 <= 
        pixIn_14_fu_662_p4 when (or_ln1942_4_fu_822_p2(0) = '1') else 
        pixOut_18;
    pixOut_20_fu_828_p3 <= 
        pixIn_15_fu_672_p4 when (or_ln1942_4_fu_822_p2(0) = '1') else 
        boxColorB;
    pixOut_27_fu_874_p3 <= 
        ap_const_lv8_0 when (and4_i_reg_1059(0) = '1') else 
        ap_phi_reg_pp0_iter2_pix_reg_368;
    pixOut_28_fu_895_p3 <= 
        ap_phi_reg_pp0_iter2_pix_reg_368 when (tobool_reg_1037(0) = '1') else 
        pixOut_27_fu_874_p3;
    pixOut_6_fu_861_p3 <= 
        ap_const_lv8_F0 when (or_ln1963_reg_1102(0) = '1') else 
        pixIn_fu_628_p1;
    pixOut_7_fu_855_p3 <= 
        conv2_i_i_i when (or_ln1963_reg_1102(0) = '1') else 
        pixIn_11_fu_632_p4;
    pixOut_8_fu_849_p3 <= 
        conv2_i_i_i when (or_ln1963_reg_1102(0) = '1') else 
        pixIn_12_fu_642_p4;
    select_ln1974_fu_868_p3 <= 
        ap_const_lv8_F0 when (cmp11_i7_reg_1032(0) = '1') else 
        whiYuv_load;
    select_ln1989_fu_916_p3 <= 
        ap_const_lv8_0 when (and4_i_reg_1059(0) = '1') else 
        ap_phi_reg_pp0_iter2_pix_8_reg_327;
    select_ln1991_1_fu_930_p3 <= 
        ap_const_lv8_0 when (and10_i_reg_1053(0) = '1') else 
        ap_phi_reg_pp0_iter2_pix_6_reg_355;
    select_ln1991_fu_902_p3 <= 
        ap_const_lv8_0 when (and10_i_reg_1053(0) = '1') else 
        ap_phi_reg_pp0_iter2_pix_9_reg_314;
    select_ln1993_1_fu_944_p3 <= 
        ap_const_lv8_0 when (and26_i_reg_1047(0) = '1') else 
        ap_phi_reg_pp0_iter2_pix_7_reg_342;
    select_ln1993_fu_881_p3 <= 
        ap_const_lv8_0 when (and26_i_reg_1047(0) = '1') else 
        ap_phi_reg_pp0_iter2_pix_10_reg_301;
    sub_ln1914_fu_479_p2 <= std_logic_vector(unsigned(boxHCoord_loc_1_out_i) - unsigned(motionSpeed_cast_fu_398_p1));
    sub_ln1918_fu_537_p2 <= std_logic_vector(unsigned(boxVCoord_loc_1_out_i) - unsigned(motionSpeed_cast_fu_398_p1));
    tobool_fu_412_p2 <= "1" when (maskId = ap_const_lv8_0) else "0";
    vDir_load_load_fu_475_p1 <= vDir;
    width_val_cast_cast_fu_402_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(width_val_cast),17));
    x_2_fu_451_p1 <= ap_sig_allocacmp_x_1(16 - 1 downto 0);
    xor_ln1942_1_fu_752_p2 <= (icmp_ln1942_3_fu_747_p2 xor ap_const_lv1_1);
    xor_ln1942_2_fu_810_p2 <= (icmp_ln1942_5_fu_804_p2 xor ap_const_lv1_1);
    xor_ln1942_fu_725_p2 <= (icmp_ln1942_fu_720_p2 xor ap_const_lv1_1);
    zext_ln1974_cast_fu_394_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln1974),16));
end behav;
