// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module bd_quad_vmix_dp_v_tpg_0_0_tpgBackground (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        height_val,
        width_val,
        patternId_val,
        motionSpeed_val,
        colorFormat_val,
        bckgndYUV_din,
        bckgndYUV_full_n,
        bckgndYUV_write,
        bckgndYUV_num_data_valid,
        bckgndYUV_fifo_cap,
        height_val4_c3_din,
        height_val4_c3_full_n,
        height_val4_c3_write,
        height_val4_c3_num_data_valid,
        height_val4_c3_fifo_cap,
        width_val7_c4_din,
        width_val7_c4_full_n,
        width_val7_c4_write,
        width_val7_c4_num_data_valid,
        width_val7_c4_fifo_cap,
        motionSpeed_val14_c_din,
        motionSpeed_val14_c_full_n,
        motionSpeed_val14_c_write,
        motionSpeed_val14_c_num_data_valid,
        motionSpeed_val14_c_fifo_cap,
        colorFormat_val17_c5_din,
        colorFormat_val17_c5_full_n,
        colorFormat_val17_c5_write,
        colorFormat_val17_c5_num_data_valid,
        colorFormat_val17_c5_fifo_cap,
        s
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [15:0] height_val;
input  [15:0] width_val;
input  [7:0] patternId_val;
input  [7:0] motionSpeed_val;
input  [7:0] colorFormat_val;
output  [47:0] bckgndYUV_din;
input   bckgndYUV_full_n;
output   bckgndYUV_write;
input  [4:0] bckgndYUV_num_data_valid;
input  [4:0] bckgndYUV_fifo_cap;
output  [15:0] height_val4_c3_din;
input   height_val4_c3_full_n;
output   height_val4_c3_write;
input  [2:0] height_val4_c3_num_data_valid;
input  [2:0] height_val4_c3_fifo_cap;
output  [15:0] width_val7_c4_din;
input   width_val7_c4_full_n;
output   width_val7_c4_write;
input  [2:0] width_val7_c4_num_data_valid;
input  [2:0] width_val7_c4_fifo_cap;
output  [7:0] motionSpeed_val14_c_din;
input   motionSpeed_val14_c_full_n;
output   motionSpeed_val14_c_write;
input  [2:0] motionSpeed_val14_c_num_data_valid;
input  [2:0] motionSpeed_val14_c_fifo_cap;
output  [7:0] colorFormat_val17_c5_din;
input   colorFormat_val17_c5_full_n;
output   colorFormat_val17_c5_write;
input  [2:0] colorFormat_val17_c5_num_data_valid;
input  [2:0] colorFormat_val17_c5_fifo_cap;
input  [31:0] s;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg height_val4_c3_write;
reg width_val7_c4_write;
reg motionSpeed_val14_c_write;
reg colorFormat_val17_c5_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [1:0] blkYuv_address0;
wire   [7:0] blkYuv_q0;
wire   [1:0] whiYuv_address0;
wire   [7:0] whiYuv_q0;
wire   [1:0] blkYuv_1_address0;
wire   [7:0] blkYuv_1_q0;
reg   [7:0] tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel;
reg   [7:0] tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_6;
reg   [2:0] vBarSel;
reg   [2:0] tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_3;
reg   [2:0] tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_2;
reg   [7:0] vBarSel_1;
reg   [2:0] tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_3;
reg   [2:0] tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_2;
reg   [7:0] rampStart;
reg    height_val4_c3_blk_n;
reg    width_val7_c4_blk_n;
reg    motionSpeed_val14_c_blk_n;
reg    colorFormat_val17_c5_blk_n;
reg   [7:0] colorFormat_val_read_reg_807;
reg    ap_block_state1;
reg   [7:0] motionSpeed_val_read_reg_813;
reg   [15:0] width_val_read_reg_818;
reg   [15:0] height_val_read_reg_824;
reg   [6:0] tmp_25_reg_830;
wire   [13:0] trunc_ln563_fu_447_p1;
reg   [13:0] trunc_ln563_reg_835;
reg   [9:0] tmp_reg_846;
reg   [7:0] patternId_val_read_reg_861;
wire    ap_CS_fsm_state2;
reg   [10:0] barWidth_reg_866;
wire   [7:0] empty_93_fu_615_p1;
reg   [7:0] empty_93_reg_872;
wire   [9:0] barWidthMinSamples_fu_634_p2;
reg   [9:0] barWidthMinSamples_reg_877;
wire   [10:0] sub_i_i_i87_fu_643_p2;
reg   [10:0] sub_i_i_i87_reg_882;
wire   [16:0] sub35_i_fu_649_p2;
reg   [16:0] sub35_i_reg_887;
wire   [16:0] sub10_i_fu_655_p2;
reg   [16:0] sub10_i_reg_893;
wire   [7:0] spec_select270_fu_661_p3;
reg   [7:0] spec_select270_reg_898;
wire   [7:0] spec_select_fu_669_p3;
reg   [7:0] spec_select_reg_903;
reg   [7:0] blkYuv_load_reg_908;
reg   [7:0] whiYuv_load_reg_913;
reg   [7:0] blkYuv_1_load_reg_918;
reg   [15:0] y_3_reg_923;
wire    ap_CS_fsm_state3;
wire   [0:0] cmp11_i_fu_696_p2;
reg   [0:0] cmp11_i_reg_931;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_ap_start;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_ap_done;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_ap_idle;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_ap_ready;
wire   [47:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_bckgndYUV_din;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_bckgndYUV_write;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_l_2_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_l_2_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_6_3_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_6_3_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_vBarSel_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_vBarSel_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_8_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_8_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_9_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_9_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_vBarSel_1_loc_1_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_vBarSel_1_loc_1_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_8_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_8_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_9_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_9_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_outpix_0_5_0_0_0_load330_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_outpix_0_5_0_0_0_load330_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_outpix_0_4_0_0_0_load328_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_outpix_0_4_0_0_0_load328_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_outpix_0_3_0_0_0_load326_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_outpix_0_3_0_0_0_load326_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_outpix_0_2_0_0_0_load324_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_outpix_0_2_0_0_0_load324_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_outpix_0_1_0_0_0_load322_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_outpix_0_1_0_0_0_load322_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_outpix_0_0_0_0_0_load320_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_outpix_0_0_0_0_0_load320_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_6;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_6_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_ap_vld;
wire   [2:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_2;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_2_ap_vld;
wire   [2:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_3;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_3_ap_vld;
wire   [2:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_vBarSel;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_vBarSel_ap_vld;
wire   [2:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_2;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_2_ap_vld;
wire   [2:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_3;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_3_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_vBarSel_1;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_vBarSel_1_ap_vld;
reg    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_ap_start_reg;
wire   [0:0] icmp_ln563_fu_681_p2;
wire    ap_CS_fsm_state4;
reg   [7:0] tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_l_1_fu_232;
reg   [7:0] tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_6_2_fu_228;
reg   [7:0] vBarSel_loc_0_fu_224;
reg   [7:0] tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_6_fu_220;
reg   [7:0] tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_7_fu_216;
reg   [7:0] vBarSel_1_loc_0_fu_212;
reg   [7:0] tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_6_fu_208;
reg   [7:0] tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_7_fu_204;
reg   [7:0] outpix_0_5_0_0_0_load331_lcssa349_fu_196;
reg   [7:0] outpix_0_4_0_0_0_load329_lcssa346_fu_192;
reg   [7:0] outpix_0_3_0_0_0_load327_lcssa343_fu_188;
reg   [7:0] outpix_0_2_0_0_0_load325_lcssa340_fu_184;
reg   [7:0] outpix_0_1_0_0_0_load323_lcssa337_fu_180;
reg   [7:0] outpix_0_0_0_0_0_load321_lcssa334_fu_176;
wire   [63:0] idxprom13_1_i262_cast_cast_cast_fu_467_p3;
wire   [7:0] add_ln750_fu_711_p2;
reg   [15:0] y_fu_200;
wire   [15:0] add_ln563_fu_686_p2;
wire   [7:0] zext_ln563_1_fu_536_p1;
wire   [7:0] zext_ln1593_fu_528_p1;
wire   [7:0] zext_ln1575_fu_516_p1;
wire   [7:0] zext_ln1412_1_fu_508_p1;
wire   [7:0] zext_ln1412_fu_500_p1;
reg    blkYuv_ce0_local;
reg    whiYuv_ce0_local;
reg    blkYuv_1_ce0_local;
wire   [13:0] empty_fu_451_p1;
wire   [0:0] cmp6_i258_fu_455_p2;
wire   [13:0] add5_i83_fu_461_p2;
wire   [13:0] add_i_fu_600_p2;
wire   [13:0] add2_i80_fu_619_p2;
wire   [9:0] p_cast_fu_624_p4;
wire   [10:0] barHeight_cast_fu_640_p1;
wire   [16:0] zext_ln563_fu_585_p1;
wire   [16:0] height_val_cast17_fu_588_p1;
wire   [0:0] cmp4_i257_fu_591_p2;
wire   [16:0] zext_ln563_2_fu_692_p1;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel = 8'd0;
#0 tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_6 = 8'd0;
#0 vBarSel = 3'd0;
#0 tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_3 = 3'd0;
#0 tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_2 = 3'd0;
#0 vBarSel_1 = 8'd0;
#0 tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_3 = 3'd0;
#0 tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_2 = 3'd0;
#0 rampStart = 8'd0;
#0 grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_ap_start_reg = 1'b0;
#0 tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_l_1_fu_232 = 8'd0;
#0 tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_6_2_fu_228 = 8'd0;
#0 vBarSel_loc_0_fu_224 = 8'd0;
#0 tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_6_fu_220 = 8'd0;
#0 tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_7_fu_216 = 8'd0;
#0 vBarSel_1_loc_0_fu_212 = 8'd0;
#0 tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_6_fu_208 = 8'd0;
#0 tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_7_fu_204 = 8'd0;
#0 y_fu_200 = 16'd0;
end

bd_quad_vmix_dp_v_tpg_0_0_tpgBackground_blkYuv_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
blkYuv_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(blkYuv_address0),
    .ce0(blkYuv_ce0_local),
    .q0(blkYuv_q0)
);

bd_quad_vmix_dp_v_tpg_0_0_tpgBackground_whiYuv_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
whiYuv_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(whiYuv_address0),
    .ce0(whiYuv_ce0_local),
    .q0(whiYuv_q0)
);

bd_quad_vmix_dp_v_tpg_0_0_tpgBackground_blkYuv_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
blkYuv_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(blkYuv_1_address0),
    .ce0(blkYuv_1_ce0_local),
    .q0(blkYuv_1_q0)
);

bd_quad_vmix_dp_v_tpg_0_0_tpgBackground_Pipeline_VITIS_LOOP_565_2 grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_ap_start),
    .ap_done(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_ap_done),
    .ap_idle(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_ap_idle),
    .ap_ready(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_ap_ready),
    .bckgndYUV_din(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_bckgndYUV_din),
    .bckgndYUV_full_n(bckgndYUV_full_n),
    .bckgndYUV_write(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_bckgndYUV_write),
    .bckgndYUV_num_data_valid(5'd0),
    .bckgndYUV_fifo_cap(5'd0),
    .zext_ln563(width_val_read_reg_818),
    .spec_select(spec_select_reg_903),
    .spec_select270(spec_select270_reg_898),
    .patternId_val(patternId_val_read_reg_861),
    .blkYuv_load(blkYuv_load_reg_908),
    .empty_38(empty_93_reg_872),
    .barWidth(barWidth_reg_866),
    .barWidth_cast(barWidth_reg_866),
    .barWidthMinSamples(barWidthMinSamples_reg_877),
    .y(y_3_reg_923),
    .sub_i_i_i87(sub_i_i_i87_reg_882),
    .blkYuv_1_load(blkYuv_1_load_reg_918),
    .sub35_i(sub35_i_reg_887),
    .cmp11_i(cmp11_i_reg_931),
    .sub35_i_cast(sub35_i_reg_887),
    .whiYuv_load(whiYuv_load_reg_913),
    .colorFormat_val(colorFormat_val_read_reg_807),
    .empty(tmp_25_reg_830),
    .tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_l_2_out_i(tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_l_1_fu_232),
    .tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_l_2_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_l_2_out_o),
    .tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_l_2_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_l_2_out_o_ap_vld),
    .tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_6_3_out_i(tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_6_2_fu_228),
    .tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_6_3_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_6_3_out_o),
    .tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_6_3_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_6_3_out_o_ap_vld),
    .vBarSel_loc_1_out_i(vBarSel_loc_0_fu_224),
    .vBarSel_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_vBarSel_loc_1_out_o),
    .vBarSel_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_vBarSel_loc_1_out_o_ap_vld),
    .tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_8_out_i(tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_6_fu_220),
    .tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_8_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_8_out_o),
    .tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_8_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_8_out_o_ap_vld),
    .tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_9_out_i(tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_7_fu_216),
    .tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_9_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_9_out_o),
    .tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_9_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_9_out_o_ap_vld),
    .vBarSel_1_loc_1_out_i(vBarSel_1_loc_0_fu_212),
    .vBarSel_1_loc_1_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_vBarSel_1_loc_1_out_o),
    .vBarSel_1_loc_1_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_vBarSel_1_loc_1_out_o_ap_vld),
    .tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_8_out_i(tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_6_fu_208),
    .tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_8_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_8_out_o),
    .tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_8_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_8_out_o_ap_vld),
    .tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_9_out_i(tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_7_fu_204),
    .tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_9_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_9_out_o),
    .tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_9_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_9_out_o_ap_vld),
    .outpix_0_5_0_0_0_load330_out_i(outpix_0_5_0_0_0_load331_lcssa349_fu_196),
    .outpix_0_5_0_0_0_load330_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_outpix_0_5_0_0_0_load330_out_o),
    .outpix_0_5_0_0_0_load330_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_outpix_0_5_0_0_0_load330_out_o_ap_vld),
    .outpix_0_4_0_0_0_load328_out_i(outpix_0_4_0_0_0_load329_lcssa346_fu_192),
    .outpix_0_4_0_0_0_load328_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_outpix_0_4_0_0_0_load328_out_o),
    .outpix_0_4_0_0_0_load328_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_outpix_0_4_0_0_0_load328_out_o_ap_vld),
    .outpix_0_3_0_0_0_load326_out_i(outpix_0_3_0_0_0_load327_lcssa343_fu_188),
    .outpix_0_3_0_0_0_load326_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_outpix_0_3_0_0_0_load326_out_o),
    .outpix_0_3_0_0_0_load326_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_outpix_0_3_0_0_0_load326_out_o_ap_vld),
    .outpix_0_2_0_0_0_load324_out_i(outpix_0_2_0_0_0_load325_lcssa340_fu_184),
    .outpix_0_2_0_0_0_load324_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_outpix_0_2_0_0_0_load324_out_o),
    .outpix_0_2_0_0_0_load324_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_outpix_0_2_0_0_0_load324_out_o_ap_vld),
    .outpix_0_1_0_0_0_load322_out_i(outpix_0_1_0_0_0_load323_lcssa337_fu_180),
    .outpix_0_1_0_0_0_load322_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_outpix_0_1_0_0_0_load322_out_o),
    .outpix_0_1_0_0_0_load322_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_outpix_0_1_0_0_0_load322_out_o_ap_vld),
    .outpix_0_0_0_0_0_load320_out_i(outpix_0_0_0_0_0_load321_lcssa334_fu_176),
    .outpix_0_0_0_0_0_load320_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_outpix_0_0_0_0_0_load320_out_o),
    .outpix_0_0_0_0_0_load320_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_outpix_0_0_0_0_0_load320_out_o_ap_vld),
    .tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_6(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_6),
    .tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_6_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_6_ap_vld),
    .tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel),
    .tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_ap_vld),
    .tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_2(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_2),
    .tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_2_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_2_ap_vld),
    .tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_3(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_3),
    .tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_3_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_3_ap_vld),
    .vBarSel(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_vBarSel),
    .vBarSel_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_vBarSel_ap_vld),
    .tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_2(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_2),
    .tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_2_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_2_ap_vld),
    .tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_3(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_3),
    .tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_3_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_3_ap_vld),
    .vBarSel_1(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_vBarSel_1),
    .vBarSel_1_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_vBarSel_1_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln563_fu_681_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln563_fu_681_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
            grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_ap_start_reg <= 1'b1;
        end else if ((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_ap_ready == 1'b1)) begin
            grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_6_fu_208 <= zext_ln1593_fu_528_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_8_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_6_fu_208 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_8_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_7_fu_204 <= zext_ln563_1_fu_536_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_9_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_7_fu_204 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_9_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_6_2_fu_228 <= tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_6;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_6_3_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_6_2_fu_228 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_6_3_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_l_1_fu_232 <= tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_l_2_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_l_1_fu_232 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_l_2_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_6_fu_220 <= zext_ln1412_1_fu_508_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_8_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_6_fu_220 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_8_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_7_fu_216 <= zext_ln1575_fu_516_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_9_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_7_fu_216 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_9_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        vBarSel_1_loc_0_fu_212 <= vBarSel_1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_vBarSel_1_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        vBarSel_1_loc_0_fu_212 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_vBarSel_1_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        vBarSel_loc_0_fu_224 <= zext_ln1412_fu_500_p1;
    end else if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_vBarSel_loc_1_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        vBarSel_loc_0_fu_224 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_vBarSel_loc_1_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        y_fu_200 <= 16'd0;
    end else if (((icmp_ln563_fu_681_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        y_fu_200 <= add_ln563_fu_686_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        barWidthMinSamples_reg_877 <= barWidthMinSamples_fu_634_p2;
        barWidth_reg_866 <= {{add_i_fu_600_p2[13:3]}};
        blkYuv_1_load_reg_918 <= blkYuv_1_q0;
        blkYuv_load_reg_908 <= blkYuv_q0;
        empty_93_reg_872 <= empty_93_fu_615_p1;
        patternId_val_read_reg_861 <= patternId_val;
        spec_select270_reg_898[6 : 0] <= spec_select270_fu_661_p3[6 : 0];
        spec_select_reg_903[7] <= spec_select_fu_669_p3[7];
        sub10_i_reg_893 <= sub10_i_fu_655_p2;
        sub35_i_reg_887 <= sub35_i_fu_649_p2;
        sub_i_i_i87_reg_882 <= sub_i_i_i87_fu_643_p2;
        whiYuv_load_reg_913 <= whiYuv_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        cmp11_i_reg_931 <= cmp11_i_fu_696_p2;
        y_3_reg_923 <= y_fu_200;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        colorFormat_val_read_reg_807 <= colorFormat_val;
        height_val_read_reg_824 <= height_val;
        motionSpeed_val_read_reg_813 <= motionSpeed_val;
        tmp_25_reg_830 <= {{colorFormat_val[7:1]}};
        tmp_reg_846 <= {{add5_i83_fu_461_p2[13:4]}};
        trunc_ln563_reg_835 <= trunc_ln563_fu_447_p1;
        width_val_read_reg_818 <= width_val;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_outpix_0_0_0_0_0_load320_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        outpix_0_0_0_0_0_load321_lcssa334_fu_176 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_outpix_0_0_0_0_0_load320_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_outpix_0_1_0_0_0_load322_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        outpix_0_1_0_0_0_load323_lcssa337_fu_180 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_outpix_0_1_0_0_0_load322_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_outpix_0_2_0_0_0_load324_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        outpix_0_2_0_0_0_load325_lcssa340_fu_184 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_outpix_0_2_0_0_0_load324_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_outpix_0_3_0_0_0_load326_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        outpix_0_3_0_0_0_load327_lcssa343_fu_188 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_outpix_0_3_0_0_0_load326_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_outpix_0_4_0_0_0_load328_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        outpix_0_4_0_0_0_load329_lcssa346_fu_192 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_outpix_0_4_0_0_0_load328_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_outpix_0_5_0_0_0_load330_out_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        outpix_0_5_0_0_0_load331_lcssa349_fu_196 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_outpix_0_5_0_0_0_load330_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln563_fu_681_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        rampStart <= add_ln750_fu_711_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_2_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_2 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_3_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_3 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_3;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_6_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_6 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternColorBars_unsigned_short_unsigned_short_unsigned_char_int_hBarSel_6;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_2_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_2 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_2;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_3_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_3 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_3;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_vBarSel_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        vBarSel <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_vBarSel;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_vBarSel_1_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        vBarSel_1 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_vBarSel_1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln563_fu_681_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln563_fu_681_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        blkYuv_1_ce0_local = 1'b1;
    end else begin
        blkYuv_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        blkYuv_ce0_local = 1'b1;
    end else begin
        blkYuv_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        colorFormat_val17_c5_blk_n = colorFormat_val17_c5_full_n;
    end else begin
        colorFormat_val17_c5_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        colorFormat_val17_c5_write = 1'b1;
    end else begin
        colorFormat_val17_c5_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        height_val4_c3_blk_n = height_val4_c3_full_n;
    end else begin
        height_val4_c3_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        height_val4_c3_write = 1'b1;
    end else begin
        height_val4_c3_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        motionSpeed_val14_c_blk_n = motionSpeed_val14_c_full_n;
    end else begin
        motionSpeed_val14_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        motionSpeed_val14_c_write = 1'b1;
    end else begin
        motionSpeed_val14_c_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        whiYuv_ce0_local = 1'b1;
    end else begin
        whiYuv_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        width_val7_c4_blk_n = width_val7_c4_full_n;
    end else begin
        width_val7_c4_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        width_val7_c4_write = 1'b1;
    end else begin
        width_val7_c4_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln563_fu_681_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add2_i80_fu_619_p2 = (trunc_ln563_reg_835 + 14'd15);

assign add5_i83_fu_461_p2 = (empty_fu_451_p1 + 14'd15);

assign add_i_fu_600_p2 = (trunc_ln563_reg_835 + 14'd7);

assign add_ln563_fu_686_p2 = (y_fu_200 + 16'd1);

assign add_ln750_fu_711_p2 = (rampStart + motionSpeed_val_read_reg_813);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (colorFormat_val17_c5_full_n == 1'b0) | (motionSpeed_val14_c_full_n == 1'b0) | (width_val7_c4_full_n == 1'b0) | (height_val4_c3_full_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign barHeight_cast_fu_640_p1 = tmp_reg_846;

assign barWidthMinSamples_fu_634_p2 = ($signed(p_cast_fu_624_p4) + $signed(10'd1022));

assign bckgndYUV_din = grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_bckgndYUV_din;

assign bckgndYUV_write = grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_bckgndYUV_write;

assign blkYuv_1_address0 = idxprom13_1_i262_cast_cast_cast_fu_467_p3;

assign blkYuv_address0 = idxprom13_1_i262_cast_cast_cast_fu_467_p3;

assign cmp11_i_fu_696_p2 = ((sub10_i_reg_893 == zext_ln563_2_fu_692_p1) ? 1'b1 : 1'b0);

assign cmp4_i257_fu_591_p2 = ((colorFormat_val_read_reg_807 == 8'd0) ? 1'b1 : 1'b0);

assign cmp6_i258_fu_455_p2 = ((colorFormat_val == 8'd1) ? 1'b1 : 1'b0);

assign colorFormat_val17_c5_din = colorFormat_val;

assign empty_93_fu_615_p1 = s[7:0];

assign empty_fu_451_p1 = height_val[13:0];

assign grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_ap_start = grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_337_ap_start_reg;

assign height_val4_c3_din = height_val;

assign height_val_cast17_fu_588_p1 = height_val_read_reg_824;

assign icmp_ln563_fu_681_p2 = ((y_fu_200 == height_val_read_reg_824) ? 1'b1 : 1'b0);

assign idxprom13_1_i262_cast_cast_cast_fu_467_p3 = ((cmp6_i258_fu_455_p2[0:0] == 1'b1) ? 64'd1 : 64'd2);

assign motionSpeed_val14_c_din = motionSpeed_val;

assign p_cast_fu_624_p4 = {{add2_i80_fu_619_p2[13:4]}};

assign spec_select270_fu_661_p3 = ((cmp4_i257_fu_591_p2[0:0] == 1'b1) ? 8'd255 : 8'd128);

assign spec_select_fu_669_p3 = ((cmp4_i257_fu_591_p2[0:0] == 1'b1) ? 8'd0 : 8'd128);

assign sub10_i_fu_655_p2 = ($signed(height_val_cast17_fu_588_p1) + $signed(17'd131071));

assign sub35_i_fu_649_p2 = ($signed(zext_ln563_fu_585_p1) + $signed(17'd131071));

assign sub_i_i_i87_fu_643_p2 = ($signed(barHeight_cast_fu_640_p1) + $signed(11'd2047));

assign trunc_ln563_fu_447_p1 = width_val[13:0];

assign whiYuv_address0 = idxprom13_1_i262_cast_cast_cast_fu_467_p3;

assign width_val7_c4_din = width_val;

assign zext_ln1412_1_fu_508_p1 = tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_3;

assign zext_ln1412_fu_500_p1 = vBarSel;

assign zext_ln1575_fu_516_p1 = tpgPatternTartanColorBars_unsigned_short_unsigned_short_unsigned_short_unsign_2;

assign zext_ln1593_fu_528_p1 = tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_3;

assign zext_ln563_1_fu_536_p1 = tpgPatternCheckerBoard_unsigned_short_unsigned_short_unsigned_short_unsigned_2;

assign zext_ln563_2_fu_692_p1 = y_fu_200;

assign zext_ln563_fu_585_p1 = width_val_read_reg_818;

always @ (posedge ap_clk) begin
    spec_select270_reg_898[7] <= 1'b1;
    spec_select_reg_903[6:0] <= 7'b0000000;
end

endmodule //bd_quad_vmix_dp_v_tpg_0_0_tpgBackground
