-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity bd_quad_vmix_dp_v_tpg_3_0_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    counter_loc_0_i : IN STD_LOGIC_VECTOR (15 downto 0);
    sof : IN STD_LOGIC_VECTOR (0 downto 0);
    div_i : IN STD_LOGIC_VECTOR (9 downto 0);
    ovrlayYUV_dout : IN STD_LOGIC_VECTOR (47 downto 0);
    ovrlayYUV_empty_n : IN STD_LOGIC;
    ovrlayYUV_read : OUT STD_LOGIC;
    ovrlayYUV_num_data_valid : IN STD_LOGIC_VECTOR (4 downto 0);
    ovrlayYUV_fifo_cap : IN STD_LOGIC_VECTOR (4 downto 0);
    colorFormat_val17_load : IN STD_LOGIC_VECTOR (7 downto 0);
    m_axis_video_TDATA : OUT STD_LOGIC_VECTOR (47 downto 0);
    m_axis_video_TVALID : OUT STD_LOGIC;
    m_axis_video_TREADY : IN STD_LOGIC;
    m_axis_video_TKEEP : OUT STD_LOGIC_VECTOR (5 downto 0);
    m_axis_video_TSTRB : OUT STD_LOGIC_VECTOR (5 downto 0);
    m_axis_video_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axis_video_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axis_video_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axis_video_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
    sub_i : IN STD_LOGIC_VECTOR (10 downto 0);
    counter_loc_1_i_out : OUT STD_LOGIC_VECTOR (15 downto 0);
    counter_loc_1_i_out_ap_vld : OUT STD_LOGIC;
    phi_ln1036_out : OUT STD_LOGIC_VECTOR (0 downto 0);
    phi_ln1036_out_ap_vld : OUT STD_LOGIC;
    counter : OUT STD_LOGIC_VECTOR (15 downto 0);
    counter_ap_vld : OUT STD_LOGIC );
end;


architecture behav of bd_quad_vmix_dp_v_tpg_3_0_MultiPixStream2AXIvideo_Pipeline_VITIS_LOOP_981_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv10_0 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv6_3F : STD_LOGIC_VECTOR (5 downto 0) := "111111";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv10_1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ovrlayYUV_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal icmp_ln981_reg_603 : STD_LOGIC_VECTOR (0 downto 0);
    signal m_axis_video_TDATA_blk_n : STD_LOGIC;
    signal sof_2_reg_233 : STD_LOGIC_VECTOR (0 downto 0);
    signal phi_ln1036_reg_245 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln981_fu_271_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state3_pp0_stage0_iter1_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal axi_last_fu_286_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal axi_last_reg_607 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln1008_fu_319_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state2 : STD_LOGIC;
    signal ap_phi_mux_sof_2_phi_fu_237_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal add_ln1005_fu_294_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal j_fu_146 : STD_LOGIC_VECTOR (9 downto 0) := "0000000000";
    signal j_2_fu_276_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal counter_loc_1_i_fu_150 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal zext_ln981_fu_282_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal pix_444_fu_323_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal pix_rgb_4_fu_327_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln1020_fu_393_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1020_1_fu_398_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal axi_data_fu_377_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal axi_data_2_fu_411_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal axi_data_2_fu_411_p7 : STD_LOGIC_VECTOR (8 downto 0);
    signal sel_tmp2_fu_403_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal axi_data_2_fu_411_p9 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_fu_435_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_fu_435_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_fu_435_p6 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_fu_435_p7 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_1_fu_455_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_1_fu_455_p6 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_1_fu_455_p7 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_fu_475_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_fu_475_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_fu_475_p6 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_fu_475_p7 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_3_fu_495_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_3_fu_495_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_3_fu_495_p6 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_3_fu_495_p7 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_4_fu_515_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_4_fu_515_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_4_fu_515_p6 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_4_fu_515_p7 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_4_fu_515_p9 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_3_fu_495_p9 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_fu_475_p9 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_1_fu_455_p9 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_fu_435_p9 : STD_LOGIC_VECTOR (7 downto 0);
    signal sext_ln925_fu_431_p1 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_5_fu_535_p6 : STD_LOGIC_VECTOR (39 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal axi_data_2_fu_411_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal axi_data_2_fu_411_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal axi_data_2_fu_411_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_435_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_435_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_435_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_fu_455_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_fu_455_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_fu_455_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_2_fu_475_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_2_fu_475_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_2_fu_475_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_3_fu_495_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_3_fu_495_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_3_fu_495_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_4_fu_515_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_4_fu_515_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_4_fu_515_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component bd_quad_vmix_dp_v_tpg_3_0_sparsemux_7_2_9_1_1_x IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (8 downto 0);
        din1 : IN STD_LOGIC_VECTOR (8 downto 0);
        din2 : IN STD_LOGIC_VECTOR (8 downto 0);
        def : IN STD_LOGIC_VECTOR (8 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (8 downto 0) );
    end component;


    component bd_quad_vmix_dp_v_tpg_3_0_sparsemux_7_2_8_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        def : IN STD_LOGIC_VECTOR (7 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    sparsemux_7_2_9_1_1_x_U136 : component bd_quad_vmix_dp_v_tpg_3_0_sparsemux_7_2_9_1_1_x
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "10",
        din0_WIDTH => 9,
        CASE1 => "01",
        din1_WIDTH => 9,
        CASE2 => "00",
        din2_WIDTH => 9,
        def_WIDTH => 9,
        sel_WIDTH => 2,
        dout_WIDTH => 9)
    port map (
        din0 => axi_data_fu_377_p3,
        din1 => axi_data_2_fu_411_p4,
        din2 => axi_data_fu_377_p3,
        def => axi_data_2_fu_411_p7,
        sel => sel_tmp2_fu_403_p3,
        dout => axi_data_2_fu_411_p9);

    sparsemux_7_2_8_1_1_U137 : component bd_quad_vmix_dp_v_tpg_3_0_sparsemux_7_2_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "10",
        din0_WIDTH => 8,
        CASE1 => "01",
        din1_WIDTH => 8,
        CASE2 => "00",
        din2_WIDTH => 8,
        def_WIDTH => 8,
        sel_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => tmp_fu_435_p2,
        din1 => tmp_fu_435_p4,
        din2 => tmp_fu_435_p6,
        def => tmp_fu_435_p7,
        sel => sel_tmp2_fu_403_p3,
        dout => tmp_fu_435_p9);

    sparsemux_7_2_8_1_1_U138 : component bd_quad_vmix_dp_v_tpg_3_0_sparsemux_7_2_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "10",
        din0_WIDTH => 8,
        CASE1 => "01",
        din1_WIDTH => 8,
        CASE2 => "00",
        din2_WIDTH => 8,
        def_WIDTH => 8,
        sel_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => tmp_1_fu_455_p2,
        din1 => pix_444_fu_323_p1,
        din2 => tmp_1_fu_455_p6,
        def => tmp_1_fu_455_p7,
        sel => sel_tmp2_fu_403_p3,
        dout => tmp_1_fu_455_p9);

    sparsemux_7_2_8_1_1_U139 : component bd_quad_vmix_dp_v_tpg_3_0_sparsemux_7_2_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "10",
        din0_WIDTH => 8,
        CASE1 => "01",
        din1_WIDTH => 8,
        CASE2 => "00",
        din2_WIDTH => 8,
        def_WIDTH => 8,
        sel_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => tmp_2_fu_475_p2,
        din1 => tmp_2_fu_475_p4,
        din2 => tmp_2_fu_475_p6,
        def => tmp_2_fu_475_p7,
        sel => sel_tmp2_fu_403_p3,
        dout => tmp_2_fu_475_p9);

    sparsemux_7_2_8_1_1_U140 : component bd_quad_vmix_dp_v_tpg_3_0_sparsemux_7_2_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "10",
        din0_WIDTH => 8,
        CASE1 => "01",
        din1_WIDTH => 8,
        CASE2 => "00",
        din2_WIDTH => 8,
        def_WIDTH => 8,
        sel_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => tmp_3_fu_495_p2,
        din1 => tmp_3_fu_495_p4,
        din2 => tmp_3_fu_495_p6,
        def => tmp_3_fu_495_p7,
        sel => sel_tmp2_fu_403_p3,
        dout => tmp_3_fu_495_p9);

    sparsemux_7_2_8_1_1_U141 : component bd_quad_vmix_dp_v_tpg_3_0_sparsemux_7_2_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "10",
        din0_WIDTH => 8,
        CASE1 => "01",
        din1_WIDTH => 8,
        CASE2 => "00",
        din2_WIDTH => 8,
        def_WIDTH => 8,
        sel_WIDTH => 2,
        dout_WIDTH => 8)
    port map (
        din0 => tmp_4_fu_515_p2,
        din1 => tmp_4_fu_515_p4,
        din2 => tmp_4_fu_515_p6,
        def => tmp_4_fu_515_p7,
        sel => sel_tmp2_fu_403_p3,
        dout => tmp_4_fu_515_p9);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2))) then 
                    ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state2);
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    counter_loc_1_i_fu_150_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                counter_loc_1_i_fu_150 <= counter_loc_0_i;
            elsif (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln981_fu_271_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_phi_mux_sof_2_phi_fu_237_p4 = ap_const_lv1_1))) then 
                counter_loc_1_i_fu_150 <= add_ln1005_fu_294_p2;
            end if; 
        end if;
    end process;

    j_fu_146_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                j_fu_146 <= ap_const_lv10_0;
            elsif (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln981_fu_271_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                j_fu_146 <= j_2_fu_276_p2;
            end if; 
        end if;
    end process;

    phi_ln1036_reg_245_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln981_reg_603 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                phi_ln1036_reg_245 <= trunc_ln1008_fu_319_p1;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                phi_ln1036_reg_245 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    sof_2_reg_233_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln981_reg_603 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                sof_2_reg_233 <= ap_const_lv1_0;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                sof_2_reg_233 <= sof;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                axi_last_reg_607 <= axi_last_fu_286_p2;
                icmp_ln981_reg_603 <= icmp_ln981_fu_271_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln981_fu_271_p2, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln981_fu_271_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) and not(((ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln981_fu_271_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) or ((ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    add_ln1005_fu_294_p2 <= std_logic_vector(unsigned(counter_loc_1_i_fu_150) + unsigned(ap_const_lv16_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state4 <= ap_CS_fsm(2);
    ap_CS_fsm_state5 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state3_pp0_stage0_iter1_grp1)
    begin
                ap_block_pp0_stage0_01001_grp1 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter1_grp1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state3_pp0_stage0_iter1_grp1)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter1_grp1));
    end process;


    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state3_pp0_stage0_iter1_grp1)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter1_grp1));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_state3_pp0_stage0_iter1_grp1)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter1_grp1));
    end process;


    ap_block_state3_pp0_stage0_iter1_grp1_assign_proc : process(ovrlayYUV_empty_n, m_axis_video_TREADY, icmp_ln981_reg_603)
    begin
                ap_block_state3_pp0_stage0_iter1_grp1 <= (((icmp_ln981_reg_603 = ap_const_lv1_0) and (m_axis_video_TREADY = ap_const_logic_0)) or ((icmp_ln981_reg_603 = ap_const_lv1_0) and (ovrlayYUV_empty_n = ap_const_logic_0)));
    end process;


    ap_condition_pp0_exit_iter0_state2_assign_proc : process(icmp_ln981_fu_271_p2)
    begin
        if ((icmp_ln981_fu_271_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_sof_2_phi_fu_237_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln981_reg_603, sof_2_reg_233, ap_block_pp0_stage0)
    begin
        if (((icmp_ln981_reg_603 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_phi_mux_sof_2_phi_fu_237_p4 <= ap_const_lv1_0;
        else 
            ap_phi_mux_sof_2_phi_fu_237_p4 <= sof_2_reg_233;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    axi_data_2_fu_411_p4 <= (ap_const_lv1_1 & pix_rgb_4_fu_327_p4);
    axi_data_2_fu_411_p7 <= "XXXXXXXXX";
    axi_data_fu_377_p3 <= (ap_const_lv1_1 & pix_444_fu_323_p1);
    axi_last_fu_286_p2 <= "1" when (zext_ln981_fu_282_p1 = sub_i) else "0";
    counter <= std_logic_vector(unsigned(counter_loc_1_i_fu_150) + unsigned(ap_const_lv16_1));

    counter_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln981_fu_271_p2, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter0, ap_phi_mux_sof_2_phi_fu_237_p4)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln981_fu_271_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_phi_mux_sof_2_phi_fu_237_p4 = ap_const_lv1_1))) then 
            counter_ap_vld <= ap_const_logic_1;
        else 
            counter_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    counter_loc_1_i_out <= counter_loc_1_i_fu_150;

    counter_loc_1_i_out_ap_vld_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            counter_loc_1_i_out_ap_vld <= ap_const_logic_1;
        else 
            counter_loc_1_i_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln1020_1_fu_398_p2 <= "1" when (colorFormat_val17_load = ap_const_lv8_0) else "0";
    icmp_ln1020_fu_393_p2 <= "1" when (colorFormat_val17_load = ap_const_lv8_1) else "0";
    icmp_ln981_fu_271_p2 <= "1" when (j_fu_146 = div_i) else "0";
    j_2_fu_276_p2 <= std_logic_vector(unsigned(j_fu_146) + unsigned(ap_const_lv10_1));
    m_axis_video_TDATA <= (tmp_5_fu_535_p6 & sext_ln925_fu_431_p1(7 downto 0));

    m_axis_video_TDATA_blk_n_assign_proc : process(m_axis_video_TREADY, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_grp1, icmp_ln981_reg_603)
    begin
        if (((icmp_ln981_reg_603 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m_axis_video_TDATA_blk_n <= m_axis_video_TREADY;
        else 
            m_axis_video_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    m_axis_video_TDEST <= "X";
    m_axis_video_TID <= "X";
    m_axis_video_TKEEP <= ap_const_lv6_3F;
    m_axis_video_TLAST <= axi_last_reg_607;
    m_axis_video_TSTRB <= "XXXXXX";
    m_axis_video_TUSER <= sof_2_reg_233;

    m_axis_video_TVALID_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln981_reg_603, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((icmp_ln981_reg_603 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            m_axis_video_TVALID <= ap_const_logic_1;
        else 
            m_axis_video_TVALID <= ap_const_logic_0;
        end if; 
    end process;


    ovrlayYUV_blk_n_assign_proc : process(ovrlayYUV_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_grp1, icmp_ln981_reg_603)
    begin
        if (((icmp_ln981_reg_603 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ovrlayYUV_blk_n <= ovrlayYUV_empty_n;
        else 
            ovrlayYUV_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    ovrlayYUV_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln981_reg_603, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((icmp_ln981_reg_603 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ovrlayYUV_read <= ap_const_logic_1;
        else 
            ovrlayYUV_read <= ap_const_logic_0;
        end if; 
    end process;

    phi_ln1036_out <= phi_ln1036_reg_245;

    phi_ln1036_out_ap_vld_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            phi_ln1036_out_ap_vld <= ap_const_logic_1;
        else 
            phi_ln1036_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    pix_444_fu_323_p1 <= ovrlayYUV_dout(8 - 1 downto 0);
    pix_rgb_4_fu_327_p4 <= ovrlayYUV_dout(15 downto 8);
    sel_tmp2_fu_403_p3 <= (icmp_ln1020_fu_393_p2 & icmp_ln1020_1_fu_398_p2);
        sext_ln925_fu_431_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(axi_data_2_fu_411_p9),48));

    tmp_1_fu_455_p2 <= ovrlayYUV_dout(23 downto 16);
    tmp_1_fu_455_p6 <= ovrlayYUV_dout(31 downto 24);
    tmp_1_fu_455_p7 <= "XXXXXXXX";
    tmp_2_fu_475_p2 <= ovrlayYUV_dout(31 downto 24);
    tmp_2_fu_475_p4 <= ovrlayYUV_dout(39 downto 32);
    tmp_2_fu_475_p6 <= ovrlayYUV_dout(39 downto 32);
    tmp_2_fu_475_p7 <= "XXXXXXXX";
    tmp_3_fu_495_p2 <= ovrlayYUV_dout(39 downto 32);
    tmp_3_fu_495_p4 <= ovrlayYUV_dout(47 downto 40);
    tmp_3_fu_495_p6 <= ovrlayYUV_dout(47 downto 40);
    tmp_3_fu_495_p7 <= "XXXXXXXX";
    tmp_4_fu_515_p2 <= ovrlayYUV_dout(47 downto 40);
    tmp_4_fu_515_p4 <= ovrlayYUV_dout(31 downto 24);
    tmp_4_fu_515_p6 <= ovrlayYUV_dout(23 downto 16);
    tmp_4_fu_515_p7 <= "XXXXXXXX";
    tmp_5_fu_535_p6 <= ((((tmp_4_fu_515_p9 & tmp_3_fu_495_p9) & tmp_2_fu_475_p9) & tmp_1_fu_455_p9) & tmp_fu_435_p9);
    tmp_fu_435_p2 <= ovrlayYUV_dout(15 downto 8);
    tmp_fu_435_p4 <= ovrlayYUV_dout(23 downto 16);
    tmp_fu_435_p6 <= ovrlayYUV_dout(15 downto 8);
    tmp_fu_435_p7 <= "XXXXXXXX";
    trunc_ln1008_fu_319_p1 <= counter_loc_1_i_fu_150(1 - 1 downto 0);
    zext_ln981_fu_282_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_fu_146),11));
end behav;
