domain_path: /home/izaan/GitRepos/dpdma_exdes/vitis_tpg_vfmw/platform/export/platform/sw/standalone_psu_cortexa53_0
app_src_dir: /mnt/ssd2/Xilinx/Vitis/2024.2/data/embeddedsw/lib/sw_apps/empty_application
template: empty_application
