// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module bd_quad_vmix_dp_v_tpg_2_0_tpgForeground_Pipeline_VITIS_LOOP_774_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        bckgndYUV_dout,
        bckgndYUV_empty_n,
        bckgndYUV_read,
        bckgndYUV_num_data_valid,
        bckgndYUV_fifo_cap,
        ovrlayYUV_din,
        ovrlayYUV_full_n,
        ovrlayYUV_write,
        ovrlayYUV_num_data_valid,
        ovrlayYUV_fifo_cap,
        width_val_cast,
        conv2_i_i_i,
        patternId_val_load,
        boxSize,
        y,
        boxColorB,
        boxColorG,
        boxColorR,
        pixOut_18,
        vMax,
        motionSpeed,
        hMax,
        zext_ln1974,
        crossHairX_val_cast,
        cmp2_i,
        crossHairX,
        whiYuv_load,
        color,
        maskId,
        cmp11_i,
        empty_36,
        empty_37,
        empty,
        boxHCoord_loc_1_out_i,
        boxHCoord_loc_1_out_o,
        boxHCoord_loc_1_out_o_ap_vld,
        boxVCoord_loc_1_out_i,
        boxVCoord_loc_1_out_o,
        boxVCoord_loc_1_out_o_ap_vld,
        boxVCoord,
        boxVCoord_ap_vld,
        boxHCoord,
        boxHCoord_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [47:0] bckgndYUV_dout;
input   bckgndYUV_empty_n;
output   bckgndYUV_read;
input  [4:0] bckgndYUV_num_data_valid;
input  [4:0] bckgndYUV_fifo_cap;
output  [47:0] ovrlayYUV_din;
input   ovrlayYUV_full_n;
output   ovrlayYUV_write;
input  [31:0] ovrlayYUV_num_data_valid;
input  [31:0] ovrlayYUV_fifo_cap;
input  [15:0] width_val_cast;
input  [7:0] conv2_i_i_i;
input  [7:0] patternId_val_load;
input  [15:0] boxSize;
input  [15:0] y;
input  [7:0] boxColorB;
input  [7:0] boxColorG;
input  [7:0] boxColorR;
input  [7:0] pixOut_18;
input  [15:0] vMax;
input  [7:0] motionSpeed;
input  [15:0] hMax;
input  [8:0] zext_ln1974;
input  [15:0] crossHairX_val_cast;
input  [0:0] cmp2_i;
input  [15:0] crossHairX;
input  [7:0] whiYuv_load;
input  [7:0] color;
input  [7:0] maskId;
input  [0:0] cmp11_i;
input  [0:0] empty_36;
input  [0:0] empty_37;
input  [0:0] empty;
input  [15:0] boxHCoord_loc_1_out_i;
output  [15:0] boxHCoord_loc_1_out_o;
output   boxHCoord_loc_1_out_o_ap_vld;
input  [15:0] boxVCoord_loc_1_out_i;
output  [15:0] boxVCoord_loc_1_out_o;
output   boxVCoord_loc_1_out_o_ap_vld;
output  [15:0] boxVCoord;
output   boxVCoord_ap_vld;
output  [15:0] boxHCoord;
output   boxHCoord_ap_vld;

reg ap_idle;
reg bckgndYUV_read;
reg ovrlayYUV_write;
reg[15:0] boxHCoord_loc_1_out_o;
reg boxHCoord_loc_1_out_o_ap_vld;
reg[15:0] boxVCoord_loc_1_out_o;
reg boxVCoord_loc_1_out_o_ap_vld;
reg boxVCoord_ap_vld;
reg boxHCoord_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln774_reg_1065;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln774_fu_445_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [0:0] vDir;
reg   [0:0] hDir;
reg    ovrlayYUV_blk_n;
wire    ap_block_pp0_stage0;
reg    bckgndYUV_blk_n;
reg    ap_block_pp0_stage0_11001;
wire   [7:0] patternId_val_load_read_read_fu_270_p2;
wire   [7:0] patternId_val_load_read_reg_1021;
wire   [0:0] cmp11_i7_fu_406_p2;
reg   [0:0] cmp11_i7_reg_1032;
wire   [0:0] tobool_fu_412_p2;
reg   [0:0] tobool_reg_1037;
wire   [0:0] and26_i_fu_418_p2;
reg   [0:0] and26_i_reg_1047;
wire   [0:0] and10_i_fu_424_p2;
reg   [0:0] and10_i_reg_1053;
wire   [0:0] and4_i_fu_430_p2;
reg   [0:0] and4_i_reg_1059;
wire   [15:0] x_2_fu_451_p1;
reg   [15:0] x_2_reg_1069;
wire   [0:0] icmp_ln1884_fu_461_p2;
reg   [0:0] icmp_ln1884_reg_1075;
wire   [14:0] grp_fu_381_p4;
reg   [14:0] tmp_1_reg_1097;
wire   [0:0] or_ln1963_fu_591_p2;
reg   [0:0] or_ln1963_reg_1102;
wire   [0:0] or_ln1963_2_fu_611_p2;
reg   [0:0] or_ln1963_2_reg_1109;
wire   [7:0] pixIn_fu_628_p1;
wire   [7:0] pixIn_11_fu_632_p4;
wire   [7:0] pixIn_12_fu_642_p4;
wire   [7:0] pixIn_13_fu_652_p4;
wire   [7:0] pixIn_14_fu_662_p4;
wire   [7:0] pixIn_15_fu_672_p4;
wire   [7:0] pixOut_16_fu_770_p3;
wire   [7:0] pixOut_15_fu_777_p3;
wire   [7:0] pixOut_14_fu_784_p3;
wire   [7:0] pixOut_20_fu_828_p3;
wire   [7:0] pixOut_19_fu_835_p3;
wire   [7:0] pixOut_17_fu_842_p3;
wire   [7:0] pixOut_8_fu_849_p3;
wire   [7:0] pixOut_7_fu_855_p3;
wire   [7:0] pixOut_6_fu_861_p3;
wire   [7:0] select_ln1974_fu_868_p3;
wire   [7:0] ap_phi_reg_pp0_iter0_pix_10_reg_301;
reg   [7:0] ap_phi_reg_pp0_iter1_pix_10_reg_301;
reg   [7:0] ap_phi_reg_pp0_iter2_pix_10_reg_301;
wire   [7:0] ap_phi_reg_pp0_iter0_pix_9_reg_314;
reg   [7:0] ap_phi_reg_pp0_iter1_pix_9_reg_314;
reg   [7:0] ap_phi_reg_pp0_iter2_pix_9_reg_314;
wire   [7:0] ap_phi_reg_pp0_iter0_pix_8_reg_327;
reg   [7:0] ap_phi_reg_pp0_iter1_pix_8_reg_327;
reg   [7:0] ap_phi_reg_pp0_iter2_pix_8_reg_327;
wire   [7:0] ap_phi_reg_pp0_iter0_pix_7_reg_342;
reg   [7:0] ap_phi_reg_pp0_iter1_pix_7_reg_342;
reg   [7:0] ap_phi_reg_pp0_iter2_pix_7_reg_342;
wire   [7:0] ap_phi_reg_pp0_iter0_pix_6_reg_355;
reg   [7:0] ap_phi_reg_pp0_iter1_pix_6_reg_355;
reg   [7:0] ap_phi_reg_pp0_iter2_pix_6_reg_355;
wire   [7:0] ap_phi_reg_pp0_iter0_pix_reg_368;
reg   [7:0] ap_phi_reg_pp0_iter1_pix_reg_368;
reg   [7:0] ap_phi_reg_pp0_iter2_pix_reg_368;
wire   [15:0] sub_ln1914_fu_479_p2;
wire   [15:0] add_ln1912_fu_485_p2;
wire   [0:0] hDir_load_load_fu_471_p1;
wire   [0:0] icmp_ln1889_fu_491_p2;
wire   [0:0] icmp_ln1894_fu_509_p2;
wire    ap_block_pp0_stage0_grp0;
wire   [15:0] sub_ln1918_fu_537_p2;
wire   [15:0] add_ln1916_fu_543_p2;
wire   [0:0] vDir_load_load_fu_475_p1;
wire   [0:0] icmp_ln1906_fu_561_p2;
wire   [0:0] icmp_ln1901_fu_549_p2;
wire    ap_block_pp0_stage0_11001_grp0;
reg    ap_block_pp0_stage0_subdone_grp0_done_reg;
wire    ap_block_pp0_stage0_subdone_grp0;
reg   [16:0] x_fu_146;
wire   [16:0] add_ln774_fu_617_p2;
wire    ap_loop_init;
reg   [16:0] ap_sig_allocacmp_x_1;
reg    ap_block_pp0_stage0_01001;
wire   [16:0] width_val_cast_cast_fu_402_p1;
wire   [15:0] or_ln1884_fu_455_p2;
wire   [15:0] motionSpeed_cast_fu_398_p1;
wire   [15:0] zext_ln1974_cast_fu_394_p1;
wire   [16:0] crossHairX_val_cast_cast_fu_390_p1;
wire   [0:0] icmp_ln1963_fu_585_p2;
wire   [15:0] or_ln1963_1_fu_597_p3;
wire   [0:0] icmp_ln1963_1_fu_605_p2;
wire   [15:0] boxBottom_fu_715_p2;
wire   [0:0] icmp_ln1942_fu_720_p2;
wire   [0:0] icmp_ln1942_1_fu_731_p2;
wire   [0:0] xor_ln1942_fu_725_p2;
wire   [15:0] boxRight_fu_710_p2;
wire   [0:0] icmp_ln1942_3_fu_747_p2;
wire   [0:0] icmp_ln1942_2_fu_742_p2;
wire   [0:0] or_ln1942_fu_736_p2;
wire   [0:0] or_ln1942_1_fu_758_p2;
wire   [0:0] xor_ln1942_1_fu_752_p2;
wire   [0:0] or_ln1942_2_fu_764_p2;
wire   [15:0] or_ln_fu_791_p3;
wire   [0:0] icmp_ln1942_5_fu_804_p2;
wire   [0:0] icmp_ln1942_4_fu_798_p2;
wire   [0:0] or_ln1942_3_fu_816_p2;
wire   [0:0] xor_ln1942_2_fu_810_p2;
wire   [0:0] or_ln1942_4_fu_822_p2;
wire   [7:0] select_ln1993_fu_881_p3;
wire   [7:0] pixOut_27_fu_874_p3;
wire   [7:0] select_ln1991_fu_902_p3;
wire   [7:0] select_ln1989_fu_916_p3;
wire   [7:0] select_ln1991_1_fu_930_p3;
wire   [7:0] select_ln1993_1_fu_944_p3;
wire   [7:0] p_0_5_0_0_0155_fu_888_p3;
wire   [7:0] empty_82_fu_909_p3;
wire   [7:0] empty_83_fu_923_p3;
wire   [7:0] empty_85_fu_951_p3;
wire   [7:0] empty_84_fu_937_p3;
wire   [7:0] pixOut_28_fu_895_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_332;
reg    ap_condition_339;
reg    ap_condition_272;
reg    ap_condition_757;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 vDir = 1'd0;
#0 hDir = 1'd0;
#0 ap_block_pp0_stage0_subdone_grp0_done_reg = 1'b0;
#0 x_fu_146 = 17'd0;
#0 ap_done_reg = 1'b0;
end

bd_quad_vmix_dp_v_tpg_2_0_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone_grp0)) begin
            ap_block_pp0_stage0_subdone_grp0_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln774_reg_1065 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (patternId_val_load_read_reg_1021 == 8'd1))) begin
        ap_phi_reg_pp0_iter2_pix_10_reg_301 <= pixOut_20_fu_828_p3;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln774_reg_1065 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln1963_2_reg_1109 == 1'd1) & (patternId_val_load_read_reg_1021 == 8'd2))) begin
        ap_phi_reg_pp0_iter2_pix_10_reg_301 <= conv2_i_i_i;
    end else if (((~(patternId_val_load_read_reg_1021 == 8'd1) & ~(patternId_val_load_read_reg_1021 == 8'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln774_reg_1065 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln774_reg_1065 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln1963_2_reg_1109 == 1'd0) & (patternId_val_load_read_reg_1021 == 8'd2)))) begin
        ap_phi_reg_pp0_iter2_pix_10_reg_301 <= {{bckgndYUV_dout[47:40]}};
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter2_pix_10_reg_301 <= ap_phi_reg_pp0_iter1_pix_10_reg_301;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln774_reg_1065 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (patternId_val_load_read_reg_1021 == 8'd1))) begin
        ap_phi_reg_pp0_iter2_pix_6_reg_355 <= pixOut_15_fu_777_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln774_reg_1065 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln1963_2_reg_1109 == 1'd1) & (patternId_val_load_read_reg_1021 == 8'd2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln774_reg_1065 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln1963_2_reg_1109 == 1'd0) & (patternId_val_load_read_reg_1021 == 8'd2)))) begin
        ap_phi_reg_pp0_iter2_pix_6_reg_355 <= pixOut_7_fu_855_p3;
    end else if ((~(patternId_val_load_read_reg_1021 == 8'd1) & ~(patternId_val_load_read_reg_1021 == 8'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln774_reg_1065 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter2_pix_6_reg_355 <= {{bckgndYUV_dout[15:8]}};
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter2_pix_6_reg_355 <= ap_phi_reg_pp0_iter1_pix_6_reg_355;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln774_reg_1065 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (patternId_val_load_read_reg_1021 == 8'd1))) begin
        ap_phi_reg_pp0_iter2_pix_7_reg_342 <= pixOut_16_fu_770_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln774_reg_1065 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln1963_2_reg_1109 == 1'd1) & (patternId_val_load_read_reg_1021 == 8'd2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln774_reg_1065 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln1963_2_reg_1109 == 1'd0) & (patternId_val_load_read_reg_1021 == 8'd2)))) begin
        ap_phi_reg_pp0_iter2_pix_7_reg_342 <= pixOut_8_fu_849_p3;
    end else if ((~(patternId_val_load_read_reg_1021 == 8'd1) & ~(patternId_val_load_read_reg_1021 == 8'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln774_reg_1065 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter2_pix_7_reg_342 <= {{bckgndYUV_dout[23:16]}};
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter2_pix_7_reg_342 <= ap_phi_reg_pp0_iter1_pix_7_reg_342;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln774_reg_1065 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (patternId_val_load_read_reg_1021 == 8'd1))) begin
        ap_phi_reg_pp0_iter2_pix_8_reg_327 <= pixOut_17_fu_842_p3;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln774_reg_1065 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln1963_2_reg_1109 == 1'd1) & (patternId_val_load_read_reg_1021 == 8'd2))) begin
        ap_phi_reg_pp0_iter2_pix_8_reg_327 <= 8'd240;
    end else if (((~(patternId_val_load_read_reg_1021 == 8'd1) & ~(patternId_val_load_read_reg_1021 == 8'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln774_reg_1065 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln774_reg_1065 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln1963_2_reg_1109 == 1'd0) & (patternId_val_load_read_reg_1021 == 8'd2)))) begin
        ap_phi_reg_pp0_iter2_pix_8_reg_327 <= {{bckgndYUV_dout[31:24]}};
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter2_pix_8_reg_327 <= ap_phi_reg_pp0_iter1_pix_8_reg_327;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln774_reg_1065 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (patternId_val_load_read_reg_1021 == 8'd1))) begin
        ap_phi_reg_pp0_iter2_pix_9_reg_314 <= pixOut_19_fu_835_p3;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln774_reg_1065 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln1963_2_reg_1109 == 1'd1) & (patternId_val_load_read_reg_1021 == 8'd2))) begin
        ap_phi_reg_pp0_iter2_pix_9_reg_314 <= select_ln1974_fu_868_p3;
    end else if (((~(patternId_val_load_read_reg_1021 == 8'd1) & ~(patternId_val_load_read_reg_1021 == 8'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln774_reg_1065 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln774_reg_1065 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln1963_2_reg_1109 == 1'd0) & (patternId_val_load_read_reg_1021 == 8'd2)))) begin
        ap_phi_reg_pp0_iter2_pix_9_reg_314 <= {{bckgndYUV_dout[39:32]}};
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter2_pix_9_reg_314 <= ap_phi_reg_pp0_iter1_pix_9_reg_314;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln774_reg_1065 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (patternId_val_load_read_reg_1021 == 8'd1))) begin
        ap_phi_reg_pp0_iter2_pix_reg_368 <= pixOut_14_fu_784_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln774_reg_1065 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln1963_2_reg_1109 == 1'd1) & (patternId_val_load_read_reg_1021 == 8'd2)) | ((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln774_reg_1065 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (or_ln1963_2_reg_1109 == 1'd0) & (patternId_val_load_read_reg_1021 == 8'd2)))) begin
        ap_phi_reg_pp0_iter2_pix_reg_368 <= pixOut_6_fu_861_p3;
    end else if ((~(patternId_val_load_read_reg_1021 == 8'd1) & ~(patternId_val_load_read_reg_1021 == 8'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln774_reg_1065 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter2_pix_reg_368 <= pixIn_fu_628_p1;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter2_pix_reg_368 <= ap_phi_reg_pp0_iter1_pix_reg_368;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_757)) begin
        if (((icmp_ln1894_fu_509_p2 == 1'd1) & (hDir_load_load_fu_471_p1 == 1'd1))) begin
            hDir <= 1'd0;
        end else if (((icmp_ln1889_fu_491_p2 == 1'd1) & (hDir_load_load_fu_471_p1 == 1'd0))) begin
            hDir <= 1'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_757)) begin
        if (((icmp_ln1906_fu_561_p2 == 1'd1) & (vDir_load_load_fu_475_p1 == 1'd1))) begin
            vDir <= 1'd0;
        end else if (((icmp_ln1901_fu_549_p2 == 1'd1) & (vDir_load_load_fu_475_p1 == 1'd0))) begin
            vDir <= 1'd1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln774_fu_445_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            x_fu_146 <= add_ln774_fu_617_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            x_fu_146 <= 17'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and10_i_reg_1053 <= and10_i_fu_424_p2;
        and26_i_reg_1047 <= and26_i_fu_418_p2;
        and4_i_reg_1059 <= and4_i_fu_430_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        cmp11_i7_reg_1032 <= cmp11_i7_fu_406_p2;
        icmp_ln1884_reg_1075 <= icmp_ln1884_fu_461_p2;
        icmp_ln774_reg_1065 <= icmp_ln774_fu_445_p2;
        or_ln1963_2_reg_1109 <= or_ln1963_2_fu_611_p2;
        or_ln1963_reg_1102 <= or_ln1963_fu_591_p2;
        tobool_reg_1037 <= tobool_fu_412_p2;
        x_2_reg_1069 <= x_2_fu_451_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_pix_10_reg_301 <= ap_phi_reg_pp0_iter0_pix_10_reg_301;
        ap_phi_reg_pp0_iter1_pix_6_reg_355 <= ap_phi_reg_pp0_iter0_pix_6_reg_355;
        ap_phi_reg_pp0_iter1_pix_7_reg_342 <= ap_phi_reg_pp0_iter0_pix_7_reg_342;
        ap_phi_reg_pp0_iter1_pix_8_reg_327 <= ap_phi_reg_pp0_iter0_pix_8_reg_327;
        ap_phi_reg_pp0_iter1_pix_9_reg_314 <= ap_phi_reg_pp0_iter0_pix_9_reg_314;
        ap_phi_reg_pp0_iter1_pix_reg_368 <= ap_phi_reg_pp0_iter0_pix_reg_368;
        tmp_1_reg_1097 <= {{ap_sig_allocacmp_x_1[15:1]}};
    end
end

always @ (*) begin
    if (((icmp_ln774_fu_445_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_x_1 = 17'd0;
    end else begin
        ap_sig_allocacmp_x_1 = x_fu_146;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln774_reg_1065 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bckgndYUV_blk_n = bckgndYUV_empty_n;
    end else begin
        bckgndYUV_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln774_reg_1065 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bckgndYUV_read = 1'b1;
    end else begin
        bckgndYUV_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (icmp_ln774_reg_1065 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1884_reg_1075 == 1'd1) & (patternId_val_load_read_reg_1021 == 8'd1))) begin
        boxHCoord_ap_vld = 1'b1;
    end else begin
        boxHCoord_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((icmp_ln774_fu_445_p2 == 1'd1) & (icmp_ln1889_fu_491_p2 == 1'd0) & (hDir_load_load_fu_471_p1 == 1'd0) & (icmp_ln1884_fu_461_p2 == 1'd1) & (patternId_val_load_read_read_fu_270_p2 == 8'd1)) | ((icmp_ln774_fu_445_p2 == 1'd1) & (icmp_ln1894_fu_509_p2 == 1'd1) & (hDir_load_load_fu_471_p1 == 1'd1) & (icmp_ln1884_fu_461_p2 == 1'd1) & (patternId_val_load_read_read_fu_270_p2 == 8'd1))))) begin
        boxHCoord_loc_1_out_o = add_ln1912_fu_485_p2;
    end else if ((((icmp_ln774_fu_445_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (icmp_ln1894_fu_509_p2 == 1'd0) & (hDir_load_load_fu_471_p1 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1884_fu_461_p2 == 1'd1) & (patternId_val_load_read_read_fu_270_p2 == 8'd1)) | ((icmp_ln774_fu_445_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (icmp_ln1889_fu_491_p2 == 1'd1) & (hDir_load_load_fu_471_p1 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1884_fu_461_p2 == 1'd1) & (patternId_val_load_read_read_fu_270_p2 == 8'd1)))) begin
        boxHCoord_loc_1_out_o = sub_ln1914_fu_479_p2;
    end else begin
        boxHCoord_loc_1_out_o = boxHCoord_loc_1_out_i;
    end
end

always @ (*) begin
    if ((((icmp_ln774_fu_445_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1894_fu_509_p2 == 1'd0) & (hDir_load_load_fu_471_p1 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1884_fu_461_p2 == 1'd1) & (patternId_val_load_read_read_fu_270_p2 == 8'd1)) | ((icmp_ln774_fu_445_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1889_fu_491_p2 == 1'd1) & (hDir_load_load_fu_471_p1 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1884_fu_461_p2 == 1'd1) & (patternId_val_load_read_read_fu_270_p2 == 8'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((icmp_ln774_fu_445_p2 == 1'd1) & (icmp_ln1889_fu_491_p2 == 1'd0) & (hDir_load_load_fu_471_p1 == 1'd0) & (icmp_ln1884_fu_461_p2 == 1'd1) & (patternId_val_load_read_read_fu_270_p2 == 8'd1)) | ((icmp_ln774_fu_445_p2 == 1'd1) & (icmp_ln1894_fu_509_p2 == 1'd1) & (hDir_load_load_fu_471_p1 == 1'd1) & (icmp_ln1884_fu_461_p2 
    == 1'd1) & (patternId_val_load_read_read_fu_270_p2 == 8'd1)))))) begin
        boxHCoord_loc_1_out_o_ap_vld = 1'b1;
    end else begin
        boxHCoord_loc_1_out_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone_grp0_done_reg) & (1'b0 == ap_block_pp0_stage0_11001_grp0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1884_reg_1075 == 1'd1) & (patternId_val_load_read_reg_1021 == 8'd1))) begin
        boxVCoord_ap_vld = 1'b1;
    end else begin
        boxVCoord_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_272)) begin
        if ((1'b1 == ap_condition_339)) begin
            boxVCoord_loc_1_out_o = add_ln1916_fu_543_p2;
        end else if ((1'b1 == ap_condition_332)) begin
            boxVCoord_loc_1_out_o = sub_ln1918_fu_537_p2;
        end else begin
            boxVCoord_loc_1_out_o = boxVCoord_loc_1_out_i;
        end
    end else begin
        boxVCoord_loc_1_out_o = boxVCoord_loc_1_out_i;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((icmp_ln774_fu_445_p2 == 1'd1) & (icmp_ln1901_fu_549_p2 == 1'd0) & (vDir_load_load_fu_475_p1 == 1'd0) & (icmp_ln1884_fu_461_p2 == 1'd1) & (patternId_val_load_read_read_fu_270_p2 == 8'd1)) | ((icmp_ln774_fu_445_p2 == 1'd1) & (icmp_ln1906_fu_561_p2 == 1'd1) & (vDir_load_load_fu_475_p1 == 1'd1) & (icmp_ln1884_fu_461_p2 == 1'd1) & (patternId_val_load_read_read_fu_270_p2 == 8'd1)))) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (((icmp_ln774_fu_445_p2 == 1'd1) & (icmp_ln1901_fu_549_p2 == 1'd1) & (vDir_load_load_fu_475_p1 == 1'd0) & (icmp_ln1884_fu_461_p2 == 1'd1) & (patternId_val_load_read_read_fu_270_p2 == 8'd1)) | ((icmp_ln774_fu_445_p2 == 1'd1) & (icmp_ln1906_fu_561_p2 == 1'd0) & (vDir_load_load_fu_475_p1 == 1'd1) & (icmp_ln1884_fu_461_p2 == 1'd1) & (patternId_val_load_read_read_fu_270_p2 == 8'd1)))))) begin
        boxVCoord_loc_1_out_o_ap_vld = 1'b1;
    end else begin
        boxVCoord_loc_1_out_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ovrlayYUV_blk_n = ovrlayYUV_full_n;
    end else begin
        ovrlayYUV_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ovrlayYUV_write = 1'b1;
    end else begin
        ovrlayYUV_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1912_fu_485_p2 = (boxHCoord_loc_1_out_i + motionSpeed_cast_fu_398_p1);

assign add_ln1916_fu_543_p2 = (boxVCoord_loc_1_out_i + motionSpeed_cast_fu_398_p1);

assign add_ln774_fu_617_p2 = (ap_sig_allocacmp_x_1 + 17'd2);

assign and10_i_fu_424_p2 = (empty_37 & cmp11_i);

assign and26_i_fu_418_p2 = (empty_36 & cmp11_i);

assign and4_i_fu_430_p2 = (empty & cmp11_i);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

assign ap_block_pp0_stage0_11001_grp0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

assign ap_block_pp0_stage0_subdone_grp0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((icmp_ln774_reg_1065 == 1'd1) & (bckgndYUV_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = (ovrlayYUV_full_n == 1'b0);
end

always @ (*) begin
    ap_condition_272 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_332 = (((icmp_ln774_fu_445_p2 == 1'd1) & (icmp_ln1901_fu_549_p2 == 1'd1) & (vDir_load_load_fu_475_p1 == 1'd0) & (icmp_ln1884_fu_461_p2 == 1'd1) & (patternId_val_load_read_read_fu_270_p2 == 8'd1)) | ((icmp_ln774_fu_445_p2 == 1'd1) & (icmp_ln1906_fu_561_p2 == 1'd0) & (vDir_load_load_fu_475_p1 == 1'd1) & (icmp_ln1884_fu_461_p2 == 1'd1) & (patternId_val_load_read_read_fu_270_p2 == 8'd1)));
end

always @ (*) begin
    ap_condition_339 = (((icmp_ln774_fu_445_p2 == 1'd1) & (icmp_ln1901_fu_549_p2 == 1'd0) & (vDir_load_load_fu_475_p1 == 1'd0) & (icmp_ln1884_fu_461_p2 == 1'd1) & (patternId_val_load_read_read_fu_270_p2 == 8'd1)) | ((icmp_ln774_fu_445_p2 == 1'd1) & (icmp_ln1906_fu_561_p2 == 1'd1) & (vDir_load_load_fu_475_p1 == 1'd1) & (icmp_ln1884_fu_461_p2 == 1'd1) & (patternId_val_load_read_read_fu_270_p2 == 8'd1)));
end

always @ (*) begin
    ap_condition_757 = ((icmp_ln774_fu_445_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln1884_fu_461_p2 == 1'd1) & (patternId_val_load_read_read_fu_270_p2 == 8'd1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_pix_10_reg_301 = 'bx;

assign ap_phi_reg_pp0_iter0_pix_6_reg_355 = 'bx;

assign ap_phi_reg_pp0_iter0_pix_7_reg_342 = 'bx;

assign ap_phi_reg_pp0_iter0_pix_8_reg_327 = 'bx;

assign ap_phi_reg_pp0_iter0_pix_9_reg_314 = 'bx;

assign ap_phi_reg_pp0_iter0_pix_reg_368 = 'bx;

assign ap_ready = ap_ready_sig;

assign boxBottom_fu_715_p2 = (boxSize + boxVCoord_loc_1_out_i);

assign boxHCoord = boxHCoord_loc_1_out_i;

assign boxRight_fu_710_p2 = (boxSize + boxHCoord_loc_1_out_i);

assign boxVCoord = boxVCoord_loc_1_out_i;

assign cmp11_i7_fu_406_p2 = ((color == 8'd0) ? 1'b1 : 1'b0);

assign crossHairX_val_cast_cast_fu_390_p1 = crossHairX_val_cast;

assign empty_82_fu_909_p3 = ((tobool_reg_1037[0:0] == 1'b1) ? ap_phi_reg_pp0_iter2_pix_9_reg_314 : select_ln1991_fu_902_p3);

assign empty_83_fu_923_p3 = ((tobool_reg_1037[0:0] == 1'b1) ? ap_phi_reg_pp0_iter2_pix_8_reg_327 : select_ln1989_fu_916_p3);

assign empty_84_fu_937_p3 = ((tobool_reg_1037[0:0] == 1'b1) ? ap_phi_reg_pp0_iter2_pix_6_reg_355 : select_ln1991_1_fu_930_p3);

assign empty_85_fu_951_p3 = ((tobool_reg_1037[0:0] == 1'b1) ? ap_phi_reg_pp0_iter2_pix_7_reg_342 : select_ln1993_1_fu_944_p3);

assign grp_fu_381_p4 = {{ap_sig_allocacmp_x_1[15:1]}};

assign hDir_load_load_fu_471_p1 = hDir;

assign icmp_ln1884_fu_461_p2 = ((or_ln1884_fu_455_p2 == 16'd0) ? 1'b1 : 1'b0);

assign icmp_ln1889_fu_491_p2 = ((boxHCoord_loc_1_out_i > hMax) ? 1'b1 : 1'b0);

assign icmp_ln1894_fu_509_p2 = ((zext_ln1974_cast_fu_394_p1 > boxHCoord_loc_1_out_i) ? 1'b1 : 1'b0);

assign icmp_ln1901_fu_549_p2 = ((boxVCoord_loc_1_out_i > vMax) ? 1'b1 : 1'b0);

assign icmp_ln1906_fu_561_p2 = ((zext_ln1974_cast_fu_394_p1 > boxVCoord_loc_1_out_i) ? 1'b1 : 1'b0);

assign icmp_ln1942_1_fu_731_p2 = ((y < boxVCoord_loc_1_out_i) ? 1'b1 : 1'b0);

assign icmp_ln1942_2_fu_742_p2 = ((x_2_reg_1069 < boxHCoord_loc_1_out_i) ? 1'b1 : 1'b0);

assign icmp_ln1942_3_fu_747_p2 = ((x_2_reg_1069 < boxRight_fu_710_p2) ? 1'b1 : 1'b0);

assign icmp_ln1942_4_fu_798_p2 = ((or_ln_fu_791_p3 < boxHCoord_loc_1_out_i) ? 1'b1 : 1'b0);

assign icmp_ln1942_5_fu_804_p2 = ((or_ln_fu_791_p3 < boxRight_fu_710_p2) ? 1'b1 : 1'b0);

assign icmp_ln1942_fu_720_p2 = ((y < boxBottom_fu_715_p2) ? 1'b1 : 1'b0);

assign icmp_ln1963_1_fu_605_p2 = ((or_ln1963_1_fu_597_p3 == crossHairX) ? 1'b1 : 1'b0);

assign icmp_ln1963_fu_585_p2 = ((ap_sig_allocacmp_x_1 == crossHairX_val_cast_cast_fu_390_p1) ? 1'b1 : 1'b0);

assign icmp_ln774_fu_445_p2 = ((ap_sig_allocacmp_x_1 < width_val_cast_cast_fu_402_p1) ? 1'b1 : 1'b0);

assign motionSpeed_cast_fu_398_p1 = motionSpeed;

assign or_ln1884_fu_455_p2 = (y | x_2_fu_451_p1);

assign or_ln1942_1_fu_758_p2 = (or_ln1942_fu_736_p2 | icmp_ln1942_2_fu_742_p2);

assign or_ln1942_2_fu_764_p2 = (xor_ln1942_1_fu_752_p2 | or_ln1942_1_fu_758_p2);

assign or_ln1942_3_fu_816_p2 = (or_ln1942_fu_736_p2 | icmp_ln1942_4_fu_798_p2);

assign or_ln1942_4_fu_822_p2 = (xor_ln1942_2_fu_810_p2 | or_ln1942_3_fu_816_p2);

assign or_ln1942_fu_736_p2 = (xor_ln1942_fu_725_p2 | icmp_ln1942_1_fu_731_p2);

assign or_ln1963_1_fu_597_p3 = {{grp_fu_381_p4}, {1'd1}};

assign or_ln1963_2_fu_611_p2 = (icmp_ln1963_1_fu_605_p2 | cmp2_i);

assign or_ln1963_fu_591_p2 = (icmp_ln1963_fu_585_p2 | cmp2_i);

assign or_ln_fu_791_p3 = {{tmp_1_reg_1097}, {1'd1}};

assign ovrlayYUV_din = {{{{{{p_0_5_0_0_0155_fu_888_p3}, {empty_82_fu_909_p3}}, {empty_83_fu_923_p3}}, {empty_85_fu_951_p3}}, {empty_84_fu_937_p3}}, {pixOut_28_fu_895_p3}};

assign p_0_5_0_0_0155_fu_888_p3 = ((tobool_reg_1037[0:0] == 1'b1) ? ap_phi_reg_pp0_iter2_pix_10_reg_301 : select_ln1993_fu_881_p3);

assign patternId_val_load_read_read_fu_270_p2 = patternId_val_load;

assign patternId_val_load_read_reg_1021 = patternId_val_load;

assign pixIn_11_fu_632_p4 = {{bckgndYUV_dout[15:8]}};

assign pixIn_12_fu_642_p4 = {{bckgndYUV_dout[23:16]}};

assign pixIn_13_fu_652_p4 = {{bckgndYUV_dout[31:24]}};

assign pixIn_14_fu_662_p4 = {{bckgndYUV_dout[39:32]}};

assign pixIn_15_fu_672_p4 = {{bckgndYUV_dout[47:40]}};

assign pixIn_fu_628_p1 = bckgndYUV_dout[7:0];

assign pixOut_14_fu_784_p3 = ((or_ln1942_2_fu_764_p2[0:0] == 1'b1) ? pixIn_fu_628_p1 : boxColorR);

assign pixOut_15_fu_777_p3 = ((or_ln1942_2_fu_764_p2[0:0] == 1'b1) ? pixIn_11_fu_632_p4 : boxColorG);

assign pixOut_16_fu_770_p3 = ((or_ln1942_2_fu_764_p2[0:0] == 1'b1) ? pixIn_12_fu_642_p4 : boxColorB);

assign pixOut_17_fu_842_p3 = ((or_ln1942_4_fu_822_p2[0:0] == 1'b1) ? pixIn_13_fu_652_p4 : boxColorR);

assign pixOut_19_fu_835_p3 = ((or_ln1942_4_fu_822_p2[0:0] == 1'b1) ? pixIn_14_fu_662_p4 : pixOut_18);

assign pixOut_20_fu_828_p3 = ((or_ln1942_4_fu_822_p2[0:0] == 1'b1) ? pixIn_15_fu_672_p4 : boxColorB);

assign pixOut_27_fu_874_p3 = ((and4_i_reg_1059[0:0] == 1'b1) ? 8'd0 : ap_phi_reg_pp0_iter2_pix_reg_368);

assign pixOut_28_fu_895_p3 = ((tobool_reg_1037[0:0] == 1'b1) ? ap_phi_reg_pp0_iter2_pix_reg_368 : pixOut_27_fu_874_p3);

assign pixOut_6_fu_861_p3 = ((or_ln1963_reg_1102[0:0] == 1'b1) ? 8'd240 : pixIn_fu_628_p1);

assign pixOut_7_fu_855_p3 = ((or_ln1963_reg_1102[0:0] == 1'b1) ? conv2_i_i_i : pixIn_11_fu_632_p4);

assign pixOut_8_fu_849_p3 = ((or_ln1963_reg_1102[0:0] == 1'b1) ? conv2_i_i_i : pixIn_12_fu_642_p4);

assign select_ln1974_fu_868_p3 = ((cmp11_i7_reg_1032[0:0] == 1'b1) ? 8'd240 : whiYuv_load);

assign select_ln1989_fu_916_p3 = ((and4_i_reg_1059[0:0] == 1'b1) ? 8'd0 : ap_phi_reg_pp0_iter2_pix_8_reg_327);

assign select_ln1991_1_fu_930_p3 = ((and10_i_reg_1053[0:0] == 1'b1) ? 8'd0 : ap_phi_reg_pp0_iter2_pix_6_reg_355);

assign select_ln1991_fu_902_p3 = ((and10_i_reg_1053[0:0] == 1'b1) ? 8'd0 : ap_phi_reg_pp0_iter2_pix_9_reg_314);

assign select_ln1993_1_fu_944_p3 = ((and26_i_reg_1047[0:0] == 1'b1) ? 8'd0 : ap_phi_reg_pp0_iter2_pix_7_reg_342);

assign select_ln1993_fu_881_p3 = ((and26_i_reg_1047[0:0] == 1'b1) ? 8'd0 : ap_phi_reg_pp0_iter2_pix_10_reg_301);

assign sub_ln1914_fu_479_p2 = (boxHCoord_loc_1_out_i - motionSpeed_cast_fu_398_p1);

assign sub_ln1918_fu_537_p2 = (boxVCoord_loc_1_out_i - motionSpeed_cast_fu_398_p1);

assign tobool_fu_412_p2 = ((maskId == 8'd0) ? 1'b1 : 1'b0);

assign vDir_load_load_fu_475_p1 = vDir;

assign width_val_cast_cast_fu_402_p1 = width_val_cast;

assign x_2_fu_451_p1 = ap_sig_allocacmp_x_1[15:0];

assign xor_ln1942_1_fu_752_p2 = (icmp_ln1942_3_fu_747_p2 ^ 1'd1);

assign xor_ln1942_2_fu_810_p2 = (icmp_ln1942_5_fu_804_p2 ^ 1'd1);

assign xor_ln1942_fu_725_p2 = (icmp_ln1942_fu_720_p2 ^ 1'd1);

assign zext_ln1974_cast_fu_394_p1 = zext_ln1974;

endmodule //bd_quad_vmix_dp_v_tpg_2_0_tpgForeground_Pipeline_VITIS_LOOP_774_2
