// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module bd_quad_vmix_dp_v_mix_0_0_AXIvideo2MultiPixStream_1 (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        s_axis_video_TDATA,
        s_axis_video_TVALID,
        s_axis_video_TREADY,
        s_axis_video_TKEEP,
        s_axis_video_TSTRB,
        s_axis_video_TUSER,
        s_axis_video_TLAST,
        s_axis_video_TID,
        s_axis_video_TDEST,
        srcLayer0_din,
        srcLayer0_full_n,
        srcLayer0_write,
        srcLayer0_num_data_valid,
        srcLayer0_fifo_cap,
        Height,
        WidthIn,
        layerEnableFlag,
        HwReg_layerEnableFlag_0_val_c26_din,
        HwReg_layerEnableFlag_0_val_c26_full_n,
        HwReg_layerEnableFlag_0_val_c26_write,
        HwReg_layerEnableFlag_0_val_c26_num_data_valid,
        HwReg_layerEnableFlag_0_val_c26_fifo_cap
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_state2 = 9'd2;
parameter    ap_ST_fsm_state3 = 9'd4;
parameter    ap_ST_fsm_state4 = 9'd8;
parameter    ap_ST_fsm_state5 = 9'd16;
parameter    ap_ST_fsm_state6 = 9'd32;
parameter    ap_ST_fsm_state7 = 9'd64;
parameter    ap_ST_fsm_state8 = 9'd128;
parameter    ap_ST_fsm_state9 = 9'd256;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [47:0] s_axis_video_TDATA;
input   s_axis_video_TVALID;
output   s_axis_video_TREADY;
input  [5:0] s_axis_video_TKEEP;
input  [5:0] s_axis_video_TSTRB;
input  [0:0] s_axis_video_TUSER;
input  [0:0] s_axis_video_TLAST;
input  [0:0] s_axis_video_TID;
input  [0:0] s_axis_video_TDEST;
output  [47:0] srcLayer0_din;
input   srcLayer0_full_n;
output   srcLayer0_write;
input  [2:0] srcLayer0_num_data_valid;
input  [2:0] srcLayer0_fifo_cap;
input  [11:0] Height;
input  [11:0] WidthIn;
input  [0:0] layerEnableFlag;
output  [0:0] HwReg_layerEnableFlag_0_val_c26_din;
input   HwReg_layerEnableFlag_0_val_c26_full_n;
output   HwReg_layerEnableFlag_0_val_c26_write;
input  [2:0] HwReg_layerEnableFlag_0_val_c26_num_data_valid;
input  [2:0] HwReg_layerEnableFlag_0_val_c26_fifo_cap;

reg ap_done;
reg ap_idle;
reg start_write;
reg s_axis_video_TREADY;
reg HwReg_layerEnableFlag_0_val_c26_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    HwReg_layerEnableFlag_0_val_c26_blk_n;
reg   [0:0] layerEnableFlag_read_reg_457;
reg    ap_block_state1;
wire   [11:0] grp_reg_unsigned_short_1_fu_239_ap_return;
reg   [11:0] rows_reg_495;
wire    ap_CS_fsm_state2;
reg   [10:0] trunc_ln9_reg_514;
wire   [0:0] cmp10302_fu_327_p2;
reg   [0:0] cmp10302_reg_523;
wire    ap_CS_fsm_state4;
wire   [0:0] xor_ln3150_fu_332_p2;
reg   [0:0] xor_ln3150_reg_528;
wire   [0:0] and_ln3150_fu_356_p2;
reg   [0:0] and_ln3150_reg_539;
wire    ap_CS_fsm_state5;
wire   [0:0] select_ln3150_fu_410_p3;
reg   [0:0] select_ln3150_reg_550;
wire    ap_CS_fsm_state7;
wire    grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_168_ap_start;
wire    grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_168_ap_done;
wire    grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_168_ap_idle;
wire    grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_168_ap_ready;
wire    grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_168_s_axis_video_TREADY;
wire   [47:0] grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_168_axi_data_out;
wire    grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_168_axi_data_out_ap_vld;
wire   [0:0] grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_168_axi_last_out;
wire    grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_168_axi_last_out_ap_vld;
wire    grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_188_ap_start;
wire    grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_188_ap_done;
wire    grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_188_ap_idle;
wire    grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_188_ap_ready;
wire   [47:0] grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_188_srcLayer0_din;
wire    grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_188_srcLayer0_write;
wire    grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_188_s_axis_video_TREADY;
wire   [0:0] grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_188_eol_out;
wire    grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_188_eol_out_ap_vld;
wire   [47:0] grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_188_axi_data_25_out;
wire    grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_188_axi_data_25_out_ap_vld;
wire    grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_216_ap_start;
wire    grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_216_ap_done;
wire    grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_216_ap_idle;
wire    grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_216_ap_ready;
wire    grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_216_s_axis_video_TREADY;
wire   [47:0] grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_216_axi_data_4_out;
wire    grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_216_axi_data_4_out_ap_vld;
wire   [0:0] grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_216_axi_last_4_out;
wire    grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_216_axi_last_4_out_ap_vld;
reg    grp_reg_unsigned_short_1_fu_239_ap_start;
wire    grp_reg_unsigned_short_1_fu_239_ap_done;
wire    grp_reg_unsigned_short_1_fu_239_ap_idle;
wire    grp_reg_unsigned_short_1_fu_239_ap_ready;
reg    grp_reg_unsigned_short_1_fu_239_ap_ce;
reg    ap_block_state1_ignore_call14;
reg    grp_reg_unsigned_short_1_fu_245_ap_start;
wire    grp_reg_unsigned_short_1_fu_245_ap_done;
wire    grp_reg_unsigned_short_1_fu_245_ap_idle;
wire    grp_reg_unsigned_short_1_fu_245_ap_ready;
reg    grp_reg_unsigned_short_1_fu_245_ap_ce;
wire   [11:0] grp_reg_unsigned_short_1_fu_245_ap_return;
reg    ap_block_state1_ignore_call15;
reg   [0:0] sof_reg_146;
wire    ap_CS_fsm_state9;
reg   [0:0] axi_last_reg_158;
reg    grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_168_ap_start_reg;
wire    ap_CS_fsm_state3;
reg   [47:0] axi_data_fu_112;
reg    grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_188_ap_start_reg;
wire   [0:0] icmp_ln3101_fu_341_p2;
wire    ap_CS_fsm_state6;
reg    grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_216_ap_start_reg;
wire    ap_CS_fsm_state8;
reg   [0:0] axi_last_4_loc_fu_96;
reg   [11:0] i_fu_116;
wire   [11:0] i_10_fu_346_p2;
reg   [8:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 9'd1;
#0 grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_168_ap_start_reg = 1'b0;
#0 grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_188_ap_start_reg = 1'b0;
#0 grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_216_ap_start_reg = 1'b0;
#0 i_fu_116 = 12'd0;
end

bd_quad_vmix_dp_v_mix_0_0_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_168(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_168_ap_start),
    .ap_done(grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_168_ap_done),
    .ap_idle(grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_168_ap_idle),
    .ap_ready(grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_168_ap_ready),
    .s_axis_video_TVALID(s_axis_video_TVALID),
    .s_axis_video_TDATA(s_axis_video_TDATA),
    .s_axis_video_TREADY(grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_168_s_axis_video_TREADY),
    .s_axis_video_TKEEP(s_axis_video_TKEEP),
    .s_axis_video_TSTRB(s_axis_video_TSTRB),
    .s_axis_video_TUSER(s_axis_video_TUSER),
    .s_axis_video_TLAST(s_axis_video_TLAST),
    .s_axis_video_TID(s_axis_video_TID),
    .s_axis_video_TDEST(s_axis_video_TDEST),
    .axi_data_out(grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_168_axi_data_out),
    .axi_data_out_ap_vld(grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_168_axi_data_out_ap_vld),
    .axi_last_out(grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_168_axi_last_out),
    .axi_last_out_ap_vld(grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_168_axi_last_out_ap_vld)
);

bd_quad_vmix_dp_v_mix_0_0_AXIvideo2MultiPixStream_1_Pipeline_loop_width grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_188(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_188_ap_start),
    .ap_done(grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_188_ap_done),
    .ap_idle(grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_188_ap_idle),
    .ap_ready(grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_188_ap_ready),
    .s_axis_video_TVALID(s_axis_video_TVALID),
    .srcLayer0_din(grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_188_srcLayer0_din),
    .srcLayer0_full_n(srcLayer0_full_n),
    .srcLayer0_write(grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_188_srcLayer0_write),
    .srcLayer0_num_data_valid(3'd0),
    .srcLayer0_fifo_cap(3'd0),
    .sof_13(sof_reg_146),
    .axi_last_28(axi_last_reg_158),
    .axi_data_24(axi_data_fu_112),
    .trunc_ln9(trunc_ln9_reg_514),
    .s_axis_video_TDATA(s_axis_video_TDATA),
    .s_axis_video_TREADY(grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_188_s_axis_video_TREADY),
    .s_axis_video_TKEEP(s_axis_video_TKEEP),
    .s_axis_video_TSTRB(s_axis_video_TSTRB),
    .s_axis_video_TUSER(s_axis_video_TUSER),
    .s_axis_video_TLAST(s_axis_video_TLAST),
    .s_axis_video_TID(s_axis_video_TID),
    .s_axis_video_TDEST(s_axis_video_TDEST),
    .eol_out(grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_188_eol_out),
    .eol_out_ap_vld(grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_188_eol_out_ap_vld),
    .axi_data_25_out(grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_188_axi_data_25_out),
    .axi_data_25_out_ap_vld(grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_188_axi_data_25_out_ap_vld)
);

bd_quad_vmix_dp_v_mix_0_0_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_216(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_216_ap_start),
    .ap_done(grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_216_ap_done),
    .ap_idle(grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_216_ap_idle),
    .ap_ready(grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_216_ap_ready),
    .s_axis_video_TVALID(s_axis_video_TVALID),
    .axi_data_25_reload(grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_188_axi_data_25_out),
    .select_ln3150(select_ln3150_reg_550),
    .eol_reload(grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_188_eol_out),
    .s_axis_video_TDATA(s_axis_video_TDATA),
    .s_axis_video_TREADY(grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_216_s_axis_video_TREADY),
    .s_axis_video_TKEEP(s_axis_video_TKEEP),
    .s_axis_video_TSTRB(s_axis_video_TSTRB),
    .s_axis_video_TUSER(s_axis_video_TUSER),
    .s_axis_video_TLAST(s_axis_video_TLAST),
    .s_axis_video_TID(s_axis_video_TID),
    .s_axis_video_TDEST(s_axis_video_TDEST),
    .axi_data_4_out(grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_216_axi_data_4_out),
    .axi_data_4_out_ap_vld(grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_216_axi_data_4_out_ap_vld),
    .axi_last_4_out(grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_216_axi_last_4_out),
    .axi_last_4_out_ap_vld(grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_216_axi_last_4_out_ap_vld)
);

bd_quad_vmix_dp_v_mix_0_0_reg_unsigned_short_1 grp_reg_unsigned_short_1_fu_239(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_reg_unsigned_short_1_fu_239_ap_start),
    .ap_done(grp_reg_unsigned_short_1_fu_239_ap_done),
    .ap_idle(grp_reg_unsigned_short_1_fu_239_ap_idle),
    .ap_ready(grp_reg_unsigned_short_1_fu_239_ap_ready),
    .ap_ce(grp_reg_unsigned_short_1_fu_239_ap_ce),
    .d(Height),
    .ap_return(grp_reg_unsigned_short_1_fu_239_ap_return)
);

bd_quad_vmix_dp_v_mix_0_0_reg_unsigned_short_1 grp_reg_unsigned_short_1_fu_245(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_reg_unsigned_short_1_fu_245_ap_start),
    .ap_done(grp_reg_unsigned_short_1_fu_245_ap_done),
    .ap_idle(grp_reg_unsigned_short_1_fu_245_ap_idle),
    .ap_ready(grp_reg_unsigned_short_1_fu_245_ap_ready),
    .ap_ce(grp_reg_unsigned_short_1_fu_245_ap_ce),
    .d(WidthIn),
    .ap_return(grp_reg_unsigned_short_1_fu_245_ap_return)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state5) & ((layerEnableFlag_read_reg_457 == 1'd0) | (icmp_ln3101_fu_341_p2 == 1'd1)))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_216_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_216_ap_start_reg <= 1'b1;
        end else if ((grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_216_ap_ready == 1'b1)) begin
            grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_216_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_168_ap_start_reg <= 1'b0;
    end else begin
        if (((layerEnableFlag_read_reg_457 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_168_ap_start_reg <= 1'b1;
        end else if ((grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_168_ap_ready == 1'b1)) begin
            grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_168_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_188_ap_start_reg <= 1'b0;
    end else begin
        if (((layerEnableFlag_read_reg_457 == 1'd1) & (icmp_ln3101_fu_341_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
            grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_188_ap_start_reg <= 1'b1;
        end else if ((grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_188_ap_ready == 1'b1)) begin
            grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_188_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_216_axi_data_4_out_ap_vld == 1'b1))) begin
        axi_data_fu_112 <= grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_216_axi_data_4_out;
    end else if (((1'b1 == ap_CS_fsm_state3) & (grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_168_axi_data_out_ap_vld == 1'b1))) begin
        axi_data_fu_112 <= grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_168_axi_data_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        axi_last_reg_158 <= axi_last_4_loc_fu_96;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        axi_last_reg_158 <= grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_168_axi_last_out;
    end
end

always @ (posedge ap_clk) begin
    if ((layerEnableFlag_read_reg_457 == 1'd1)) begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            i_fu_116 <= 12'd0;
        end else if (((icmp_ln3101_fu_341_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
            i_fu_116 <= i_10_fu_346_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        sof_reg_146 <= and_ln3150_reg_539;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        sof_reg_146 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        and_ln3150_reg_539 <= and_ln3150_fu_356_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_216_axi_last_4_out_ap_vld == 1'b1))) begin
        axi_last_4_loc_fu_96 <= grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_216_axi_last_4_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        cmp10302_reg_523 <= cmp10302_fu_327_p2;
        xor_ln3150_reg_528 <= xor_ln3150_fu_332_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        layerEnableFlag_read_reg_457 <= layerEnableFlag;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        rows_reg_495 <= grp_reg_unsigned_short_1_fu_239_ap_return;
        trunc_ln9_reg_514 <= {{grp_reg_unsigned_short_1_fu_245_ap_return[11:1]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        select_ln3150_reg_550 <= select_ln3150_fu_410_p3;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_layerEnableFlag_0_val_c26_blk_n = HwReg_layerEnableFlag_0_val_c26_full_n;
    end else begin
        HwReg_layerEnableFlag_0_val_c26_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_layerEnableFlag_0_val_c26_write = 1'b1;
    end else begin
        HwReg_layerEnableFlag_0_val_c26_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_168_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_188_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_216_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & ((layerEnableFlag_read_reg_457 == 1'd0) | (icmp_ln3101_fu_341_p2 == 1'd1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (real_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((1'b0 == ap_block_state1_ignore_call14) & (1'b1 == ap_CS_fsm_state1)))) begin
        grp_reg_unsigned_short_1_fu_239_ap_ce = 1'b1;
    end else begin
        grp_reg_unsigned_short_1_fu_239_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b0 == ap_block_state1_ignore_call14) & (1'b1 == ap_CS_fsm_state1))) begin
        grp_reg_unsigned_short_1_fu_239_ap_start = 1'b1;
    end else begin
        grp_reg_unsigned_short_1_fu_239_ap_start = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) | ((1'b0 == ap_block_state1_ignore_call15) & (1'b1 == ap_CS_fsm_state1)))) begin
        grp_reg_unsigned_short_1_fu_245_ap_ce = 1'b1;
    end else begin
        grp_reg_unsigned_short_1_fu_245_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b0 == ap_block_state1_ignore_call15) & (1'b1 == ap_CS_fsm_state1))) begin
        grp_reg_unsigned_short_1_fu_245_ap_start = 1'b1;
    end else begin
        grp_reg_unsigned_short_1_fu_245_ap_start = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) & ((layerEnableFlag_read_reg_457 == 1'd0) | (icmp_ln3101_fu_341_p2 == 1'd1)))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        s_axis_video_TREADY = grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_216_s_axis_video_TREADY;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        s_axis_video_TREADY = grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_188_s_axis_video_TREADY;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        s_axis_video_TREADY = grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_168_s_axis_video_TREADY;
    end else begin
        s_axis_video_TREADY = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((layerEnableFlag_read_reg_457 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_168_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & ((layerEnableFlag_read_reg_457 == 1'd0) | (icmp_ln3101_fu_341_p2 == 1'd1)))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_188_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_216_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign HwReg_layerEnableFlag_0_val_c26_din = layerEnableFlag;

assign and_ln3150_fu_356_p2 = (xor_ln3150_reg_528 & sof_reg_146);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((1'b0 == HwReg_layerEnableFlag_0_val_c26_full_n) | (ap_done_reg == 1'b1) | (real_start == 1'b0));
end

always @ (*) begin
    ap_block_state1_ignore_call14 = ((1'b0 == HwReg_layerEnableFlag_0_val_c26_full_n) | (ap_done_reg == 1'b1) | (real_start == 1'b0));
end

always @ (*) begin
    ap_block_state1_ignore_call15 = ((1'b0 == HwReg_layerEnableFlag_0_val_c26_full_n) | (ap_done_reg == 1'b1) | (real_start == 1'b0));
end

assign ap_ready = internal_ap_ready;

assign cmp10302_fu_327_p2 = ((trunc_ln9_reg_514 != 11'd0) ? 1'b1 : 1'b0);

assign grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_216_ap_start = grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_eol_fu_216_ap_start_reg;

assign grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_168_ap_start = grp_AXIvideo2MultiPixStream_1_Pipeline_loop_wait_for_start_fu_168_ap_start_reg;

assign grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_188_ap_start = grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_188_ap_start_reg;

assign i_10_fu_346_p2 = (i_fu_116 + 12'd1);

assign icmp_ln3101_fu_341_p2 = ((i_fu_116 == rows_reg_495) ? 1'b1 : 1'b0);

assign select_ln3150_fu_410_p3 = ((cmp10302_reg_523[0:0] == 1'b1) ? grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_188_eol_out : axi_last_reg_158);

assign srcLayer0_din = grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_188_srcLayer0_din;

assign srcLayer0_write = grp_AXIvideo2MultiPixStream_1_Pipeline_loop_width_fu_188_srcLayer0_write;

assign start_out = real_start;

assign xor_ln3150_fu_332_p2 = (cmp10302_fu_327_p2 ^ 1'd1);

endmodule //bd_quad_vmix_dp_v_mix_0_0_AXIvideo2MultiPixStream_1
