// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module bd_quad_vmix_dp_v_tpg_3_0_tpgBackground (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        height_val,
        width_val,
        patternId_val,
        motionSpeed_val,
        colorFormat_val,
        bckgndYUV_din,
        bckgndYUV_full_n,
        bckgndYUV_write,
        bckgndYUV_num_data_valid,
        bckgndYUV_fifo_cap,
        height_val4_c3_din,
        height_val4_c3_full_n,
        height_val4_c3_write,
        height_val4_c3_num_data_valid,
        height_val4_c3_fifo_cap,
        width_val7_c4_din,
        width_val7_c4_full_n,
        width_val7_c4_write,
        width_val7_c4_num_data_valid,
        width_val7_c4_fifo_cap,
        motionSpeed_val14_c_din,
        motionSpeed_val14_c_full_n,
        motionSpeed_val14_c_write,
        motionSpeed_val14_c_num_data_valid,
        motionSpeed_val14_c_fifo_cap,
        colorFormat_val17_c5_din,
        colorFormat_val17_c5_full_n,
        colorFormat_val17_c5_write,
        colorFormat_val17_c5_num_data_valid,
        colorFormat_val17_c5_fifo_cap
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [15:0] height_val;
input  [15:0] width_val;
input  [7:0] patternId_val;
input  [7:0] motionSpeed_val;
input  [7:0] colorFormat_val;
output  [47:0] bckgndYUV_din;
input   bckgndYUV_full_n;
output   bckgndYUV_write;
input  [31:0] bckgndYUV_num_data_valid;
input  [31:0] bckgndYUV_fifo_cap;
output  [15:0] height_val4_c3_din;
input   height_val4_c3_full_n;
output   height_val4_c3_write;
input  [2:0] height_val4_c3_num_data_valid;
input  [2:0] height_val4_c3_fifo_cap;
output  [15:0] width_val7_c4_din;
input   width_val7_c4_full_n;
output   width_val7_c4_write;
input  [2:0] width_val7_c4_num_data_valid;
input  [2:0] width_val7_c4_fifo_cap;
output  [7:0] motionSpeed_val14_c_din;
input   motionSpeed_val14_c_full_n;
output   motionSpeed_val14_c_write;
input  [2:0] motionSpeed_val14_c_num_data_valid;
input  [2:0] motionSpeed_val14_c_fifo_cap;
output  [7:0] colorFormat_val17_c5_din;
input   colorFormat_val17_c5_full_n;
output   colorFormat_val17_c5_write;
input  [2:0] colorFormat_val17_c5_num_data_valid;
input  [2:0] colorFormat_val17_c5_fifo_cap;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg height_val4_c3_write;
reg width_val7_c4_write;
reg motionSpeed_val14_c_write;
reg colorFormat_val17_c5_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [1:0] blkYuv_address0;
wire   [7:0] blkYuv_q0;
reg   [7:0] rampStart;
reg    height_val4_c3_blk_n;
reg    width_val7_c4_blk_n;
reg    motionSpeed_val14_c_blk_n;
reg    colorFormat_val17_c5_blk_n;
reg   [7:0] colorFormat_val_read_reg_327;
reg    ap_block_state1;
reg   [7:0] motionSpeed_val_read_reg_332;
reg   [15:0] width_val_read_reg_337;
reg   [15:0] height_val_read_reg_342;
reg   [6:0] tmp_reg_347;
reg   [7:0] patternId_val_read_reg_357;
wire    ap_CS_fsm_state2;
reg   [7:0] blkYuv_load_reg_362;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_ap_start;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_ap_done;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_ap_idle;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_ap_ready;
wire   [47:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_bckgndYUV_din;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_bckgndYUV_write;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_outpix_0_5_0_0_0_load329_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_outpix_0_5_0_0_0_load329_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_outpix_0_4_0_0_0_load327_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_outpix_0_4_0_0_0_load327_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_outpix_0_3_0_0_0_load325_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_outpix_0_3_0_0_0_load325_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_outpix_0_2_0_0_0_load323_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_outpix_0_2_0_0_0_load323_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_outpix_0_1_0_0_0_load321_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_outpix_0_1_0_0_0_load321_out_o_ap_vld;
wire   [7:0] grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_outpix_0_0_0_0_0_load319_out_o;
wire    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_outpix_0_0_0_0_0_load319_out_o_ap_vld;
reg    grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_ap_start_reg;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln563_fu_259_p2;
wire    ap_CS_fsm_state4;
reg   [7:0] outpix_0_5_0_0_0_load330_lcssa348_fu_118;
reg   [7:0] outpix_0_4_0_0_0_load328_lcssa345_fu_114;
reg   [7:0] outpix_0_3_0_0_0_load326_lcssa342_fu_110;
reg   [7:0] outpix_0_2_0_0_0_load324_lcssa339_fu_106;
reg   [7:0] outpix_0_1_0_0_0_load322_lcssa336_fu_102;
reg   [7:0] outpix_0_0_0_0_0_load320_lcssa333_fu_98;
wire   [63:0] idxprom13_1_i188_cast_cast_cast_fu_242_p3;
wire   [7:0] add_ln750_fu_279_p2;
reg   [15:0] y_fu_94;
wire   [15:0] y_4_fu_264_p2;
reg    blkYuv_ce0_local;
wire   [0:0] cmp6_i184_fu_236_p2;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 rampStart = 8'd0;
#0 grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_ap_start_reg = 1'b0;
#0 y_fu_94 = 16'd0;
end

bd_quad_vmix_dp_v_tpg_3_0_tpgBackground_blkYuv_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
blkYuv_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(blkYuv_address0),
    .ce0(blkYuv_ce0_local),
    .q0(blkYuv_q0)
);

bd_quad_vmix_dp_v_tpg_3_0_tpgBackground_Pipeline_VITIS_LOOP_565_2 grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_ap_start),
    .ap_done(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_ap_done),
    .ap_idle(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_ap_idle),
    .ap_ready(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_ap_ready),
    .bckgndYUV_din(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_bckgndYUV_din),
    .bckgndYUV_full_n(bckgndYUV_full_n),
    .bckgndYUV_write(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_bckgndYUV_write),
    .bckgndYUV_num_data_valid(bckgndYUV_num_data_valid),
    .bckgndYUV_fifo_cap(bckgndYUV_fifo_cap),
    .width_val_cast(width_val_read_reg_337),
    .patternId_val(patternId_val_read_reg_357),
    .blkYuv_load(blkYuv_load_reg_362),
    .colorFormat_val(colorFormat_val_read_reg_327),
    .empty(tmp_reg_347),
    .outpix_0_5_0_0_0_load329_out_i(outpix_0_5_0_0_0_load330_lcssa348_fu_118),
    .outpix_0_5_0_0_0_load329_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_outpix_0_5_0_0_0_load329_out_o),
    .outpix_0_5_0_0_0_load329_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_outpix_0_5_0_0_0_load329_out_o_ap_vld),
    .outpix_0_4_0_0_0_load327_out_i(outpix_0_4_0_0_0_load328_lcssa345_fu_114),
    .outpix_0_4_0_0_0_load327_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_outpix_0_4_0_0_0_load327_out_o),
    .outpix_0_4_0_0_0_load327_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_outpix_0_4_0_0_0_load327_out_o_ap_vld),
    .outpix_0_3_0_0_0_load325_out_i(outpix_0_3_0_0_0_load326_lcssa342_fu_110),
    .outpix_0_3_0_0_0_load325_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_outpix_0_3_0_0_0_load325_out_o),
    .outpix_0_3_0_0_0_load325_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_outpix_0_3_0_0_0_load325_out_o_ap_vld),
    .outpix_0_2_0_0_0_load323_out_i(outpix_0_2_0_0_0_load324_lcssa339_fu_106),
    .outpix_0_2_0_0_0_load323_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_outpix_0_2_0_0_0_load323_out_o),
    .outpix_0_2_0_0_0_load323_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_outpix_0_2_0_0_0_load323_out_o_ap_vld),
    .outpix_0_1_0_0_0_load321_out_i(outpix_0_1_0_0_0_load322_lcssa336_fu_102),
    .outpix_0_1_0_0_0_load321_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_outpix_0_1_0_0_0_load321_out_o),
    .outpix_0_1_0_0_0_load321_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_outpix_0_1_0_0_0_load321_out_o_ap_vld),
    .outpix_0_0_0_0_0_load319_out_i(outpix_0_0_0_0_0_load320_lcssa333_fu_98),
    .outpix_0_0_0_0_0_load319_out_o(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_outpix_0_0_0_0_0_load319_out_o),
    .outpix_0_0_0_0_0_load319_out_o_ap_vld(grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_outpix_0_0_0_0_0_load319_out_o_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln563_fu_259_p2 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln563_fu_259_p2 == 1'd0))) begin
            grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_ap_start_reg <= 1'b1;
        end else if ((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_ap_ready == 1'b1)) begin
            grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        y_fu_94 <= 16'd0;
    end else if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln563_fu_259_p2 == 1'd0))) begin
        y_fu_94 <= y_4_fu_264_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        blkYuv_load_reg_362 <= blkYuv_q0;
        patternId_val_read_reg_357 <= patternId_val;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        colorFormat_val_read_reg_327 <= colorFormat_val;
        height_val_read_reg_342 <= height_val;
        motionSpeed_val_read_reg_332 <= motionSpeed_val;
        tmp_reg_347 <= {{colorFormat_val[7:1]}};
        width_val_read_reg_337 <= width_val;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_outpix_0_0_0_0_0_load319_out_o_ap_vld == 1'b1))) begin
        outpix_0_0_0_0_0_load320_lcssa333_fu_98 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_outpix_0_0_0_0_0_load319_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_outpix_0_1_0_0_0_load321_out_o_ap_vld == 1'b1))) begin
        outpix_0_1_0_0_0_load322_lcssa336_fu_102 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_outpix_0_1_0_0_0_load321_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_outpix_0_2_0_0_0_load323_out_o_ap_vld == 1'b1))) begin
        outpix_0_2_0_0_0_load324_lcssa339_fu_106 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_outpix_0_2_0_0_0_load323_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_outpix_0_3_0_0_0_load325_out_o_ap_vld == 1'b1))) begin
        outpix_0_3_0_0_0_load326_lcssa342_fu_110 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_outpix_0_3_0_0_0_load325_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_outpix_0_4_0_0_0_load327_out_o_ap_vld == 1'b1))) begin
        outpix_0_4_0_0_0_load328_lcssa345_fu_114 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_outpix_0_4_0_0_0_load327_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_outpix_0_5_0_0_0_load329_out_o_ap_vld == 1'b1))) begin
        outpix_0_5_0_0_0_load330_lcssa348_fu_118 <= grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_outpix_0_5_0_0_0_load329_out_o;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln563_fu_259_p2 == 1'd1))) begin
        rampStart <= add_ln750_fu_279_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln563_fu_259_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln563_fu_259_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        blkYuv_ce0_local = 1'b1;
    end else begin
        blkYuv_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        colorFormat_val17_c5_blk_n = colorFormat_val17_c5_full_n;
    end else begin
        colorFormat_val17_c5_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        colorFormat_val17_c5_write = 1'b1;
    end else begin
        colorFormat_val17_c5_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        height_val4_c3_blk_n = height_val4_c3_full_n;
    end else begin
        height_val4_c3_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        height_val4_c3_write = 1'b1;
    end else begin
        height_val4_c3_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        motionSpeed_val14_c_blk_n = motionSpeed_val14_c_full_n;
    end else begin
        motionSpeed_val14_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        motionSpeed_val14_c_write = 1'b1;
    end else begin
        motionSpeed_val14_c_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        width_val7_c4_blk_n = width_val7_c4_full_n;
    end else begin
        width_val7_c4_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        width_val7_c4_write = 1'b1;
    end else begin
        width_val7_c4_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln563_fu_259_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln750_fu_279_p2 = (rampStart + motionSpeed_val_read_reg_332);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (colorFormat_val17_c5_full_n == 1'b0) | (motionSpeed_val14_c_full_n == 1'b0) | (width_val7_c4_full_n == 1'b0) | (height_val4_c3_full_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign bckgndYUV_din = grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_bckgndYUV_din;

assign bckgndYUV_write = grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_bckgndYUV_write;

assign blkYuv_address0 = idxprom13_1_i188_cast_cast_cast_fu_242_p3;

assign cmp6_i184_fu_236_p2 = ((colorFormat_val == 8'd1) ? 1'b1 : 1'b0);

assign colorFormat_val17_c5_din = colorFormat_val;

assign grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_ap_start = grp_tpgBackground_Pipeline_VITIS_LOOP_565_2_fu_197_ap_start_reg;

assign height_val4_c3_din = height_val;

assign icmp_ln563_fu_259_p2 = ((y_fu_94 == height_val_read_reg_342) ? 1'b1 : 1'b0);

assign idxprom13_1_i188_cast_cast_cast_fu_242_p3 = ((cmp6_i184_fu_236_p2[0:0] == 1'b1) ? 64'd1 : 64'd2);

assign motionSpeed_val14_c_din = motionSpeed_val;

assign width_val7_c4_din = width_val;

assign y_4_fu_264_p2 = (y_fu_94 + 16'd1);

endmodule //bd_quad_vmix_dp_v_tpg_3_0_tpgBackground
