// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module bd_quad_vmix_dp_v_mix_0_0_v_mix_core_alpha_false_false_20 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        outLayer1_dout,
        outLayer1_empty_n,
        outLayer1_read,
        outLayer1_num_data_valid,
        outLayer1_fifo_cap,
        srcLayer2x_dout,
        srcLayer2x_empty_n,
        srcLayer2x_read,
        srcLayer2x_num_data_valid,
        srcLayer2x_fifo_cap,
        HwReg_width_val,
        HwReg_height_val,
        HwReg_layerEnable_val25_dout,
        HwReg_layerEnable_val25_empty_n,
        HwReg_layerEnable_val25_read,
        HwReg_layerEnable_val25_num_data_valid,
        HwReg_layerEnable_val25_fifo_cap,
        HwReg_layerStartX_2_val27_dout,
        HwReg_layerStartX_2_val27_empty_n,
        HwReg_layerStartX_2_val27_read,
        HwReg_layerStartX_2_val27_num_data_valid,
        HwReg_layerStartX_2_val27_fifo_cap,
        HwReg_layerStartY_2_val31_dout,
        HwReg_layerStartY_2_val31_empty_n,
        HwReg_layerStartY_2_val31_read,
        HwReg_layerStartY_2_val31_num_data_valid,
        HwReg_layerStartY_2_val31_fifo_cap,
        HwReg_layerWidth_2_val_dout,
        HwReg_layerWidth_2_val_empty_n,
        HwReg_layerWidth_2_val_read,
        HwReg_layerWidth_2_val_num_data_valid,
        HwReg_layerWidth_2_val_fifo_cap,
        HwReg_layerHeight_2_val_dout,
        HwReg_layerHeight_2_val_empty_n,
        HwReg_layerHeight_2_val_read,
        HwReg_layerHeight_2_val_num_data_valid,
        HwReg_layerHeight_2_val_fifo_cap,
        HwReg_layerScaleFactor_2_val43_dout,
        HwReg_layerScaleFactor_2_val43_empty_n,
        HwReg_layerScaleFactor_2_val43_read,
        HwReg_layerScaleFactor_2_val43_num_data_valid,
        HwReg_layerScaleFactor_2_val43_fifo_cap,
        outLayer2_din,
        outLayer2_full_n,
        outLayer2_write,
        outLayer2_num_data_valid,
        outLayer2_fifo_cap,
        HwReg_layerEnable_val25_c22_din,
        HwReg_layerEnable_val25_c22_full_n,
        HwReg_layerEnable_val25_c22_write,
        HwReg_layerEnable_val25_c22_num_data_valid,
        HwReg_layerEnable_val25_c22_fifo_cap
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [47:0] outLayer1_dout;
input   outLayer1_empty_n;
output   outLayer1_read;
input  [2:0] outLayer1_num_data_valid;
input  [2:0] outLayer1_fifo_cap;
input  [47:0] srcLayer2x_dout;
input   srcLayer2x_empty_n;
output   srcLayer2x_read;
input  [2:0] srcLayer2x_num_data_valid;
input  [2:0] srcLayer2x_fifo_cap;
input  [11:0] HwReg_width_val;
input  [11:0] HwReg_height_val;
input  [4:0] HwReg_layerEnable_val25_dout;
input   HwReg_layerEnable_val25_empty_n;
output   HwReg_layerEnable_val25_read;
input  [2:0] HwReg_layerEnable_val25_num_data_valid;
input  [2:0] HwReg_layerEnable_val25_fifo_cap;
input  [15:0] HwReg_layerStartX_2_val27_dout;
input   HwReg_layerStartX_2_val27_empty_n;
output   HwReg_layerStartX_2_val27_read;
input  [3:0] HwReg_layerStartX_2_val27_num_data_valid;
input  [3:0] HwReg_layerStartX_2_val27_fifo_cap;
input  [15:0] HwReg_layerStartY_2_val31_dout;
input   HwReg_layerStartY_2_val31_empty_n;
output   HwReg_layerStartY_2_val31_read;
input  [3:0] HwReg_layerStartY_2_val31_num_data_valid;
input  [3:0] HwReg_layerStartY_2_val31_fifo_cap;
input  [15:0] HwReg_layerWidth_2_val_dout;
input   HwReg_layerWidth_2_val_empty_n;
output   HwReg_layerWidth_2_val_read;
input  [2:0] HwReg_layerWidth_2_val_num_data_valid;
input  [2:0] HwReg_layerWidth_2_val_fifo_cap;
input  [15:0] HwReg_layerHeight_2_val_dout;
input   HwReg_layerHeight_2_val_empty_n;
output   HwReg_layerHeight_2_val_read;
input  [2:0] HwReg_layerHeight_2_val_num_data_valid;
input  [2:0] HwReg_layerHeight_2_val_fifo_cap;
input  [7:0] HwReg_layerScaleFactor_2_val43_dout;
input   HwReg_layerScaleFactor_2_val43_empty_n;
output   HwReg_layerScaleFactor_2_val43_read;
input  [3:0] HwReg_layerScaleFactor_2_val43_num_data_valid;
input  [3:0] HwReg_layerScaleFactor_2_val43_fifo_cap;
output  [47:0] outLayer2_din;
input   outLayer2_full_n;
output   outLayer2_write;
input  [31:0] outLayer2_num_data_valid;
input  [31:0] outLayer2_fifo_cap;
output  [4:0] HwReg_layerEnable_val25_c22_din;
input   HwReg_layerEnable_val25_c22_full_n;
output   HwReg_layerEnable_val25_c22_write;
input  [2:0] HwReg_layerEnable_val25_c22_num_data_valid;
input  [2:0] HwReg_layerEnable_val25_c22_fifo_cap;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg HwReg_layerEnable_val25_read;
reg HwReg_layerStartX_2_val27_read;
reg HwReg_layerStartY_2_val31_read;
reg HwReg_layerWidth_2_val_read;
reg HwReg_layerHeight_2_val_read;
reg HwReg_layerScaleFactor_2_val43_read;
reg HwReg_layerEnable_val25_c22_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    HwReg_layerEnable_val25_blk_n;
reg    HwReg_layerStartX_2_val27_blk_n;
reg    HwReg_layerStartY_2_val31_blk_n;
reg    HwReg_layerWidth_2_val_blk_n;
reg    HwReg_layerHeight_2_val_blk_n;
reg    HwReg_layerScaleFactor_2_val43_blk_n;
reg    HwReg_layerEnable_val25_c22_blk_n;
reg   [11:0] HwReg_height_val_read_reg_311;
reg    ap_block_state1;
reg   [15:0] layerStartY_reg_316;
reg   [10:0] div_cast_i_reg_321;
wire   [16:0] add60_i_fu_206_p2;
reg   [16:0] add60_i_reg_326;
reg   [14:0] div65_cast_i_reg_331;
reg   [15:0] div72_cast_i_reg_336;
reg   [0:0] tmp_8_reg_341;
wire   [0:0] rev13_fu_286_p2;
reg   [0:0] rev13_reg_349;
wire    ap_CS_fsm_state2;
wire   [0:0] cmp61_i_fu_293_p2;
reg   [0:0] cmp61_i_reg_354;
wire    grp_v_mix_core_alpha_false_false_20_Pipeline_VITIS_LOOP_465_3_fu_152_ap_start;
wire    grp_v_mix_core_alpha_false_false_20_Pipeline_VITIS_LOOP_465_3_fu_152_ap_done;
wire    grp_v_mix_core_alpha_false_false_20_Pipeline_VITIS_LOOP_465_3_fu_152_ap_idle;
wire    grp_v_mix_core_alpha_false_false_20_Pipeline_VITIS_LOOP_465_3_fu_152_ap_ready;
wire    grp_v_mix_core_alpha_false_false_20_Pipeline_VITIS_LOOP_465_3_fu_152_outLayer1_read;
wire    grp_v_mix_core_alpha_false_false_20_Pipeline_VITIS_LOOP_465_3_fu_152_srcLayer2x_read;
wire   [47:0] grp_v_mix_core_alpha_false_false_20_Pipeline_VITIS_LOOP_465_3_fu_152_outLayer2_din;
wire    grp_v_mix_core_alpha_false_false_20_Pipeline_VITIS_LOOP_465_3_fu_152_outLayer2_write;
reg    grp_v_mix_core_alpha_false_false_20_Pipeline_VITIS_LOOP_465_3_fu_152_ap_start_reg;
wire   [0:0] icmp_ln463_fu_262_p2;
wire    ap_CS_fsm_state3;
reg   [11:0] y_fu_92;
wire   [11:0] add_ln463_fu_267_p2;
wire   [15:0] HwReg_layerScaleFactor_2_val43_readcast_fu_168_p1;
wire   [15:0] HwReg_layerScaleFactor_2_val43_readcast14_fu_178_p1;
wire   [15:0] shl_ln449_fu_172_p2;
wire   [16:0] layerHeight_cast_i_fu_202_p1;
wire   [16:0] hwReg_layerStartY_2_val_cast_i_fu_198_p1;
wire   [15:0] shl_ln450_fu_182_p2;
wire   [16:0] layerWidth_cast_i_fu_226_p1;
wire   [16:0] hwReg_layerStartX_2_val_cast_i_fu_212_p1;
wire   [16:0] add71_i_fu_230_p2;
wire   [15:0] zext_ln463_3_fu_277_p1;
wire   [0:0] ult_fu_281_p2;
wire   [16:0] zext_ln463_fu_273_p1;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 grp_v_mix_core_alpha_false_false_20_Pipeline_VITIS_LOOP_465_3_fu_152_ap_start_reg = 1'b0;
#0 y_fu_92 = 12'd0;
end

bd_quad_vmix_dp_v_mix_0_0_v_mix_core_alpha_false_false_20_Pipeline_VITIS_LOOP_465_3 grp_v_mix_core_alpha_false_false_20_Pipeline_VITIS_LOOP_465_3_fu_152(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_v_mix_core_alpha_false_false_20_Pipeline_VITIS_LOOP_465_3_fu_152_ap_start),
    .ap_done(grp_v_mix_core_alpha_false_false_20_Pipeline_VITIS_LOOP_465_3_fu_152_ap_done),
    .ap_idle(grp_v_mix_core_alpha_false_false_20_Pipeline_VITIS_LOOP_465_3_fu_152_ap_idle),
    .ap_ready(grp_v_mix_core_alpha_false_false_20_Pipeline_VITIS_LOOP_465_3_fu_152_ap_ready),
    .outLayer1_dout(outLayer1_dout),
    .outLayer1_empty_n(outLayer1_empty_n),
    .outLayer1_read(grp_v_mix_core_alpha_false_false_20_Pipeline_VITIS_LOOP_465_3_fu_152_outLayer1_read),
    .outLayer1_num_data_valid(3'd0),
    .outLayer1_fifo_cap(3'd0),
    .srcLayer2x_dout(srcLayer2x_dout),
    .srcLayer2x_empty_n(srcLayer2x_empty_n),
    .srcLayer2x_read(grp_v_mix_core_alpha_false_false_20_Pipeline_VITIS_LOOP_465_3_fu_152_srcLayer2x_read),
    .srcLayer2x_num_data_valid(3'd0),
    .srcLayer2x_fifo_cap(3'd0),
    .outLayer2_din(grp_v_mix_core_alpha_false_false_20_Pipeline_VITIS_LOOP_465_3_fu_152_outLayer2_din),
    .outLayer2_full_n(outLayer2_full_n),
    .outLayer2_write(grp_v_mix_core_alpha_false_false_20_Pipeline_VITIS_LOOP_465_3_fu_152_outLayer2_write),
    .outLayer2_num_data_valid(outLayer2_num_data_valid),
    .outLayer2_fifo_cap(outLayer2_fifo_cap),
    .div_cast_i(div_cast_i_reg_321),
    .div65_cast_i(div65_cast_i_reg_331),
    .div72_cast_i(div72_cast_i_reg_336),
    .cmp61_i(cmp61_i_reg_354),
    .rev5(rev13_reg_349),
    .empty(tmp_8_reg_341)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln463_fu_262_p2 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_v_mix_core_alpha_false_false_20_Pipeline_VITIS_LOOP_465_3_fu_152_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln463_fu_262_p2 == 1'd0))) begin
            grp_v_mix_core_alpha_false_false_20_Pipeline_VITIS_LOOP_465_3_fu_152_ap_start_reg <= 1'b1;
        end else if ((grp_v_mix_core_alpha_false_false_20_Pipeline_VITIS_LOOP_465_3_fu_152_ap_ready == 1'b1)) begin
            grp_v_mix_core_alpha_false_false_20_Pipeline_VITIS_LOOP_465_3_fu_152_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        y_fu_92 <= 12'd0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln463_fu_262_p2 == 1'd0))) begin
        y_fu_92 <= add_ln463_fu_267_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        HwReg_height_val_read_reg_311 <= HwReg_height_val;
        add60_i_reg_326 <= add60_i_fu_206_p2;
        div65_cast_i_reg_331 <= {{HwReg_layerStartX_2_val27_dout[15:1]}};
        div72_cast_i_reg_336 <= {{add71_i_fu_230_p2[16:1]}};
        div_cast_i_reg_321 <= {{HwReg_width_val[11:1]}};
        layerStartY_reg_316 <= HwReg_layerStartY_2_val31_dout;
        tmp_8_reg_341 <= HwReg_layerEnable_val25_dout[32'd2];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        cmp61_i_reg_354 <= cmp61_i_fu_293_p2;
        rev13_reg_349 <= rev13_fu_286_p2;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_layerEnable_val25_blk_n = HwReg_layerEnable_val25_empty_n;
    end else begin
        HwReg_layerEnable_val25_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_layerEnable_val25_c22_blk_n = HwReg_layerEnable_val25_c22_full_n;
    end else begin
        HwReg_layerEnable_val25_c22_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        HwReg_layerEnable_val25_c22_write = 1'b1;
    end else begin
        HwReg_layerEnable_val25_c22_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        HwReg_layerEnable_val25_read = 1'b1;
    end else begin
        HwReg_layerEnable_val25_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_layerHeight_2_val_blk_n = HwReg_layerHeight_2_val_empty_n;
    end else begin
        HwReg_layerHeight_2_val_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        HwReg_layerHeight_2_val_read = 1'b1;
    end else begin
        HwReg_layerHeight_2_val_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_layerScaleFactor_2_val43_blk_n = HwReg_layerScaleFactor_2_val43_empty_n;
    end else begin
        HwReg_layerScaleFactor_2_val43_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        HwReg_layerScaleFactor_2_val43_read = 1'b1;
    end else begin
        HwReg_layerScaleFactor_2_val43_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_layerStartX_2_val27_blk_n = HwReg_layerStartX_2_val27_empty_n;
    end else begin
        HwReg_layerStartX_2_val27_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        HwReg_layerStartX_2_val27_read = 1'b1;
    end else begin
        HwReg_layerStartX_2_val27_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_layerStartY_2_val31_blk_n = HwReg_layerStartY_2_val31_empty_n;
    end else begin
        HwReg_layerStartY_2_val31_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        HwReg_layerStartY_2_val31_read = 1'b1;
    end else begin
        HwReg_layerStartY_2_val31_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_layerWidth_2_val_blk_n = HwReg_layerWidth_2_val_empty_n;
    end else begin
        HwReg_layerWidth_2_val_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        HwReg_layerWidth_2_val_read = 1'b1;
    end else begin
        HwReg_layerWidth_2_val_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_v_mix_core_alpha_false_false_20_Pipeline_VITIS_LOOP_465_3_fu_152_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln463_fu_262_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln463_fu_262_p2 == 1'd1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln463_fu_262_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_v_mix_core_alpha_false_false_20_Pipeline_VITIS_LOOP_465_3_fu_152_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign HwReg_layerEnable_val25_c22_din = HwReg_layerEnable_val25_dout;

assign HwReg_layerScaleFactor_2_val43_readcast14_fu_178_p1 = HwReg_layerScaleFactor_2_val43_dout;

assign HwReg_layerScaleFactor_2_val43_readcast_fu_168_p1 = HwReg_layerScaleFactor_2_val43_dout;

assign add60_i_fu_206_p2 = (layerHeight_cast_i_fu_202_p1 + hwReg_layerStartY_2_val_cast_i_fu_198_p1);

assign add71_i_fu_230_p2 = (layerWidth_cast_i_fu_226_p1 + hwReg_layerStartX_2_val_cast_i_fu_212_p1);

assign add_ln463_fu_267_p2 = (y_fu_92 + 12'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (1'b0 == HwReg_layerEnable_val25_c22_full_n) | (1'b0 == HwReg_layerScaleFactor_2_val43_empty_n) | (1'b0 == HwReg_layerHeight_2_val_empty_n) | (1'b0 == HwReg_layerWidth_2_val_empty_n) | (1'b0 == HwReg_layerStartY_2_val31_empty_n) | (1'b0 == HwReg_layerStartX_2_val27_empty_n) | (1'b0 == HwReg_layerEnable_val25_empty_n) | (ap_done_reg == 1'b1));
end

assign cmp61_i_fu_293_p2 = ((add60_i_reg_326 > zext_ln463_fu_273_p1) ? 1'b1 : 1'b0);

assign grp_v_mix_core_alpha_false_false_20_Pipeline_VITIS_LOOP_465_3_fu_152_ap_start = grp_v_mix_core_alpha_false_false_20_Pipeline_VITIS_LOOP_465_3_fu_152_ap_start_reg;

assign hwReg_layerStartX_2_val_cast_i_fu_212_p1 = HwReg_layerStartX_2_val27_dout;

assign hwReg_layerStartY_2_val_cast_i_fu_198_p1 = HwReg_layerStartY_2_val31_dout;

assign icmp_ln463_fu_262_p2 = ((y_fu_92 == HwReg_height_val_read_reg_311) ? 1'b1 : 1'b0);

assign layerHeight_cast_i_fu_202_p1 = shl_ln449_fu_172_p2;

assign layerWidth_cast_i_fu_226_p1 = shl_ln450_fu_182_p2;

assign outLayer1_read = grp_v_mix_core_alpha_false_false_20_Pipeline_VITIS_LOOP_465_3_fu_152_outLayer1_read;

assign outLayer2_din = grp_v_mix_core_alpha_false_false_20_Pipeline_VITIS_LOOP_465_3_fu_152_outLayer2_din;

assign outLayer2_write = grp_v_mix_core_alpha_false_false_20_Pipeline_VITIS_LOOP_465_3_fu_152_outLayer2_write;

assign rev13_fu_286_p2 = (ult_fu_281_p2 ^ 1'd1);

assign shl_ln449_fu_172_p2 = HwReg_layerHeight_2_val_dout << HwReg_layerScaleFactor_2_val43_readcast_fu_168_p1;

assign shl_ln450_fu_182_p2 = HwReg_layerWidth_2_val_dout << HwReg_layerScaleFactor_2_val43_readcast14_fu_178_p1;

assign srcLayer2x_read = grp_v_mix_core_alpha_false_false_20_Pipeline_VITIS_LOOP_465_3_fu_152_srcLayer2x_read;

assign ult_fu_281_p2 = ((zext_ln463_3_fu_277_p1 < layerStartY_reg_316) ? 1'b1 : 1'b0);

assign zext_ln463_3_fu_277_p1 = y_fu_92;

assign zext_ln463_fu_273_p1 = y_fu_92;

endmodule //bd_quad_vmix_dp_v_mix_0_0_v_mix_core_alpha_false_false_20
