// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module bd_quad_vmix_dp_v_mix_0_0_v_mix_core_alpha_false_false_22 (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        outLayer3_dout,
        outLayer3_empty_n,
        outLayer3_read,
        outLayer3_num_data_valid,
        outLayer3_fifo_cap,
        srcLayer4x_dout,
        srcLayer4x_empty_n,
        srcLayer4x_read,
        srcLayer4x_num_data_valid,
        srcLayer4x_fifo_cap,
        hwReg_width_val,
        hwReg_height_val,
        hwReg_layerEnable_val_dout,
        hwReg_layerEnable_val_empty_n,
        hwReg_layerEnable_val_read,
        hwReg_layerEnable_val_num_data_valid,
        hwReg_layerEnable_val_fifo_cap,
        hwReg_layerStartX_4_val_dout,
        hwReg_layerStartX_4_val_empty_n,
        hwReg_layerStartX_4_val_read,
        hwReg_layerStartX_4_val_num_data_valid,
        hwReg_layerStartX_4_val_fifo_cap,
        hwReg_layerStartY_4_val_dout,
        hwReg_layerStartY_4_val_empty_n,
        hwReg_layerStartY_4_val_read,
        hwReg_layerStartY_4_val_num_data_valid,
        hwReg_layerStartY_4_val_fifo_cap,
        hwReg_layerWidth_4_val_dout,
        hwReg_layerWidth_4_val_empty_n,
        hwReg_layerWidth_4_val_read,
        hwReg_layerWidth_4_val_num_data_valid,
        hwReg_layerWidth_4_val_fifo_cap,
        hwReg_layerHeight_4_val_dout,
        hwReg_layerHeight_4_val_empty_n,
        hwReg_layerHeight_4_val_read,
        hwReg_layerHeight_4_val_num_data_valid,
        hwReg_layerHeight_4_val_fifo_cap,
        hwReg_layerScaleFactor_4_val_dout,
        hwReg_layerScaleFactor_4_val_empty_n,
        hwReg_layerScaleFactor_4_val_read,
        hwReg_layerScaleFactor_4_val_num_data_valid,
        hwReg_layerScaleFactor_4_val_fifo_cap,
        outLayer4_din,
        outLayer4_full_n,
        outLayer4_write,
        outLayer4_num_data_valid,
        outLayer4_fifo_cap
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [47:0] outLayer3_dout;
input   outLayer3_empty_n;
output   outLayer3_read;
input  [2:0] outLayer3_num_data_valid;
input  [2:0] outLayer3_fifo_cap;
input  [47:0] srcLayer4x_dout;
input   srcLayer4x_empty_n;
output   srcLayer4x_read;
input  [2:0] srcLayer4x_num_data_valid;
input  [2:0] srcLayer4x_fifo_cap;
input  [11:0] hwReg_width_val;
input  [11:0] hwReg_height_val;
input  [4:0] hwReg_layerEnable_val_dout;
input   hwReg_layerEnable_val_empty_n;
output   hwReg_layerEnable_val_read;
input  [2:0] hwReg_layerEnable_val_num_data_valid;
input  [2:0] hwReg_layerEnable_val_fifo_cap;
input  [15:0] hwReg_layerStartX_4_val_dout;
input   hwReg_layerStartX_4_val_empty_n;
output   hwReg_layerStartX_4_val_read;
input  [4:0] hwReg_layerStartX_4_val_num_data_valid;
input  [4:0] hwReg_layerStartX_4_val_fifo_cap;
input  [15:0] hwReg_layerStartY_4_val_dout;
input   hwReg_layerStartY_4_val_empty_n;
output   hwReg_layerStartY_4_val_read;
input  [4:0] hwReg_layerStartY_4_val_num_data_valid;
input  [4:0] hwReg_layerStartY_4_val_fifo_cap;
input  [15:0] hwReg_layerWidth_4_val_dout;
input   hwReg_layerWidth_4_val_empty_n;
output   hwReg_layerWidth_4_val_read;
input  [3:0] hwReg_layerWidth_4_val_num_data_valid;
input  [3:0] hwReg_layerWidth_4_val_fifo_cap;
input  [15:0] hwReg_layerHeight_4_val_dout;
input   hwReg_layerHeight_4_val_empty_n;
output   hwReg_layerHeight_4_val_read;
input  [3:0] hwReg_layerHeight_4_val_num_data_valid;
input  [3:0] hwReg_layerHeight_4_val_fifo_cap;
input  [7:0] hwReg_layerScaleFactor_4_val_dout;
input   hwReg_layerScaleFactor_4_val_empty_n;
output   hwReg_layerScaleFactor_4_val_read;
input  [4:0] hwReg_layerScaleFactor_4_val_num_data_valid;
input  [4:0] hwReg_layerScaleFactor_4_val_fifo_cap;
output  [47:0] outLayer4_din;
input   outLayer4_full_n;
output   outLayer4_write;
input  [31:0] outLayer4_num_data_valid;
input  [31:0] outLayer4_fifo_cap;

reg ap_done;
reg ap_idle;
reg start_write;
reg hwReg_layerEnable_val_read;
reg hwReg_layerStartX_4_val_read;
reg hwReg_layerStartY_4_val_read;
reg hwReg_layerWidth_4_val_read;
reg hwReg_layerHeight_4_val_read;
reg hwReg_layerScaleFactor_4_val_read;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    hwReg_layerEnable_val_blk_n;
reg    hwReg_layerStartX_4_val_blk_n;
reg    hwReg_layerStartY_4_val_blk_n;
reg    hwReg_layerWidth_4_val_blk_n;
reg    hwReg_layerHeight_4_val_blk_n;
reg    hwReg_layerScaleFactor_4_val_blk_n;
reg   [11:0] hwReg_height_val_read_reg_301;
reg    ap_block_state1;
reg   [15:0] layerStartY_reg_306;
reg   [10:0] div_cast_reg_311;
wire   [16:0] add60_fu_196_p2;
reg   [16:0] add60_reg_316;
reg   [14:0] div65_cast_reg_321;
reg   [15:0] div72_cast_reg_326;
reg   [0:0] tmp_4_reg_331;
wire   [0:0] rev12_fu_276_p2;
reg   [0:0] rev12_reg_339;
wire    ap_CS_fsm_state2;
wire   [0:0] cmp61_fu_283_p2;
reg   [0:0] cmp61_reg_344;
wire    grp_v_mix_core_alpha_false_false_22_Pipeline_VITIS_LOOP_465_3_fu_142_ap_start;
wire    grp_v_mix_core_alpha_false_false_22_Pipeline_VITIS_LOOP_465_3_fu_142_ap_done;
wire    grp_v_mix_core_alpha_false_false_22_Pipeline_VITIS_LOOP_465_3_fu_142_ap_idle;
wire    grp_v_mix_core_alpha_false_false_22_Pipeline_VITIS_LOOP_465_3_fu_142_ap_ready;
wire    grp_v_mix_core_alpha_false_false_22_Pipeline_VITIS_LOOP_465_3_fu_142_outLayer3_read;
wire    grp_v_mix_core_alpha_false_false_22_Pipeline_VITIS_LOOP_465_3_fu_142_srcLayer4x_read;
wire   [47:0] grp_v_mix_core_alpha_false_false_22_Pipeline_VITIS_LOOP_465_3_fu_142_outLayer4_din;
wire    grp_v_mix_core_alpha_false_false_22_Pipeline_VITIS_LOOP_465_3_fu_142_outLayer4_write;
reg    grp_v_mix_core_alpha_false_false_22_Pipeline_VITIS_LOOP_465_3_fu_142_ap_start_reg;
wire   [0:0] icmp_ln463_fu_252_p2;
wire    ap_CS_fsm_state3;
reg   [11:0] y_fu_90;
wire   [11:0] add_ln463_fu_257_p2;
wire   [15:0] hwReg_layerScaleFactor_4_val_readcast_fu_158_p1;
wire   [15:0] hwReg_layerScaleFactor_4_val_readcast13_fu_168_p1;
wire   [15:0] shl_ln449_fu_162_p2;
wire   [16:0] layerHeight_cast_fu_192_p1;
wire   [16:0] hwReg_layerStartY_4_val_cast_fu_188_p1;
wire   [15:0] shl_ln450_fu_172_p2;
wire   [16:0] layerWidth_cast_fu_216_p1;
wire   [16:0] hwReg_layerStartX_4_val_cast_fu_202_p1;
wire   [16:0] add71_fu_220_p2;
wire   [15:0] zext_ln463_1_fu_267_p1;
wire   [0:0] ult_fu_271_p2;
wire   [16:0] zext_ln463_fu_263_p1;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 grp_v_mix_core_alpha_false_false_22_Pipeline_VITIS_LOOP_465_3_fu_142_ap_start_reg = 1'b0;
#0 y_fu_90 = 12'd0;
end

bd_quad_vmix_dp_v_mix_0_0_v_mix_core_alpha_false_false_22_Pipeline_VITIS_LOOP_465_3 grp_v_mix_core_alpha_false_false_22_Pipeline_VITIS_LOOP_465_3_fu_142(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_v_mix_core_alpha_false_false_22_Pipeline_VITIS_LOOP_465_3_fu_142_ap_start),
    .ap_done(grp_v_mix_core_alpha_false_false_22_Pipeline_VITIS_LOOP_465_3_fu_142_ap_done),
    .ap_idle(grp_v_mix_core_alpha_false_false_22_Pipeline_VITIS_LOOP_465_3_fu_142_ap_idle),
    .ap_ready(grp_v_mix_core_alpha_false_false_22_Pipeline_VITIS_LOOP_465_3_fu_142_ap_ready),
    .outLayer3_dout(outLayer3_dout),
    .outLayer3_empty_n(outLayer3_empty_n),
    .outLayer3_read(grp_v_mix_core_alpha_false_false_22_Pipeline_VITIS_LOOP_465_3_fu_142_outLayer3_read),
    .outLayer3_num_data_valid(3'd0),
    .outLayer3_fifo_cap(3'd0),
    .srcLayer4x_dout(srcLayer4x_dout),
    .srcLayer4x_empty_n(srcLayer4x_empty_n),
    .srcLayer4x_read(grp_v_mix_core_alpha_false_false_22_Pipeline_VITIS_LOOP_465_3_fu_142_srcLayer4x_read),
    .srcLayer4x_num_data_valid(3'd0),
    .srcLayer4x_fifo_cap(3'd0),
    .outLayer4_din(grp_v_mix_core_alpha_false_false_22_Pipeline_VITIS_LOOP_465_3_fu_142_outLayer4_din),
    .outLayer4_full_n(outLayer4_full_n),
    .outLayer4_write(grp_v_mix_core_alpha_false_false_22_Pipeline_VITIS_LOOP_465_3_fu_142_outLayer4_write),
    .outLayer4_num_data_valid(outLayer4_num_data_valid),
    .outLayer4_fifo_cap(outLayer4_fifo_cap),
    .div_cast(div_cast_reg_311),
    .div65_cast(div65_cast_reg_321),
    .div72_cast(div72_cast_reg_326),
    .cmp61(cmp61_reg_344),
    .rev5(rev12_reg_339),
    .empty(tmp_4_reg_331)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln463_fu_252_p2 == 1'd1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_v_mix_core_alpha_false_false_22_Pipeline_VITIS_LOOP_465_3_fu_142_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln463_fu_252_p2 == 1'd0))) begin
            grp_v_mix_core_alpha_false_false_22_Pipeline_VITIS_LOOP_465_3_fu_142_ap_start_reg <= 1'b1;
        end else if ((grp_v_mix_core_alpha_false_false_22_Pipeline_VITIS_LOOP_465_3_fu_142_ap_ready == 1'b1)) begin
            grp_v_mix_core_alpha_false_false_22_Pipeline_VITIS_LOOP_465_3_fu_142_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((real_start == 1'b1) & (internal_ap_ready == 1'b0))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        y_fu_90 <= 12'd0;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln463_fu_252_p2 == 1'd0))) begin
        y_fu_90 <= add_ln463_fu_257_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        add60_reg_316 <= add60_fu_196_p2;
        div65_cast_reg_321 <= {{hwReg_layerStartX_4_val_dout[15:1]}};
        div72_cast_reg_326 <= {{add71_fu_220_p2[16:1]}};
        div_cast_reg_311 <= {{hwReg_width_val[11:1]}};
        hwReg_height_val_read_reg_301 <= hwReg_height_val;
        layerStartY_reg_306 <= hwReg_layerStartY_4_val_dout;
        tmp_4_reg_331 <= hwReg_layerEnable_val_dout[32'd4];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        cmp61_reg_344 <= cmp61_fu_283_p2;
        rev12_reg_339 <= rev12_fu_276_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_v_mix_core_alpha_false_false_22_Pipeline_VITIS_LOOP_465_3_fu_142_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln463_fu_252_p2 == 1'd1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        hwReg_layerEnable_val_blk_n = hwReg_layerEnable_val_empty_n;
    end else begin
        hwReg_layerEnable_val_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        hwReg_layerEnable_val_read = 1'b1;
    end else begin
        hwReg_layerEnable_val_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        hwReg_layerHeight_4_val_blk_n = hwReg_layerHeight_4_val_empty_n;
    end else begin
        hwReg_layerHeight_4_val_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        hwReg_layerHeight_4_val_read = 1'b1;
    end else begin
        hwReg_layerHeight_4_val_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        hwReg_layerScaleFactor_4_val_blk_n = hwReg_layerScaleFactor_4_val_empty_n;
    end else begin
        hwReg_layerScaleFactor_4_val_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        hwReg_layerScaleFactor_4_val_read = 1'b1;
    end else begin
        hwReg_layerScaleFactor_4_val_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        hwReg_layerStartX_4_val_blk_n = hwReg_layerStartX_4_val_empty_n;
    end else begin
        hwReg_layerStartX_4_val_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        hwReg_layerStartX_4_val_read = 1'b1;
    end else begin
        hwReg_layerStartX_4_val_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        hwReg_layerStartY_4_val_blk_n = hwReg_layerStartY_4_val_empty_n;
    end else begin
        hwReg_layerStartY_4_val_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        hwReg_layerStartY_4_val_read = 1'b1;
    end else begin
        hwReg_layerStartY_4_val_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        hwReg_layerWidth_4_val_blk_n = hwReg_layerWidth_4_val_empty_n;
    end else begin
        hwReg_layerWidth_4_val_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        hwReg_layerWidth_4_val_read = 1'b1;
    end else begin
        hwReg_layerWidth_4_val_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln463_fu_252_p2 == 1'd1))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((real_start == 1'b1) & (start_once_reg == 1'b0))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln463_fu_252_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_v_mix_core_alpha_false_false_22_Pipeline_VITIS_LOOP_465_3_fu_142_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add60_fu_196_p2 = (layerHeight_cast_fu_192_p1 + hwReg_layerStartY_4_val_cast_fu_188_p1);

assign add71_fu_220_p2 = (layerWidth_cast_fu_216_p1 + hwReg_layerStartX_4_val_cast_fu_202_p1);

assign add_ln463_fu_257_p2 = (y_fu_90 + 12'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (hwReg_layerScaleFactor_4_val_empty_n == 1'b0) | (hwReg_layerHeight_4_val_empty_n == 1'b0) | (hwReg_layerWidth_4_val_empty_n == 1'b0) | (hwReg_layerStartY_4_val_empty_n == 1'b0) | (hwReg_layerStartX_4_val_empty_n == 1'b0) | (hwReg_layerEnable_val_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_ready = internal_ap_ready;

assign cmp61_fu_283_p2 = ((add60_reg_316 > zext_ln463_fu_263_p1) ? 1'b1 : 1'b0);

assign grp_v_mix_core_alpha_false_false_22_Pipeline_VITIS_LOOP_465_3_fu_142_ap_start = grp_v_mix_core_alpha_false_false_22_Pipeline_VITIS_LOOP_465_3_fu_142_ap_start_reg;

assign hwReg_layerScaleFactor_4_val_readcast13_fu_168_p1 = hwReg_layerScaleFactor_4_val_dout;

assign hwReg_layerScaleFactor_4_val_readcast_fu_158_p1 = hwReg_layerScaleFactor_4_val_dout;

assign hwReg_layerStartX_4_val_cast_fu_202_p1 = hwReg_layerStartX_4_val_dout;

assign hwReg_layerStartY_4_val_cast_fu_188_p1 = hwReg_layerStartY_4_val_dout;

assign icmp_ln463_fu_252_p2 = ((y_fu_90 == hwReg_height_val_read_reg_301) ? 1'b1 : 1'b0);

assign layerHeight_cast_fu_192_p1 = shl_ln449_fu_162_p2;

assign layerWidth_cast_fu_216_p1 = shl_ln450_fu_172_p2;

assign outLayer3_read = grp_v_mix_core_alpha_false_false_22_Pipeline_VITIS_LOOP_465_3_fu_142_outLayer3_read;

assign outLayer4_din = grp_v_mix_core_alpha_false_false_22_Pipeline_VITIS_LOOP_465_3_fu_142_outLayer4_din;

assign outLayer4_write = grp_v_mix_core_alpha_false_false_22_Pipeline_VITIS_LOOP_465_3_fu_142_outLayer4_write;

assign rev12_fu_276_p2 = (ult_fu_271_p2 ^ 1'd1);

assign shl_ln449_fu_162_p2 = hwReg_layerHeight_4_val_dout << hwReg_layerScaleFactor_4_val_readcast_fu_158_p1;

assign shl_ln450_fu_172_p2 = hwReg_layerWidth_4_val_dout << hwReg_layerScaleFactor_4_val_readcast13_fu_168_p1;

assign srcLayer4x_read = grp_v_mix_core_alpha_false_false_22_Pipeline_VITIS_LOOP_465_3_fu_142_srcLayer4x_read;

assign start_out = real_start;

assign ult_fu_271_p2 = ((zext_ln463_1_fu_267_p1 < layerStartY_reg_306) ? 1'b1 : 1'b0);

assign zext_ln463_1_fu_267_p1 = y_fu_90;

assign zext_ln463_fu_263_p1 = y_fu_90;

endmodule //bd_quad_vmix_dp_v_mix_0_0_v_mix_core_alpha_false_false_22
