// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module bd_quad_vmix_dp_v_mix_0_0_v_mix_upsample_false_19 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        srcLayer3Rgb_dout,
        srcLayer3Rgb_empty_n,
        srcLayer3Rgb_read,
        srcLayer3Rgb_num_data_valid,
        srcLayer3Rgb_fifo_cap,
        HwReg_layerHeight_3_val_dout,
        HwReg_layerHeight_3_val_empty_n,
        HwReg_layerHeight_3_val_read,
        HwReg_layerHeight_3_val_num_data_valid,
        HwReg_layerHeight_3_val_fifo_cap,
        HwReg_layerWidth_3_val_dout,
        HwReg_layerWidth_3_val_empty_n,
        HwReg_layerWidth_3_val_read,
        HwReg_layerWidth_3_val_num_data_valid,
        HwReg_layerWidth_3_val_fifo_cap,
        HwReg_layerEnableFlag_3_val_dout,
        HwReg_layerEnableFlag_3_val_empty_n,
        HwReg_layerEnableFlag_3_val_read,
        HwReg_layerEnableFlag_3_val_num_data_valid,
        HwReg_layerEnableFlag_3_val_fifo_cap,
        srcLayer3x_din,
        srcLayer3x_full_n,
        srcLayer3x_write,
        srcLayer3x_num_data_valid,
        srcLayer3x_fifo_cap,
        HwReg_layerWidth_3_val_c_din,
        HwReg_layerWidth_3_val_c_full_n,
        HwReg_layerWidth_3_val_c_write,
        HwReg_layerWidth_3_val_c_num_data_valid,
        HwReg_layerWidth_3_val_c_fifo_cap,
        HwReg_layerHeight_3_val_c_din,
        HwReg_layerHeight_3_val_c_full_n,
        HwReg_layerHeight_3_val_c_write,
        HwReg_layerHeight_3_val_c_num_data_valid,
        HwReg_layerHeight_3_val_c_fifo_cap
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [47:0] srcLayer3Rgb_dout;
input   srcLayer3Rgb_empty_n;
output   srcLayer3Rgb_read;
input  [2:0] srcLayer3Rgb_num_data_valid;
input  [2:0] srcLayer3Rgb_fifo_cap;
input  [15:0] HwReg_layerHeight_3_val_dout;
input   HwReg_layerHeight_3_val_empty_n;
output   HwReg_layerHeight_3_val_read;
input  [2:0] HwReg_layerHeight_3_val_num_data_valid;
input  [2:0] HwReg_layerHeight_3_val_fifo_cap;
input  [15:0] HwReg_layerWidth_3_val_dout;
input   HwReg_layerWidth_3_val_empty_n;
output   HwReg_layerWidth_3_val_read;
input  [2:0] HwReg_layerWidth_3_val_num_data_valid;
input  [2:0] HwReg_layerWidth_3_val_fifo_cap;
input  [0:0] HwReg_layerEnableFlag_3_val_dout;
input   HwReg_layerEnableFlag_3_val_empty_n;
output   HwReg_layerEnableFlag_3_val_read;
input  [2:0] HwReg_layerEnableFlag_3_val_num_data_valid;
input  [2:0] HwReg_layerEnableFlag_3_val_fifo_cap;
output  [47:0] srcLayer3x_din;
input   srcLayer3x_full_n;
output   srcLayer3x_write;
input  [31:0] srcLayer3x_num_data_valid;
input  [31:0] srcLayer3x_fifo_cap;
output  [15:0] HwReg_layerWidth_3_val_c_din;
input   HwReg_layerWidth_3_val_c_full_n;
output   HwReg_layerWidth_3_val_c_write;
input  [2:0] HwReg_layerWidth_3_val_c_num_data_valid;
input  [2:0] HwReg_layerWidth_3_val_c_fifo_cap;
output  [15:0] HwReg_layerHeight_3_val_c_din;
input   HwReg_layerHeight_3_val_c_full_n;
output   HwReg_layerHeight_3_val_c_write;
input  [2:0] HwReg_layerHeight_3_val_c_num_data_valid;
input  [2:0] HwReg_layerHeight_3_val_c_fifo_cap;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg HwReg_layerHeight_3_val_read;
reg HwReg_layerWidth_3_val_read;
reg HwReg_layerEnableFlag_3_val_read;
reg HwReg_layerWidth_3_val_c_write;
reg HwReg_layerHeight_3_val_c_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    HwReg_layerHeight_3_val_blk_n;
reg    HwReg_layerWidth_3_val_blk_n;
reg    HwReg_layerEnableFlag_3_val_blk_n;
reg    HwReg_layerWidth_3_val_c_blk_n;
reg    HwReg_layerHeight_3_val_c_blk_n;
wire   [0:0] layerEnableFlag_read_fu_94_p2;
reg   [0:0] layerEnableFlag_reg_147;
reg    ap_block_state1;
wire   [11:0] height_fu_109_p1;
reg   [11:0] height_reg_151;
reg   [10:0] trunc_ln_reg_163;
wire    grp_v_mix_upsample_false_19_Pipeline_VITIS_LOOP_107_2_fu_100_ap_start;
wire    grp_v_mix_upsample_false_19_Pipeline_VITIS_LOOP_107_2_fu_100_ap_done;
wire    grp_v_mix_upsample_false_19_Pipeline_VITIS_LOOP_107_2_fu_100_ap_idle;
wire    grp_v_mix_upsample_false_19_Pipeline_VITIS_LOOP_107_2_fu_100_ap_ready;
wire    grp_v_mix_upsample_false_19_Pipeline_VITIS_LOOP_107_2_fu_100_srcLayer3Rgb_read;
wire   [47:0] grp_v_mix_upsample_false_19_Pipeline_VITIS_LOOP_107_2_fu_100_srcLayer3x_din;
wire    grp_v_mix_upsample_false_19_Pipeline_VITIS_LOOP_107_2_fu_100_srcLayer3x_write;
reg    grp_v_mix_upsample_false_19_Pipeline_VITIS_LOOP_107_2_fu_100_ap_start_reg;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln105_fu_131_p2;
wire    ap_CS_fsm_state3;
reg   [11:0] y_fu_62;
wire   [11:0] y_14_fu_136_p2;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 grp_v_mix_upsample_false_19_Pipeline_VITIS_LOOP_107_2_fu_100_ap_start_reg = 1'b0;
#0 y_fu_62 = 12'd0;
end

bd_quad_vmix_dp_v_mix_0_0_v_mix_upsample_false_19_Pipeline_VITIS_LOOP_107_2 grp_v_mix_upsample_false_19_Pipeline_VITIS_LOOP_107_2_fu_100(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_v_mix_upsample_false_19_Pipeline_VITIS_LOOP_107_2_fu_100_ap_start),
    .ap_done(grp_v_mix_upsample_false_19_Pipeline_VITIS_LOOP_107_2_fu_100_ap_done),
    .ap_idle(grp_v_mix_upsample_false_19_Pipeline_VITIS_LOOP_107_2_fu_100_ap_idle),
    .ap_ready(grp_v_mix_upsample_false_19_Pipeline_VITIS_LOOP_107_2_fu_100_ap_ready),
    .srcLayer3Rgb_dout(srcLayer3Rgb_dout),
    .srcLayer3Rgb_empty_n(srcLayer3Rgb_empty_n),
    .srcLayer3Rgb_read(grp_v_mix_upsample_false_19_Pipeline_VITIS_LOOP_107_2_fu_100_srcLayer3Rgb_read),
    .srcLayer3Rgb_num_data_valid(3'd0),
    .srcLayer3Rgb_fifo_cap(3'd0),
    .srcLayer3x_din(grp_v_mix_upsample_false_19_Pipeline_VITIS_LOOP_107_2_fu_100_srcLayer3x_din),
    .srcLayer3x_full_n(srcLayer3x_full_n),
    .srcLayer3x_write(grp_v_mix_upsample_false_19_Pipeline_VITIS_LOOP_107_2_fu_100_srcLayer3x_write),
    .srcLayer3x_num_data_valid(srcLayer3x_num_data_valid),
    .srcLayer3x_fifo_cap(srcLayer3x_fifo_cap),
    .trunc_ln(trunc_ln_reg_163)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state2) & ((layerEnableFlag_reg_147 == 1'd0) | (icmp_ln105_fu_131_p2 == 1'd1)))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_v_mix_upsample_false_19_Pipeline_VITIS_LOOP_107_2_fu_100_ap_start_reg <= 1'b0;
    end else begin
        if (((layerEnableFlag_reg_147 == 1'd1) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln105_fu_131_p2 == 1'd0))) begin
            grp_v_mix_upsample_false_19_Pipeline_VITIS_LOOP_107_2_fu_100_ap_start_reg <= 1'b1;
        end else if ((grp_v_mix_upsample_false_19_Pipeline_VITIS_LOOP_107_2_fu_100_ap_ready == 1'b1)) begin
            grp_v_mix_upsample_false_19_Pipeline_VITIS_LOOP_107_2_fu_100_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (layerEnableFlag_read_fu_94_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        y_fu_62 <= 12'd0;
    end else if (((layerEnableFlag_reg_147 == 1'd1) & (1'b1 == ap_CS_fsm_state2) & (icmp_ln105_fu_131_p2 == 1'd0))) begin
        y_fu_62 <= y_14_fu_136_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        height_reg_151 <= height_fu_109_p1;
        layerEnableFlag_reg_147 <= HwReg_layerEnableFlag_3_val_dout;
        trunc_ln_reg_163 <= {{HwReg_layerWidth_3_val_dout[11:1]}};
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_layerEnableFlag_3_val_blk_n = HwReg_layerEnableFlag_3_val_empty_n;
    end else begin
        HwReg_layerEnableFlag_3_val_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_layerEnableFlag_3_val_read = 1'b1;
    end else begin
        HwReg_layerEnableFlag_3_val_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_layerHeight_3_val_blk_n = HwReg_layerHeight_3_val_empty_n;
    end else begin
        HwReg_layerHeight_3_val_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_layerHeight_3_val_c_blk_n = HwReg_layerHeight_3_val_c_full_n;
    end else begin
        HwReg_layerHeight_3_val_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_layerHeight_3_val_c_write = 1'b1;
    end else begin
        HwReg_layerHeight_3_val_c_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_layerHeight_3_val_read = 1'b1;
    end else begin
        HwReg_layerHeight_3_val_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_layerWidth_3_val_blk_n = HwReg_layerWidth_3_val_empty_n;
    end else begin
        HwReg_layerWidth_3_val_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_layerWidth_3_val_c_blk_n = HwReg_layerWidth_3_val_c_full_n;
    end else begin
        HwReg_layerWidth_3_val_c_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_layerWidth_3_val_c_write = 1'b1;
    end else begin
        HwReg_layerWidth_3_val_c_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        HwReg_layerWidth_3_val_read = 1'b1;
    end else begin
        HwReg_layerWidth_3_val_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_v_mix_upsample_false_19_Pipeline_VITIS_LOOP_107_2_fu_100_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & ((layerEnableFlag_reg_147 == 1'd0) | (icmp_ln105_fu_131_p2 == 1'd1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & ((layerEnableFlag_reg_147 == 1'd0) | (icmp_ln105_fu_131_p2 == 1'd1)))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & ((layerEnableFlag_reg_147 == 1'd0) | (icmp_ln105_fu_131_p2 == 1'd1)))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_v_mix_upsample_false_19_Pipeline_VITIS_LOOP_107_2_fu_100_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign HwReg_layerHeight_3_val_c_din = HwReg_layerHeight_3_val_dout;

assign HwReg_layerWidth_3_val_c_din = HwReg_layerWidth_3_val_dout;

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (1'b0 == HwReg_layerHeight_3_val_c_full_n) | (1'b0 == HwReg_layerWidth_3_val_c_full_n) | (1'b0 == HwReg_layerEnableFlag_3_val_empty_n) | (1'b0 == HwReg_layerWidth_3_val_empty_n) | (1'b0 == HwReg_layerHeight_3_val_empty_n) | (ap_done_reg == 1'b1));
end

assign grp_v_mix_upsample_false_19_Pipeline_VITIS_LOOP_107_2_fu_100_ap_start = grp_v_mix_upsample_false_19_Pipeline_VITIS_LOOP_107_2_fu_100_ap_start_reg;

assign height_fu_109_p1 = HwReg_layerHeight_3_val_dout[11:0];

assign icmp_ln105_fu_131_p2 = ((y_fu_62 == height_reg_151) ? 1'b1 : 1'b0);

assign layerEnableFlag_read_fu_94_p2 = HwReg_layerEnableFlag_3_val_dout;

assign srcLayer3Rgb_read = grp_v_mix_upsample_false_19_Pipeline_VITIS_LOOP_107_2_fu_100_srcLayer3Rgb_read;

assign srcLayer3x_din = grp_v_mix_upsample_false_19_Pipeline_VITIS_LOOP_107_2_fu_100_srcLayer3x_din;

assign srcLayer3x_write = grp_v_mix_upsample_false_19_Pipeline_VITIS_LOOP_107_2_fu_100_srcLayer3x_write;

assign y_14_fu_136_p2 = (y_fu_62 + 12'd1);

endmodule //bd_quad_vmix_dp_v_mix_0_0_v_mix_upsample_false_19
