// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="bd_quad_vmix_dp_v_mix_0_0_v_mix,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=6.667000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.530000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=15546,HLS_SYN_LUT=18987,HLS_VERSION=2024_2}" *)

module bd_quad_vmix_dp_v_mix_0_0_v_mix (
        ap_clk,
        ap_rst_n,
        s_axis_video_TDATA,
        s_axis_video_TVALID,
        s_axis_video_TREADY,
        s_axis_video_TKEEP,
        s_axis_video_TSTRB,
        s_axis_video_TUSER,
        s_axis_video_TLAST,
        s_axis_video_TID,
        s_axis_video_TDEST,
        s_axis_video1_TDATA,
        s_axis_video1_TVALID,
        s_axis_video1_TREADY,
        s_axis_video1_TKEEP,
        s_axis_video1_TSTRB,
        s_axis_video1_TUSER,
        s_axis_video1_TLAST,
        s_axis_video1_TID,
        s_axis_video1_TDEST,
        s_axis_video2_TDATA,
        s_axis_video2_TVALID,
        s_axis_video2_TREADY,
        s_axis_video2_TKEEP,
        s_axis_video2_TSTRB,
        s_axis_video2_TUSER,
        s_axis_video2_TLAST,
        s_axis_video2_TID,
        s_axis_video2_TDEST,
        s_axis_video3_TDATA,
        s_axis_video3_TVALID,
        s_axis_video3_TREADY,
        s_axis_video3_TKEEP,
        s_axis_video3_TSTRB,
        s_axis_video3_TUSER,
        s_axis_video3_TLAST,
        s_axis_video3_TID,
        s_axis_video3_TDEST,
        s_axis_video4_TDATA,
        s_axis_video4_TVALID,
        s_axis_video4_TREADY,
        s_axis_video4_TKEEP,
        s_axis_video4_TSTRB,
        s_axis_video4_TUSER,
        s_axis_video4_TLAST,
        s_axis_video4_TID,
        s_axis_video4_TDEST,
        layerAlpha_0,
        layerStartX_0,
        layerStartY_0,
        layerWidth_0,
        layerHeight_0,
        layerScaleFactor_0,
        layerVideoFormat_address0,
        layerVideoFormat_ce0,
        layerVideoFormat_we0,
        layerVideoFormat_d0,
        layerVideoFormat_q0,
        layerVideoFormat_address1,
        layerVideoFormat_ce1,
        layerVideoFormat_we1,
        layerVideoFormat_d1,
        layerVideoFormat_q1,
        layerStride_0,
        K11,
        K12,
        K13,
        K21,
        K22,
        K23,
        K31,
        K32,
        K33,
        ROffset,
        GOffset,
        BOffset,
        K11_2,
        K12_2,
        K13_2,
        K21_2,
        K22_2,
        K23_2,
        K31_2,
        K32_2,
        K33_2,
        YOffset,
        UOffset,
        VOffset,
        m_axis_video_TDATA,
        m_axis_video_TVALID,
        m_axis_video_TREADY,
        m_axis_video_TKEEP,
        m_axis_video_TSTRB,
        m_axis_video_TUSER,
        m_axis_video_TLAST,
        m_axis_video_TID,
        m_axis_video_TDEST,
        s_axi_CTRL_AWVALID,
        s_axi_CTRL_AWREADY,
        s_axi_CTRL_AWADDR,
        s_axi_CTRL_WVALID,
        s_axi_CTRL_WREADY,
        s_axi_CTRL_WDATA,
        s_axi_CTRL_WSTRB,
        s_axi_CTRL_ARVALID,
        s_axi_CTRL_ARREADY,
        s_axi_CTRL_ARADDR,
        s_axi_CTRL_RVALID,
        s_axi_CTRL_RREADY,
        s_axi_CTRL_RDATA,
        s_axi_CTRL_RRESP,
        s_axi_CTRL_BVALID,
        s_axi_CTRL_BREADY,
        s_axi_CTRL_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;
parameter    C_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_ADDR_WIDTH = 12;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [47:0] s_axis_video_TDATA;
input   s_axis_video_TVALID;
output   s_axis_video_TREADY;
input  [5:0] s_axis_video_TKEEP;
input  [5:0] s_axis_video_TSTRB;
input  [0:0] s_axis_video_TUSER;
input  [0:0] s_axis_video_TLAST;
input  [0:0] s_axis_video_TID;
input  [0:0] s_axis_video_TDEST;
input  [47:0] s_axis_video1_TDATA;
input   s_axis_video1_TVALID;
output   s_axis_video1_TREADY;
input  [5:0] s_axis_video1_TKEEP;
input  [5:0] s_axis_video1_TSTRB;
input  [0:0] s_axis_video1_TUSER;
input  [0:0] s_axis_video1_TLAST;
input  [0:0] s_axis_video1_TID;
input  [0:0] s_axis_video1_TDEST;
input  [47:0] s_axis_video2_TDATA;
input   s_axis_video2_TVALID;
output   s_axis_video2_TREADY;
input  [5:0] s_axis_video2_TKEEP;
input  [5:0] s_axis_video2_TSTRB;
input  [0:0] s_axis_video2_TUSER;
input  [0:0] s_axis_video2_TLAST;
input  [0:0] s_axis_video2_TID;
input  [0:0] s_axis_video2_TDEST;
input  [47:0] s_axis_video3_TDATA;
input   s_axis_video3_TVALID;
output   s_axis_video3_TREADY;
input  [5:0] s_axis_video3_TKEEP;
input  [5:0] s_axis_video3_TSTRB;
input  [0:0] s_axis_video3_TUSER;
input  [0:0] s_axis_video3_TLAST;
input  [0:0] s_axis_video3_TID;
input  [0:0] s_axis_video3_TDEST;
input  [47:0] s_axis_video4_TDATA;
input   s_axis_video4_TVALID;
output   s_axis_video4_TREADY;
input  [5:0] s_axis_video4_TKEEP;
input  [5:0] s_axis_video4_TSTRB;
input  [0:0] s_axis_video4_TUSER;
input  [0:0] s_axis_video4_TLAST;
input  [0:0] s_axis_video4_TID;
input  [0:0] s_axis_video4_TDEST;
input  [15:0] layerAlpha_0;
input  [15:0] layerStartX_0;
input  [15:0] layerStartY_0;
input  [15:0] layerWidth_0;
input  [15:0] layerHeight_0;
input  [7:0] layerScaleFactor_0;
output  [2:0] layerVideoFormat_address0;
output   layerVideoFormat_ce0;
output   layerVideoFormat_we0;
output  [7:0] layerVideoFormat_d0;
input  [7:0] layerVideoFormat_q0;
output  [2:0] layerVideoFormat_address1;
output   layerVideoFormat_ce1;
output   layerVideoFormat_we1;
output  [7:0] layerVideoFormat_d1;
input  [7:0] layerVideoFormat_q1;
input  [15:0] layerStride_0;
input  [31:0] K11;
input  [31:0] K12;
input  [31:0] K13;
input  [31:0] K21;
input  [31:0] K22;
input  [31:0] K23;
input  [31:0] K31;
input  [31:0] K32;
input  [31:0] K33;
input  [31:0] ROffset;
input  [31:0] GOffset;
input  [31:0] BOffset;
input  [31:0] K11_2;
input  [31:0] K12_2;
input  [31:0] K13_2;
input  [31:0] K21_2;
input  [31:0] K22_2;
input  [31:0] K23_2;
input  [31:0] K31_2;
input  [31:0] K32_2;
input  [31:0] K33_2;
input  [31:0] YOffset;
input  [31:0] UOffset;
input  [31:0] VOffset;
output  [47:0] m_axis_video_TDATA;
output   m_axis_video_TVALID;
input   m_axis_video_TREADY;
output  [5:0] m_axis_video_TKEEP;
output  [5:0] m_axis_video_TSTRB;
output  [0:0] m_axis_video_TUSER;
output  [0:0] m_axis_video_TLAST;
output  [0:0] m_axis_video_TID;
output  [0:0] m_axis_video_TDEST;
input   s_axi_CTRL_AWVALID;
output   s_axi_CTRL_AWREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_AWADDR;
input   s_axi_CTRL_WVALID;
output   s_axi_CTRL_WREADY;
input  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_WDATA;
input  [C_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_CTRL_WSTRB;
input   s_axi_CTRL_ARVALID;
output   s_axi_CTRL_ARREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_ARADDR;
output   s_axi_CTRL_RVALID;
input   s_axi_CTRL_RREADY;
output  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_RDATA;
output  [1:0] s_axi_CTRL_RRESP;
output   s_axi_CTRL_BVALID;
input   s_axi_CTRL_BREADY;
output  [1:0] s_axi_CTRL_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [15:0] width;
wire   [15:0] height;
wire   [15:0] video_format;
wire   [15:0] background_Y_R;
wire   [15:0] background_U_G;
wire   [15:0] background_V_B;
wire   [31:0] layerEnable;
wire   [15:0] layerAlpha_1;
wire   [15:0] layerAlpha_2;
wire   [15:0] layerAlpha_3;
wire   [15:0] layerAlpha_4;
wire   [15:0] layerStartX_1;
wire   [15:0] layerStartX_2;
wire   [15:0] layerStartX_3;
wire   [15:0] layerStartX_4;
wire   [15:0] layerStartY_1;
wire   [15:0] layerStartY_2;
wire   [15:0] layerStartY_3;
wire   [15:0] layerStartY_4;
wire   [15:0] layerWidth_1;
wire   [15:0] layerWidth_2;
wire   [15:0] layerWidth_3;
wire   [15:0] layerWidth_4;
wire   [15:0] layerHeight_1;
wire   [15:0] layerHeight_2;
wire   [15:0] layerHeight_3;
wire   [15:0] layerHeight_4;
wire   [7:0] layerScaleFactor_1;
wire   [7:0] layerScaleFactor_2;
wire   [7:0] layerScaleFactor_3;
wire   [7:0] layerScaleFactor_4;
wire   [15:0] layerStride_1;
wire   [15:0] layerStride_2;
wire   [15:0] layerStride_3;
wire   [15:0] layerStride_4;
wire   [15:0] reserve;
reg   [31:0] layerEnable_read_reg_1569;
wire   [4:0] trunc_ln1812_fu_795_p1;
reg   [4:0] trunc_ln1812_reg_1574;
wire   [7:0] trunc_ln1812_1_fu_799_p1;
reg   [7:0] trunc_ln1812_1_reg_1579;
wire   [7:0] trunc_ln1812_2_fu_803_p1;
reg   [7:0] trunc_ln1812_2_reg_1584;
wire   [7:0] trunc_ln1812_3_fu_807_p1;
reg   [7:0] trunc_ln1812_3_reg_1589;
wire   [11:0] trunc_ln1812_4_fu_811_p1;
reg   [11:0] trunc_ln1812_4_reg_1594;
wire   [11:0] trunc_ln1812_5_fu_815_p1;
reg   [11:0] trunc_ln1812_5_reg_1599;
reg   [15:0] layerStartX_0_read_reg_1604;
reg   [15:0] layerStartX_1_read_reg_1609;
reg   [15:0] layerStartX_2_read_reg_1614;
reg   [15:0] layerStartX_3_read_reg_1619;
reg   [15:0] layerStartX_4_read_reg_1624;
reg   [15:0] layerStartY_0_read_reg_1629;
reg   [15:0] layerStartY_1_read_reg_1634;
reg   [15:0] layerStartY_2_read_reg_1639;
reg   [15:0] layerStartY_3_read_reg_1644;
reg   [15:0] layerStartY_4_read_reg_1649;
reg   [15:0] layerWidth_0_read_reg_1654;
reg   [15:0] layerWidth_1_read_reg_1659;
reg   [15:0] layerWidth_2_read_reg_1664;
reg   [15:0] layerWidth_3_read_reg_1669;
reg   [15:0] layerWidth_4_read_reg_1674;
reg   [15:0] layerHeight_0_read_reg_1679;
reg   [15:0] layerHeight_1_read_reg_1684;
reg   [15:0] layerHeight_2_read_reg_1689;
reg   [15:0] layerHeight_3_read_reg_1694;
reg   [15:0] layerHeight_4_read_reg_1699;
reg   [7:0] layerScaleFactor_0_read_reg_1704;
reg   [7:0] layerScaleFactor_1_read_reg_1709;
reg   [7:0] layerScaleFactor_2_read_reg_1714;
reg   [7:0] layerScaleFactor_3_read_reg_1719;
reg   [7:0] layerScaleFactor_4_read_reg_1724;
wire   [0:0] HwReg_layerEnableFlag_4_fu_1070_p3;
reg   [0:0] HwReg_layerEnableFlag_4_reg_1729;
wire    ap_CS_fsm_state2;
wire   [15:0] HwReg_layerHeight_3_fu_1078_p3;
reg   [15:0] HwReg_layerHeight_3_reg_1734;
wire   [15:0] HwReg_layerWidth_3_fu_1086_p3;
reg   [15:0] HwReg_layerWidth_3_reg_1739;
wire   [0:0] HwReg_layerEnableFlag_3_fu_1094_p3;
reg   [0:0] HwReg_layerEnableFlag_3_reg_1744;
wire   [0:0] HwReg_layerEnableFlag_2_fu_1102_p3;
reg   [0:0] HwReg_layerEnableFlag_2_reg_1749;
wire   [15:0] HwReg_layerHeight_2_fu_1110_p3;
reg   [15:0] HwReg_layerHeight_2_reg_1754;
wire   [15:0] HwReg_layerWidth_2_fu_1118_p3;
reg   [15:0] HwReg_layerWidth_2_reg_1759;
wire   [0:0] HwReg_layerEnableFlag_1_fu_1126_p3;
reg   [0:0] HwReg_layerEnableFlag_1_reg_1764;
wire   [15:0] HwReg_layerHeight_1_fu_1134_p3;
reg   [15:0] HwReg_layerHeight_1_reg_1769;
wire   [15:0] HwReg_layerWidth_1_fu_1142_p3;
reg   [15:0] HwReg_layerWidth_1_reg_1774;
wire   [0:0] HwReg_layerEnableFlag_fu_1150_p3;
reg   [0:0] HwReg_layerEnableFlag_reg_1779;
wire   [15:0] HwReg_layerHeight_fu_1158_p3;
reg   [15:0] HwReg_layerHeight_reg_1784;
wire   [15:0] HwReg_layerWidth_fu_1166_p3;
reg   [15:0] HwReg_layerWidth_reg_1789;
wire   [7:0] HwReg_layerScaleFactor_3_fu_1174_p3;
reg   [7:0] HwReg_layerScaleFactor_3_reg_1794;
wire   [15:0] HwReg_layerStartY_3_fu_1182_p3;
reg   [15:0] HwReg_layerStartY_3_reg_1799;
wire   [15:0] HwReg_layerStartX_3_fu_1190_p3;
reg   [15:0] HwReg_layerStartX_3_reg_1804;
wire   [7:0] HwReg_layerScaleFactor_2_fu_1198_p3;
reg   [7:0] HwReg_layerScaleFactor_2_reg_1809;
wire   [15:0] HwReg_layerStartY_2_fu_1206_p3;
reg   [15:0] HwReg_layerStartY_2_reg_1814;
wire   [15:0] HwReg_layerStartX_2_fu_1214_p3;
reg   [15:0] HwReg_layerStartX_2_reg_1819;
wire   [7:0] HwReg_layerScaleFactor_1_fu_1222_p3;
reg   [7:0] HwReg_layerScaleFactor_1_reg_1824;
wire   [15:0] HwReg_layerStartY_1_fu_1230_p3;
reg   [15:0] HwReg_layerStartY_1_reg_1829;
wire   [15:0] HwReg_layerStartX_1_fu_1238_p3;
reg   [15:0] HwReg_layerStartX_1_reg_1834;
wire   [7:0] HwReg_layerScaleFactor_fu_1246_p3;
reg   [7:0] HwReg_layerScaleFactor_reg_1839;
wire   [15:0] HwReg_layerStartY_fu_1254_p3;
reg   [15:0] HwReg_layerStartY_reg_1844;
wire   [15:0] HwReg_layerStartX_fu_1262_p3;
reg   [15:0] HwReg_layerStartX_reg_1849;
wire   [47:0] grp_VMixHlsDataFlowFunction_fu_676_m_axis_video_TDATA;
wire   [5:0] grp_VMixHlsDataFlowFunction_fu_676_m_axis_video_TKEEP;
wire   [5:0] grp_VMixHlsDataFlowFunction_fu_676_m_axis_video_TSTRB;
wire   [0:0] grp_VMixHlsDataFlowFunction_fu_676_m_axis_video_TUSER;
wire   [0:0] grp_VMixHlsDataFlowFunction_fu_676_m_axis_video_TLAST;
wire   [0:0] grp_VMixHlsDataFlowFunction_fu_676_m_axis_video_TID;
wire   [0:0] grp_VMixHlsDataFlowFunction_fu_676_m_axis_video_TDEST;
wire    grp_VMixHlsDataFlowFunction_fu_676_ap_start;
wire    grp_VMixHlsDataFlowFunction_fu_676_s_axis_video_TREADY;
wire    grp_VMixHlsDataFlowFunction_fu_676_s_axis_video1_TREADY;
wire    grp_VMixHlsDataFlowFunction_fu_676_s_axis_video2_TREADY;
wire    grp_VMixHlsDataFlowFunction_fu_676_s_axis_video3_TREADY;
wire    grp_VMixHlsDataFlowFunction_fu_676_s_axis_video4_TREADY;
wire    grp_VMixHlsDataFlowFunction_fu_676_m_axis_video_TVALID;
wire    grp_VMixHlsDataFlowFunction_fu_676_m_axis_video_TREADY;
wire    grp_VMixHlsDataFlowFunction_fu_676_ap_done;
wire    grp_VMixHlsDataFlowFunction_fu_676_ap_ready;
wire    grp_VMixHlsDataFlowFunction_fu_676_ap_idle;
reg    grp_VMixHlsDataFlowFunction_fu_676_ap_continue;
reg    grp_VMixHlsDataFlowFunction_fu_676_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
reg    ap_sync_reg_grp_VMixHlsDataFlowFunction_fu_676_ap_ready;
reg    ap_sync_reg_grp_VMixHlsDataFlowFunction_fu_676_ap_done;
reg    ap_block_state4_on_subcall_done;
wire    ap_sync_grp_VMixHlsDataFlowFunction_fu_676_ap_ready;
reg   [47:0] m_axis_video_TDATA_reg;
reg   [5:0] m_axis_video_TKEEP_reg;
reg   [5:0] m_axis_video_TSTRB_reg;
reg   [0:0] m_axis_video_TUSER_reg;
reg   [0:0] m_axis_video_TLAST_reg;
reg   [0:0] m_axis_video_TID_reg;
reg   [0:0] m_axis_video_TDEST_reg;
reg   [0:0] HwReg_layerEnableFlag_5_fu_386;
reg   [0:0] HwReg_layerEnableFlag_6_fu_390;
reg   [0:0] HwReg_layerEnableFlag_7_fu_394;
reg   [0:0] HwReg_layerEnableFlag_8_fu_398;
reg   [0:0] HwReg_layerEnableFlag_9_fu_402;
reg   [15:0] empty_fu_406;
reg   [15:0] empty_93_fu_410;
reg   [15:0] empty_94_fu_414;
reg   [15:0] empty_95_fu_418;
reg   [15:0] empty_96_fu_422;
reg   [15:0] empty_97_fu_426;
reg   [15:0] empty_98_fu_430;
reg   [15:0] empty_99_fu_434;
reg   [7:0] empty_100_fu_438;
reg   [15:0] empty_101_fu_442;
reg   [15:0] empty_102_fu_446;
reg   [7:0] empty_103_fu_450;
reg   [15:0] empty_104_fu_454;
reg   [15:0] empty_105_fu_458;
reg   [7:0] empty_106_fu_462;
reg   [15:0] empty_107_fu_466;
reg   [15:0] empty_108_fu_470;
reg   [7:0] empty_109_fu_474;
reg   [15:0] empty_110_fu_478;
reg   [15:0] empty_111_fu_482;
reg   [2:0] i11_fu_486;
wire   [2:0] i_fu_1270_p2;
wire   [15:0] HwReg_layerStartX_4_fu_902_p11;
wire   [15:0] HwReg_layerStartY_4_fu_925_p11;
wire   [15:0] tmp_s_fu_948_p11;
wire   [15:0] tmp_4_fu_971_p11;
wire   [7:0] HwReg_layerScaleFactor_4_fu_994_p11;
wire   [31:0] tobool_fu_1021_p2;
wire   [0:0] icmp_ln2629_1_fu_1034_p2;
wire   [0:0] icmp_ln2629_2_fu_1040_p2;
wire   [0:0] icmp_ln2629_fu_1028_p2;
wire   [0:0] icmp_ln2629_3_fu_1046_p2;
wire   [0:0] or_ln2629_1_fu_1058_p2;
wire   [0:0] or_ln2629_fu_1052_p2;
wire   [0:0] or_ln2629_2_fu_1064_p2;
wire   [0:0] tobool_fu_1021_p3;
wire   [15:0] tmp_4_fu_971_p13;
wire   [15:0] tmp_s_fu_948_p13;
wire   [7:0] HwReg_layerScaleFactor_4_fu_994_p13;
wire   [15:0] HwReg_layerStartY_4_fu_925_p13;
wire   [15:0] HwReg_layerStartX_4_fu_902_p13;
wire   [0:0] icmp_ln2626_fu_1276_p2;
wire    ap_CS_fsm_state5;
wire    regslice_both_m_axis_video_V_data_V_U_apdone_blk;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    regslice_both_s_axis_video_V_data_V_U_apdone_blk;
wire   [47:0] s_axis_video_TDATA_int_regslice;
wire    s_axis_video_TVALID_int_regslice;
reg    s_axis_video_TREADY_int_regslice;
wire    regslice_both_s_axis_video_V_data_V_U_ack_in;
wire    regslice_both_s_axis_video_V_keep_V_U_apdone_blk;
wire   [5:0] s_axis_video_TKEEP_int_regslice;
wire    regslice_both_s_axis_video_V_keep_V_U_vld_out;
wire    regslice_both_s_axis_video_V_keep_V_U_ack_in;
wire    regslice_both_s_axis_video_V_strb_V_U_apdone_blk;
wire   [5:0] s_axis_video_TSTRB_int_regslice;
wire    regslice_both_s_axis_video_V_strb_V_U_vld_out;
wire    regslice_both_s_axis_video_V_strb_V_U_ack_in;
wire    regslice_both_s_axis_video_V_user_V_U_apdone_blk;
wire   [0:0] s_axis_video_TUSER_int_regslice;
wire    regslice_both_s_axis_video_V_user_V_U_vld_out;
wire    regslice_both_s_axis_video_V_user_V_U_ack_in;
wire    regslice_both_s_axis_video_V_last_V_U_apdone_blk;
wire   [0:0] s_axis_video_TLAST_int_regslice;
wire    regslice_both_s_axis_video_V_last_V_U_vld_out;
wire    regslice_both_s_axis_video_V_last_V_U_ack_in;
wire    regslice_both_s_axis_video_V_id_V_U_apdone_blk;
wire   [0:0] s_axis_video_TID_int_regslice;
wire    regslice_both_s_axis_video_V_id_V_U_vld_out;
wire    regslice_both_s_axis_video_V_id_V_U_ack_in;
wire    regslice_both_s_axis_video_V_dest_V_U_apdone_blk;
wire   [0:0] s_axis_video_TDEST_int_regslice;
wire    regslice_both_s_axis_video_V_dest_V_U_vld_out;
wire    regslice_both_s_axis_video_V_dest_V_U_ack_in;
wire    regslice_both_s_axis_video1_V_data_V_U_apdone_blk;
wire   [47:0] s_axis_video1_TDATA_int_regslice;
wire    s_axis_video1_TVALID_int_regslice;
reg    s_axis_video1_TREADY_int_regslice;
wire    regslice_both_s_axis_video1_V_data_V_U_ack_in;
wire    regslice_both_s_axis_video1_V_keep_V_U_apdone_blk;
wire   [5:0] s_axis_video1_TKEEP_int_regslice;
wire    regslice_both_s_axis_video1_V_keep_V_U_vld_out;
wire    regslice_both_s_axis_video1_V_keep_V_U_ack_in;
wire    regslice_both_s_axis_video1_V_strb_V_U_apdone_blk;
wire   [5:0] s_axis_video1_TSTRB_int_regslice;
wire    regslice_both_s_axis_video1_V_strb_V_U_vld_out;
wire    regslice_both_s_axis_video1_V_strb_V_U_ack_in;
wire    regslice_both_s_axis_video1_V_user_V_U_apdone_blk;
wire   [0:0] s_axis_video1_TUSER_int_regslice;
wire    regslice_both_s_axis_video1_V_user_V_U_vld_out;
wire    regslice_both_s_axis_video1_V_user_V_U_ack_in;
wire    regslice_both_s_axis_video1_V_last_V_U_apdone_blk;
wire   [0:0] s_axis_video1_TLAST_int_regslice;
wire    regslice_both_s_axis_video1_V_last_V_U_vld_out;
wire    regslice_both_s_axis_video1_V_last_V_U_ack_in;
wire    regslice_both_s_axis_video1_V_id_V_U_apdone_blk;
wire   [0:0] s_axis_video1_TID_int_regslice;
wire    regslice_both_s_axis_video1_V_id_V_U_vld_out;
wire    regslice_both_s_axis_video1_V_id_V_U_ack_in;
wire    regslice_both_s_axis_video1_V_dest_V_U_apdone_blk;
wire   [0:0] s_axis_video1_TDEST_int_regslice;
wire    regslice_both_s_axis_video1_V_dest_V_U_vld_out;
wire    regslice_both_s_axis_video1_V_dest_V_U_ack_in;
wire    regslice_both_s_axis_video2_V_data_V_U_apdone_blk;
wire   [47:0] s_axis_video2_TDATA_int_regslice;
wire    s_axis_video2_TVALID_int_regslice;
reg    s_axis_video2_TREADY_int_regslice;
wire    regslice_both_s_axis_video2_V_data_V_U_ack_in;
wire    regslice_both_s_axis_video2_V_keep_V_U_apdone_blk;
wire   [5:0] s_axis_video2_TKEEP_int_regslice;
wire    regslice_both_s_axis_video2_V_keep_V_U_vld_out;
wire    regslice_both_s_axis_video2_V_keep_V_U_ack_in;
wire    regslice_both_s_axis_video2_V_strb_V_U_apdone_blk;
wire   [5:0] s_axis_video2_TSTRB_int_regslice;
wire    regslice_both_s_axis_video2_V_strb_V_U_vld_out;
wire    regslice_both_s_axis_video2_V_strb_V_U_ack_in;
wire    regslice_both_s_axis_video2_V_user_V_U_apdone_blk;
wire   [0:0] s_axis_video2_TUSER_int_regslice;
wire    regslice_both_s_axis_video2_V_user_V_U_vld_out;
wire    regslice_both_s_axis_video2_V_user_V_U_ack_in;
wire    regslice_both_s_axis_video2_V_last_V_U_apdone_blk;
wire   [0:0] s_axis_video2_TLAST_int_regslice;
wire    regslice_both_s_axis_video2_V_last_V_U_vld_out;
wire    regslice_both_s_axis_video2_V_last_V_U_ack_in;
wire    regslice_both_s_axis_video2_V_id_V_U_apdone_blk;
wire   [0:0] s_axis_video2_TID_int_regslice;
wire    regslice_both_s_axis_video2_V_id_V_U_vld_out;
wire    regslice_both_s_axis_video2_V_id_V_U_ack_in;
wire    regslice_both_s_axis_video2_V_dest_V_U_apdone_blk;
wire   [0:0] s_axis_video2_TDEST_int_regslice;
wire    regslice_both_s_axis_video2_V_dest_V_U_vld_out;
wire    regslice_both_s_axis_video2_V_dest_V_U_ack_in;
wire    regslice_both_s_axis_video3_V_data_V_U_apdone_blk;
wire   [47:0] s_axis_video3_TDATA_int_regslice;
wire    s_axis_video3_TVALID_int_regslice;
reg    s_axis_video3_TREADY_int_regslice;
wire    regslice_both_s_axis_video3_V_data_V_U_ack_in;
wire    regslice_both_s_axis_video3_V_keep_V_U_apdone_blk;
wire   [5:0] s_axis_video3_TKEEP_int_regslice;
wire    regslice_both_s_axis_video3_V_keep_V_U_vld_out;
wire    regslice_both_s_axis_video3_V_keep_V_U_ack_in;
wire    regslice_both_s_axis_video3_V_strb_V_U_apdone_blk;
wire   [5:0] s_axis_video3_TSTRB_int_regslice;
wire    regslice_both_s_axis_video3_V_strb_V_U_vld_out;
wire    regslice_both_s_axis_video3_V_strb_V_U_ack_in;
wire    regslice_both_s_axis_video3_V_user_V_U_apdone_blk;
wire   [0:0] s_axis_video3_TUSER_int_regslice;
wire    regslice_both_s_axis_video3_V_user_V_U_vld_out;
wire    regslice_both_s_axis_video3_V_user_V_U_ack_in;
wire    regslice_both_s_axis_video3_V_last_V_U_apdone_blk;
wire   [0:0] s_axis_video3_TLAST_int_regslice;
wire    regslice_both_s_axis_video3_V_last_V_U_vld_out;
wire    regslice_both_s_axis_video3_V_last_V_U_ack_in;
wire    regslice_both_s_axis_video3_V_id_V_U_apdone_blk;
wire   [0:0] s_axis_video3_TID_int_regslice;
wire    regslice_both_s_axis_video3_V_id_V_U_vld_out;
wire    regslice_both_s_axis_video3_V_id_V_U_ack_in;
wire    regslice_both_s_axis_video3_V_dest_V_U_apdone_blk;
wire   [0:0] s_axis_video3_TDEST_int_regslice;
wire    regslice_both_s_axis_video3_V_dest_V_U_vld_out;
wire    regslice_both_s_axis_video3_V_dest_V_U_ack_in;
wire    regslice_both_s_axis_video4_V_data_V_U_apdone_blk;
wire   [47:0] s_axis_video4_TDATA_int_regslice;
wire    s_axis_video4_TVALID_int_regslice;
reg    s_axis_video4_TREADY_int_regslice;
wire    regslice_both_s_axis_video4_V_data_V_U_ack_in;
wire    regslice_both_s_axis_video4_V_keep_V_U_apdone_blk;
wire   [5:0] s_axis_video4_TKEEP_int_regslice;
wire    regslice_both_s_axis_video4_V_keep_V_U_vld_out;
wire    regslice_both_s_axis_video4_V_keep_V_U_ack_in;
wire    regslice_both_s_axis_video4_V_strb_V_U_apdone_blk;
wire   [5:0] s_axis_video4_TSTRB_int_regslice;
wire    regslice_both_s_axis_video4_V_strb_V_U_vld_out;
wire    regslice_both_s_axis_video4_V_strb_V_U_ack_in;
wire    regslice_both_s_axis_video4_V_user_V_U_apdone_blk;
wire   [0:0] s_axis_video4_TUSER_int_regslice;
wire    regslice_both_s_axis_video4_V_user_V_U_vld_out;
wire    regslice_both_s_axis_video4_V_user_V_U_ack_in;
wire    regslice_both_s_axis_video4_V_last_V_U_apdone_blk;
wire   [0:0] s_axis_video4_TLAST_int_regslice;
wire    regslice_both_s_axis_video4_V_last_V_U_vld_out;
wire    regslice_both_s_axis_video4_V_last_V_U_ack_in;
wire    regslice_both_s_axis_video4_V_id_V_U_apdone_blk;
wire   [0:0] s_axis_video4_TID_int_regslice;
wire    regslice_both_s_axis_video4_V_id_V_U_vld_out;
wire    regslice_both_s_axis_video4_V_id_V_U_ack_in;
wire    regslice_both_s_axis_video4_V_dest_V_U_apdone_blk;
wire   [0:0] s_axis_video4_TDEST_int_regslice;
wire    regslice_both_s_axis_video4_V_dest_V_U_vld_out;
wire    regslice_both_s_axis_video4_V_dest_V_U_ack_in;
reg   [47:0] m_axis_video_TDATA_int_regslice;
wire    m_axis_video_TVALID_int_regslice;
wire    m_axis_video_TREADY_int_regslice;
wire    regslice_both_m_axis_video_V_data_V_U_vld_out;
wire    regslice_both_m_axis_video_V_keep_V_U_apdone_blk;
reg   [5:0] m_axis_video_TKEEP_int_regslice;
wire    regslice_both_m_axis_video_V_keep_V_U_ack_in_dummy;
wire    regslice_both_m_axis_video_V_keep_V_U_vld_out;
wire    regslice_both_m_axis_video_V_strb_V_U_apdone_blk;
reg   [5:0] m_axis_video_TSTRB_int_regslice;
wire    regslice_both_m_axis_video_V_strb_V_U_ack_in_dummy;
wire    regslice_both_m_axis_video_V_strb_V_U_vld_out;
wire    regslice_both_m_axis_video_V_user_V_U_apdone_blk;
reg   [0:0] m_axis_video_TUSER_int_regslice;
wire    regslice_both_m_axis_video_V_user_V_U_ack_in_dummy;
wire    regslice_both_m_axis_video_V_user_V_U_vld_out;
wire    regslice_both_m_axis_video_V_last_V_U_apdone_blk;
reg   [0:0] m_axis_video_TLAST_int_regslice;
wire    regslice_both_m_axis_video_V_last_V_U_ack_in_dummy;
wire    regslice_both_m_axis_video_V_last_V_U_vld_out;
wire    regslice_both_m_axis_video_V_id_V_U_apdone_blk;
reg   [0:0] m_axis_video_TID_int_regslice;
wire    regslice_both_m_axis_video_V_id_V_U_ack_in_dummy;
wire    regslice_both_m_axis_video_V_id_V_U_vld_out;
wire    regslice_both_m_axis_video_V_dest_V_U_apdone_blk;
reg   [0:0] m_axis_video_TDEST_int_regslice;
wire    regslice_both_m_axis_video_V_dest_V_U_ack_in_dummy;
wire    regslice_both_m_axis_video_V_dest_V_U_vld_out;
wire   [2:0] HwReg_layerStartX_4_fu_902_p1;
wire   [2:0] HwReg_layerStartX_4_fu_902_p3;
wire   [2:0] HwReg_layerStartX_4_fu_902_p5;
wire   [2:0] HwReg_layerStartX_4_fu_902_p7;
wire  signed [2:0] HwReg_layerStartX_4_fu_902_p9;
wire   [2:0] HwReg_layerStartY_4_fu_925_p1;
wire   [2:0] HwReg_layerStartY_4_fu_925_p3;
wire   [2:0] HwReg_layerStartY_4_fu_925_p5;
wire   [2:0] HwReg_layerStartY_4_fu_925_p7;
wire  signed [2:0] HwReg_layerStartY_4_fu_925_p9;
wire   [2:0] tmp_s_fu_948_p1;
wire   [2:0] tmp_s_fu_948_p3;
wire   [2:0] tmp_s_fu_948_p5;
wire   [2:0] tmp_s_fu_948_p7;
wire  signed [2:0] tmp_s_fu_948_p9;
wire   [2:0] tmp_4_fu_971_p1;
wire   [2:0] tmp_4_fu_971_p3;
wire   [2:0] tmp_4_fu_971_p5;
wire   [2:0] tmp_4_fu_971_p7;
wire  signed [2:0] tmp_4_fu_971_p9;
wire   [2:0] HwReg_layerScaleFactor_4_fu_994_p1;
wire   [2:0] HwReg_layerScaleFactor_4_fu_994_p3;
wire   [2:0] HwReg_layerScaleFactor_4_fu_994_p5;
wire   [2:0] HwReg_layerScaleFactor_4_fu_994_p7;
wire  signed [2:0] HwReg_layerScaleFactor_4_fu_994_p9;
wire   [0:0] tobool_fu_1021_p0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 grp_VMixHlsDataFlowFunction_fu_676_ap_start_reg = 1'b0;
#0 ap_sync_reg_grp_VMixHlsDataFlowFunction_fu_676_ap_ready = 1'b0;
#0 ap_sync_reg_grp_VMixHlsDataFlowFunction_fu_676_ap_done = 1'b0;
#0 HwReg_layerEnableFlag_5_fu_386 = 1'd0;
#0 HwReg_layerEnableFlag_6_fu_390 = 1'd0;
#0 HwReg_layerEnableFlag_7_fu_394 = 1'd0;
#0 HwReg_layerEnableFlag_8_fu_398 = 1'd0;
#0 HwReg_layerEnableFlag_9_fu_402 = 1'd0;
#0 empty_fu_406 = 16'd0;
#0 empty_93_fu_410 = 16'd0;
#0 empty_94_fu_414 = 16'd0;
#0 empty_95_fu_418 = 16'd0;
#0 empty_96_fu_422 = 16'd0;
#0 empty_97_fu_426 = 16'd0;
#0 empty_98_fu_430 = 16'd0;
#0 empty_99_fu_434 = 16'd0;
#0 empty_100_fu_438 = 8'd0;
#0 empty_101_fu_442 = 16'd0;
#0 empty_102_fu_446 = 16'd0;
#0 empty_103_fu_450 = 8'd0;
#0 empty_104_fu_454 = 16'd0;
#0 empty_105_fu_458 = 16'd0;
#0 empty_106_fu_462 = 8'd0;
#0 empty_107_fu_466 = 16'd0;
#0 empty_108_fu_470 = 16'd0;
#0 empty_109_fu_474 = 8'd0;
#0 empty_110_fu_478 = 16'd0;
#0 empty_111_fu_482 = 16'd0;
#0 i11_fu_486 = 3'd0;
end

bd_quad_vmix_dp_v_mix_0_0_VMixHlsDataFlowFunction grp_VMixHlsDataFlowFunction_fu_676(
    .HwReg_width_val(trunc_ln1812_4_reg_1594),
    .HwReg_height_val(trunc_ln1812_5_reg_1599),
    .HwReg_background_Y_R_val19(trunc_ln1812_3_reg_1589),
    .HwReg_background_U_G_val20(trunc_ln1812_2_reg_1584),
    .HwReg_background_V_B_val21(trunc_ln1812_1_reg_1579),
    .HwReg_layerEnable_val25(trunc_ln1812_reg_1574),
    .HwReg_layerEnableFlag_0_val(HwReg_layerEnableFlag_3_reg_1744),
    .HwReg_layerEnableFlag_1_val(HwReg_layerEnableFlag_2_reg_1749),
    .HwReg_layerEnableFlag_2_val(HwReg_layerEnableFlag_1_reg_1764),
    .HwReg_layerEnableFlag_3_val(HwReg_layerEnableFlag_reg_1779),
    .HwReg_layerEnableFlag_4_val(HwReg_layerEnableFlag_4_reg_1729),
    .HwReg_layerStartX_1_val26(HwReg_layerStartX_2_reg_1819),
    .HwReg_layerStartX_2_val27(HwReg_layerStartX_1_reg_1834),
    .HwReg_layerStartX_3_val28(HwReg_layerStartX_reg_1849),
    .HwReg_layerStartX_4_val29(HwReg_layerStartX_3_reg_1804),
    .HwReg_layerStartY_1_val30(HwReg_layerStartY_2_reg_1814),
    .HwReg_layerStartY_2_val31(HwReg_layerStartY_1_reg_1829),
    .HwReg_layerStartY_3_val32(HwReg_layerStartY_reg_1844),
    .HwReg_layerStartY_4_val33(HwReg_layerStartY_3_reg_1799),
    .HwReg_layerWidth_1_val(HwReg_layerWidth_2_reg_1759),
    .HwReg_layerWidth_2_val(HwReg_layerWidth_1_reg_1774),
    .HwReg_layerWidth_3_val(HwReg_layerWidth_reg_1789),
    .HwReg_layerWidth_4_val(HwReg_layerWidth_3_reg_1739),
    .HwReg_layerHeight_1_val(HwReg_layerHeight_2_reg_1754),
    .HwReg_layerHeight_2_val(HwReg_layerHeight_1_reg_1769),
    .HwReg_layerHeight_3_val(HwReg_layerHeight_reg_1784),
    .HwReg_layerHeight_4_val(HwReg_layerHeight_3_reg_1734),
    .HwReg_layerScaleFactor_1_val42(HwReg_layerScaleFactor_2_reg_1809),
    .HwReg_layerScaleFactor_2_val43(HwReg_layerScaleFactor_1_reg_1824),
    .HwReg_layerScaleFactor_3_val44(HwReg_layerScaleFactor_reg_1839),
    .HwReg_layerScaleFactor_4_val45(HwReg_layerScaleFactor_3_reg_1794),
    .s_axis_video_TDATA(s_axis_video_TDATA_int_regslice),
    .s_axis_video_TKEEP(s_axis_video_TKEEP_int_regslice),
    .s_axis_video_TSTRB(s_axis_video_TSTRB_int_regslice),
    .s_axis_video_TUSER(s_axis_video_TUSER_int_regslice),
    .s_axis_video_TLAST(s_axis_video_TLAST_int_regslice),
    .s_axis_video_TID(s_axis_video_TID_int_regslice),
    .s_axis_video_TDEST(s_axis_video_TDEST_int_regslice),
    .s_axis_video1_TDATA(s_axis_video1_TDATA_int_regslice),
    .s_axis_video1_TKEEP(s_axis_video1_TKEEP_int_regslice),
    .s_axis_video1_TSTRB(s_axis_video1_TSTRB_int_regslice),
    .s_axis_video1_TUSER(s_axis_video1_TUSER_int_regslice),
    .s_axis_video1_TLAST(s_axis_video1_TLAST_int_regslice),
    .s_axis_video1_TID(s_axis_video1_TID_int_regslice),
    .s_axis_video1_TDEST(s_axis_video1_TDEST_int_regslice),
    .s_axis_video2_TDATA(s_axis_video2_TDATA_int_regslice),
    .s_axis_video2_TKEEP(s_axis_video2_TKEEP_int_regslice),
    .s_axis_video2_TSTRB(s_axis_video2_TSTRB_int_regslice),
    .s_axis_video2_TUSER(s_axis_video2_TUSER_int_regslice),
    .s_axis_video2_TLAST(s_axis_video2_TLAST_int_regslice),
    .s_axis_video2_TID(s_axis_video2_TID_int_regslice),
    .s_axis_video2_TDEST(s_axis_video2_TDEST_int_regslice),
    .s_axis_video3_TDATA(s_axis_video3_TDATA_int_regslice),
    .s_axis_video3_TKEEP(s_axis_video3_TKEEP_int_regslice),
    .s_axis_video3_TSTRB(s_axis_video3_TSTRB_int_regslice),
    .s_axis_video3_TUSER(s_axis_video3_TUSER_int_regslice),
    .s_axis_video3_TLAST(s_axis_video3_TLAST_int_regslice),
    .s_axis_video3_TID(s_axis_video3_TID_int_regslice),
    .s_axis_video3_TDEST(s_axis_video3_TDEST_int_regslice),
    .s_axis_video4_TDATA(s_axis_video4_TDATA_int_regslice),
    .s_axis_video4_TKEEP(s_axis_video4_TKEEP_int_regslice),
    .s_axis_video4_TSTRB(s_axis_video4_TSTRB_int_regslice),
    .s_axis_video4_TUSER(s_axis_video4_TUSER_int_regslice),
    .s_axis_video4_TLAST(s_axis_video4_TLAST_int_regslice),
    .s_axis_video4_TID(s_axis_video4_TID_int_regslice),
    .s_axis_video4_TDEST(s_axis_video4_TDEST_int_regslice),
    .m_axis_video_TDATA(grp_VMixHlsDataFlowFunction_fu_676_m_axis_video_TDATA),
    .m_axis_video_TKEEP(grp_VMixHlsDataFlowFunction_fu_676_m_axis_video_TKEEP),
    .m_axis_video_TSTRB(grp_VMixHlsDataFlowFunction_fu_676_m_axis_video_TSTRB),
    .m_axis_video_TUSER(grp_VMixHlsDataFlowFunction_fu_676_m_axis_video_TUSER),
    .m_axis_video_TLAST(grp_VMixHlsDataFlowFunction_fu_676_m_axis_video_TLAST),
    .m_axis_video_TID(grp_VMixHlsDataFlowFunction_fu_676_m_axis_video_TID),
    .m_axis_video_TDEST(grp_VMixHlsDataFlowFunction_fu_676_m_axis_video_TDEST),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .HwReg_layerEnable_val25_ap_vld(1'b1),
    .HwReg_layerStartX_1_val26_ap_vld(1'b1),
    .HwReg_layerStartX_2_val27_ap_vld(1'b1),
    .HwReg_layerStartX_3_val28_ap_vld(1'b1),
    .HwReg_layerStartX_4_val29_ap_vld(1'b1),
    .HwReg_layerStartY_1_val30_ap_vld(1'b1),
    .HwReg_layerStartY_2_val31_ap_vld(1'b1),
    .HwReg_layerStartY_3_val32_ap_vld(1'b1),
    .HwReg_layerStartY_4_val33_ap_vld(1'b1),
    .HwReg_layerScaleFactor_1_val42_ap_vld(1'b1),
    .HwReg_layerScaleFactor_2_val43_ap_vld(1'b1),
    .HwReg_layerScaleFactor_3_val44_ap_vld(1'b1),
    .HwReg_layerScaleFactor_4_val45_ap_vld(1'b1),
    .ap_start(grp_VMixHlsDataFlowFunction_fu_676_ap_start),
    .s_axis_video_TVALID(s_axis_video_TVALID_int_regslice),
    .s_axis_video_TREADY(grp_VMixHlsDataFlowFunction_fu_676_s_axis_video_TREADY),
    .HwReg_height_val_ap_vld(1'b1),
    .HwReg_width_val_ap_vld(1'b1),
    .HwReg_layerEnableFlag_0_val_ap_vld(1'b1),
    .s_axis_video1_TVALID(s_axis_video1_TVALID_int_regslice),
    .s_axis_video1_TREADY(grp_VMixHlsDataFlowFunction_fu_676_s_axis_video1_TREADY),
    .HwReg_layerHeight_1_val_ap_vld(1'b1),
    .HwReg_layerWidth_1_val_ap_vld(1'b1),
    .HwReg_layerEnableFlag_1_val_ap_vld(1'b1),
    .HwReg_background_Y_R_val19_ap_vld(1'b1),
    .HwReg_background_U_G_val20_ap_vld(1'b1),
    .HwReg_background_V_B_val21_ap_vld(1'b1),
    .s_axis_video2_TVALID(s_axis_video2_TVALID_int_regslice),
    .s_axis_video2_TREADY(grp_VMixHlsDataFlowFunction_fu_676_s_axis_video2_TREADY),
    .HwReg_layerHeight_2_val_ap_vld(1'b1),
    .HwReg_layerWidth_2_val_ap_vld(1'b1),
    .HwReg_layerEnableFlag_2_val_ap_vld(1'b1),
    .s_axis_video3_TVALID(s_axis_video3_TVALID_int_regslice),
    .s_axis_video3_TREADY(grp_VMixHlsDataFlowFunction_fu_676_s_axis_video3_TREADY),
    .HwReg_layerHeight_3_val_ap_vld(1'b1),
    .HwReg_layerWidth_3_val_ap_vld(1'b1),
    .HwReg_layerEnableFlag_3_val_ap_vld(1'b1),
    .s_axis_video4_TVALID(s_axis_video4_TVALID_int_regslice),
    .s_axis_video4_TREADY(grp_VMixHlsDataFlowFunction_fu_676_s_axis_video4_TREADY),
    .HwReg_layerHeight_4_val_ap_vld(1'b1),
    .HwReg_layerWidth_4_val_ap_vld(1'b1),
    .HwReg_layerEnableFlag_4_val_ap_vld(1'b1),
    .m_axis_video_TVALID(grp_VMixHlsDataFlowFunction_fu_676_m_axis_video_TVALID),
    .m_axis_video_TREADY(grp_VMixHlsDataFlowFunction_fu_676_m_axis_video_TREADY),
    .ap_done(grp_VMixHlsDataFlowFunction_fu_676_ap_done),
    .ap_ready(grp_VMixHlsDataFlowFunction_fu_676_ap_ready),
    .ap_idle(grp_VMixHlsDataFlowFunction_fu_676_ap_idle),
    .ap_continue(grp_VMixHlsDataFlowFunction_fu_676_ap_continue)
);

bd_quad_vmix_dp_v_mix_0_0_CTRL_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_DATA_WIDTH ))
CTRL_s_axi_U(
    .AWVALID(s_axi_CTRL_AWVALID),
    .AWREADY(s_axi_CTRL_AWREADY),
    .AWADDR(s_axi_CTRL_AWADDR),
    .WVALID(s_axi_CTRL_WVALID),
    .WREADY(s_axi_CTRL_WREADY),
    .WDATA(s_axi_CTRL_WDATA),
    .WSTRB(s_axi_CTRL_WSTRB),
    .ARVALID(s_axi_CTRL_ARVALID),
    .ARREADY(s_axi_CTRL_ARREADY),
    .ARADDR(s_axi_CTRL_ARADDR),
    .RVALID(s_axi_CTRL_RVALID),
    .RREADY(s_axi_CTRL_RREADY),
    .RDATA(s_axi_CTRL_RDATA),
    .RRESP(s_axi_CTRL_RRESP),
    .BVALID(s_axi_CTRL_BVALID),
    .BREADY(s_axi_CTRL_BREADY),
    .BRESP(s_axi_CTRL_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .width(width),
    .height(height),
    .video_format(video_format),
    .background_Y_R(background_Y_R),
    .background_U_G(background_U_G),
    .background_V_B(background_V_B),
    .layerEnable(layerEnable),
    .layerAlpha_1(layerAlpha_1),
    .layerStartX_1(layerStartX_1),
    .layerStartY_1(layerStartY_1),
    .layerWidth_1(layerWidth_1),
    .layerStride_1(layerStride_1),
    .layerHeight_1(layerHeight_1),
    .layerScaleFactor_1(layerScaleFactor_1),
    .layerAlpha_2(layerAlpha_2),
    .layerStartX_2(layerStartX_2),
    .layerStartY_2(layerStartY_2),
    .layerWidth_2(layerWidth_2),
    .layerStride_2(layerStride_2),
    .layerHeight_2(layerHeight_2),
    .layerScaleFactor_2(layerScaleFactor_2),
    .layerAlpha_3(layerAlpha_3),
    .layerStartX_3(layerStartX_3),
    .layerStartY_3(layerStartY_3),
    .layerWidth_3(layerWidth_3),
    .layerStride_3(layerStride_3),
    .layerHeight_3(layerHeight_3),
    .layerScaleFactor_3(layerScaleFactor_3),
    .layerAlpha_4(layerAlpha_4),
    .layerStartX_4(layerStartX_4),
    .layerStartY_4(layerStartY_4),
    .layerWidth_4(layerWidth_4),
    .layerStride_4(layerStride_4),
    .layerHeight_4(layerHeight_4),
    .layerScaleFactor_4(layerScaleFactor_4),
    .reserve(reserve),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

(* dissolve_hierarchy = "yes" *) bd_quad_vmix_dp_v_mix_0_0_sparsemux_11_3_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 16 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 16 ))
sparsemux_11_3_16_1_1_U815(
    .din0(layerStartX_0_read_reg_1604),
    .din1(layerStartX_1_read_reg_1609),
    .din2(layerStartX_2_read_reg_1614),
    .din3(layerStartX_3_read_reg_1619),
    .din4(layerStartX_4_read_reg_1624),
    .def(HwReg_layerStartX_4_fu_902_p11),
    .sel(i11_fu_486),
    .dout(HwReg_layerStartX_4_fu_902_p13)
);

(* dissolve_hierarchy = "yes" *) bd_quad_vmix_dp_v_mix_0_0_sparsemux_11_3_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 16 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 16 ))
sparsemux_11_3_16_1_1_U816(
    .din0(layerStartY_0_read_reg_1629),
    .din1(layerStartY_1_read_reg_1634),
    .din2(layerStartY_2_read_reg_1639),
    .din3(layerStartY_3_read_reg_1644),
    .din4(layerStartY_4_read_reg_1649),
    .def(HwReg_layerStartY_4_fu_925_p11),
    .sel(i11_fu_486),
    .dout(HwReg_layerStartY_4_fu_925_p13)
);

(* dissolve_hierarchy = "yes" *) bd_quad_vmix_dp_v_mix_0_0_sparsemux_11_3_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 16 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 16 ))
sparsemux_11_3_16_1_1_U817(
    .din0(layerWidth_0_read_reg_1654),
    .din1(layerWidth_1_read_reg_1659),
    .din2(layerWidth_2_read_reg_1664),
    .din3(layerWidth_3_read_reg_1669),
    .din4(layerWidth_4_read_reg_1674),
    .def(tmp_s_fu_948_p11),
    .sel(i11_fu_486),
    .dout(tmp_s_fu_948_p13)
);

(* dissolve_hierarchy = "yes" *) bd_quad_vmix_dp_v_mix_0_0_sparsemux_11_3_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 16 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 16 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 16 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 16 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 16 ),
    .def_WIDTH( 16 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 16 ))
sparsemux_11_3_16_1_1_U818(
    .din0(layerHeight_0_read_reg_1679),
    .din1(layerHeight_1_read_reg_1684),
    .din2(layerHeight_2_read_reg_1689),
    .din3(layerHeight_3_read_reg_1694),
    .din4(layerHeight_4_read_reg_1699),
    .def(tmp_4_fu_971_p11),
    .sel(i11_fu_486),
    .dout(tmp_4_fu_971_p13)
);

(* dissolve_hierarchy = "yes" *) bd_quad_vmix_dp_v_mix_0_0_sparsemux_11_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_11_3_8_1_1_U819(
    .din0(layerScaleFactor_0_read_reg_1704),
    .din1(layerScaleFactor_1_read_reg_1709),
    .din2(layerScaleFactor_2_read_reg_1714),
    .din3(layerScaleFactor_3_read_reg_1719),
    .din4(layerScaleFactor_4_read_reg_1724),
    .def(HwReg_layerScaleFactor_4_fu_994_p11),
    .sel(i11_fu_486),
    .dout(HwReg_layerScaleFactor_4_fu_994_p13)
);

bd_quad_vmix_dp_v_mix_0_0_bitselect_1ns_32ns_32ns_1_1_1 #(
    .DATAWIDTH( 32 ),
    .ADDRWIDTH( 32 ))
bitselect_1ns_32ns_32ns_1_1_1_U820(
    .din(layerEnable_read_reg_1569),
    .sel(tobool_fu_1021_p2),
    .dout(tobool_fu_1021_p3)
);

bd_quad_vmix_dp_v_mix_0_0_regslice_both #(
    .DataWidth( 48 ))
regslice_both_s_axis_video_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video_TDATA),
    .vld_in(s_axis_video_TVALID),
    .ack_in(regslice_both_s_axis_video_V_data_V_U_ack_in),
    .data_out(s_axis_video_TDATA_int_regslice),
    .vld_out(s_axis_video_TVALID_int_regslice),
    .ack_out(s_axis_video_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video_V_data_V_U_apdone_blk)
);

bd_quad_vmix_dp_v_mix_0_0_regslice_both #(
    .DataWidth( 6 ))
regslice_both_s_axis_video_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video_TKEEP),
    .vld_in(s_axis_video_TVALID),
    .ack_in(regslice_both_s_axis_video_V_keep_V_U_ack_in),
    .data_out(s_axis_video_TKEEP_int_regslice),
    .vld_out(regslice_both_s_axis_video_V_keep_V_U_vld_out),
    .ack_out(s_axis_video_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video_V_keep_V_U_apdone_blk)
);

bd_quad_vmix_dp_v_mix_0_0_regslice_both #(
    .DataWidth( 6 ))
regslice_both_s_axis_video_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video_TSTRB),
    .vld_in(s_axis_video_TVALID),
    .ack_in(regslice_both_s_axis_video_V_strb_V_U_ack_in),
    .data_out(s_axis_video_TSTRB_int_regslice),
    .vld_out(regslice_both_s_axis_video_V_strb_V_U_vld_out),
    .ack_out(s_axis_video_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video_V_strb_V_U_apdone_blk)
);

bd_quad_vmix_dp_v_mix_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video_TUSER),
    .vld_in(s_axis_video_TVALID),
    .ack_in(regslice_both_s_axis_video_V_user_V_U_ack_in),
    .data_out(s_axis_video_TUSER_int_regslice),
    .vld_out(regslice_both_s_axis_video_V_user_V_U_vld_out),
    .ack_out(s_axis_video_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video_V_user_V_U_apdone_blk)
);

bd_quad_vmix_dp_v_mix_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video_TLAST),
    .vld_in(s_axis_video_TVALID),
    .ack_in(regslice_both_s_axis_video_V_last_V_U_ack_in),
    .data_out(s_axis_video_TLAST_int_regslice),
    .vld_out(regslice_both_s_axis_video_V_last_V_U_vld_out),
    .ack_out(s_axis_video_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video_V_last_V_U_apdone_blk)
);

bd_quad_vmix_dp_v_mix_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video_TID),
    .vld_in(s_axis_video_TVALID),
    .ack_in(regslice_both_s_axis_video_V_id_V_U_ack_in),
    .data_out(s_axis_video_TID_int_regslice),
    .vld_out(regslice_both_s_axis_video_V_id_V_U_vld_out),
    .ack_out(s_axis_video_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video_V_id_V_U_apdone_blk)
);

bd_quad_vmix_dp_v_mix_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video_TDEST),
    .vld_in(s_axis_video_TVALID),
    .ack_in(regslice_both_s_axis_video_V_dest_V_U_ack_in),
    .data_out(s_axis_video_TDEST_int_regslice),
    .vld_out(regslice_both_s_axis_video_V_dest_V_U_vld_out),
    .ack_out(s_axis_video_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video_V_dest_V_U_apdone_blk)
);

bd_quad_vmix_dp_v_mix_0_0_regslice_both #(
    .DataWidth( 48 ))
regslice_both_s_axis_video1_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video1_TDATA),
    .vld_in(s_axis_video1_TVALID),
    .ack_in(regslice_both_s_axis_video1_V_data_V_U_ack_in),
    .data_out(s_axis_video1_TDATA_int_regslice),
    .vld_out(s_axis_video1_TVALID_int_regslice),
    .ack_out(s_axis_video1_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video1_V_data_V_U_apdone_blk)
);

bd_quad_vmix_dp_v_mix_0_0_regslice_both #(
    .DataWidth( 6 ))
regslice_both_s_axis_video1_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video1_TKEEP),
    .vld_in(s_axis_video1_TVALID),
    .ack_in(regslice_both_s_axis_video1_V_keep_V_U_ack_in),
    .data_out(s_axis_video1_TKEEP_int_regslice),
    .vld_out(regslice_both_s_axis_video1_V_keep_V_U_vld_out),
    .ack_out(s_axis_video1_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video1_V_keep_V_U_apdone_blk)
);

bd_quad_vmix_dp_v_mix_0_0_regslice_both #(
    .DataWidth( 6 ))
regslice_both_s_axis_video1_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video1_TSTRB),
    .vld_in(s_axis_video1_TVALID),
    .ack_in(regslice_both_s_axis_video1_V_strb_V_U_ack_in),
    .data_out(s_axis_video1_TSTRB_int_regslice),
    .vld_out(regslice_both_s_axis_video1_V_strb_V_U_vld_out),
    .ack_out(s_axis_video1_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video1_V_strb_V_U_apdone_blk)
);

bd_quad_vmix_dp_v_mix_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video1_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video1_TUSER),
    .vld_in(s_axis_video1_TVALID),
    .ack_in(regslice_both_s_axis_video1_V_user_V_U_ack_in),
    .data_out(s_axis_video1_TUSER_int_regslice),
    .vld_out(regslice_both_s_axis_video1_V_user_V_U_vld_out),
    .ack_out(s_axis_video1_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video1_V_user_V_U_apdone_blk)
);

bd_quad_vmix_dp_v_mix_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video1_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video1_TLAST),
    .vld_in(s_axis_video1_TVALID),
    .ack_in(regslice_both_s_axis_video1_V_last_V_U_ack_in),
    .data_out(s_axis_video1_TLAST_int_regslice),
    .vld_out(regslice_both_s_axis_video1_V_last_V_U_vld_out),
    .ack_out(s_axis_video1_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video1_V_last_V_U_apdone_blk)
);

bd_quad_vmix_dp_v_mix_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video1_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video1_TID),
    .vld_in(s_axis_video1_TVALID),
    .ack_in(regslice_both_s_axis_video1_V_id_V_U_ack_in),
    .data_out(s_axis_video1_TID_int_regslice),
    .vld_out(regslice_both_s_axis_video1_V_id_V_U_vld_out),
    .ack_out(s_axis_video1_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video1_V_id_V_U_apdone_blk)
);

bd_quad_vmix_dp_v_mix_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video1_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video1_TDEST),
    .vld_in(s_axis_video1_TVALID),
    .ack_in(regslice_both_s_axis_video1_V_dest_V_U_ack_in),
    .data_out(s_axis_video1_TDEST_int_regslice),
    .vld_out(regslice_both_s_axis_video1_V_dest_V_U_vld_out),
    .ack_out(s_axis_video1_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video1_V_dest_V_U_apdone_blk)
);

bd_quad_vmix_dp_v_mix_0_0_regslice_both #(
    .DataWidth( 48 ))
regslice_both_s_axis_video2_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video2_TDATA),
    .vld_in(s_axis_video2_TVALID),
    .ack_in(regslice_both_s_axis_video2_V_data_V_U_ack_in),
    .data_out(s_axis_video2_TDATA_int_regslice),
    .vld_out(s_axis_video2_TVALID_int_regslice),
    .ack_out(s_axis_video2_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video2_V_data_V_U_apdone_blk)
);

bd_quad_vmix_dp_v_mix_0_0_regslice_both #(
    .DataWidth( 6 ))
regslice_both_s_axis_video2_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video2_TKEEP),
    .vld_in(s_axis_video2_TVALID),
    .ack_in(regslice_both_s_axis_video2_V_keep_V_U_ack_in),
    .data_out(s_axis_video2_TKEEP_int_regslice),
    .vld_out(regslice_both_s_axis_video2_V_keep_V_U_vld_out),
    .ack_out(s_axis_video2_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video2_V_keep_V_U_apdone_blk)
);

bd_quad_vmix_dp_v_mix_0_0_regslice_both #(
    .DataWidth( 6 ))
regslice_both_s_axis_video2_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video2_TSTRB),
    .vld_in(s_axis_video2_TVALID),
    .ack_in(regslice_both_s_axis_video2_V_strb_V_U_ack_in),
    .data_out(s_axis_video2_TSTRB_int_regslice),
    .vld_out(regslice_both_s_axis_video2_V_strb_V_U_vld_out),
    .ack_out(s_axis_video2_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video2_V_strb_V_U_apdone_blk)
);

bd_quad_vmix_dp_v_mix_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video2_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video2_TUSER),
    .vld_in(s_axis_video2_TVALID),
    .ack_in(regslice_both_s_axis_video2_V_user_V_U_ack_in),
    .data_out(s_axis_video2_TUSER_int_regslice),
    .vld_out(regslice_both_s_axis_video2_V_user_V_U_vld_out),
    .ack_out(s_axis_video2_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video2_V_user_V_U_apdone_blk)
);

bd_quad_vmix_dp_v_mix_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video2_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video2_TLAST),
    .vld_in(s_axis_video2_TVALID),
    .ack_in(regslice_both_s_axis_video2_V_last_V_U_ack_in),
    .data_out(s_axis_video2_TLAST_int_regslice),
    .vld_out(regslice_both_s_axis_video2_V_last_V_U_vld_out),
    .ack_out(s_axis_video2_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video2_V_last_V_U_apdone_blk)
);

bd_quad_vmix_dp_v_mix_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video2_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video2_TID),
    .vld_in(s_axis_video2_TVALID),
    .ack_in(regslice_both_s_axis_video2_V_id_V_U_ack_in),
    .data_out(s_axis_video2_TID_int_regslice),
    .vld_out(regslice_both_s_axis_video2_V_id_V_U_vld_out),
    .ack_out(s_axis_video2_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video2_V_id_V_U_apdone_blk)
);

bd_quad_vmix_dp_v_mix_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video2_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video2_TDEST),
    .vld_in(s_axis_video2_TVALID),
    .ack_in(regslice_both_s_axis_video2_V_dest_V_U_ack_in),
    .data_out(s_axis_video2_TDEST_int_regslice),
    .vld_out(regslice_both_s_axis_video2_V_dest_V_U_vld_out),
    .ack_out(s_axis_video2_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video2_V_dest_V_U_apdone_blk)
);

bd_quad_vmix_dp_v_mix_0_0_regslice_both #(
    .DataWidth( 48 ))
regslice_both_s_axis_video3_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video3_TDATA),
    .vld_in(s_axis_video3_TVALID),
    .ack_in(regslice_both_s_axis_video3_V_data_V_U_ack_in),
    .data_out(s_axis_video3_TDATA_int_regslice),
    .vld_out(s_axis_video3_TVALID_int_regslice),
    .ack_out(s_axis_video3_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video3_V_data_V_U_apdone_blk)
);

bd_quad_vmix_dp_v_mix_0_0_regslice_both #(
    .DataWidth( 6 ))
regslice_both_s_axis_video3_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video3_TKEEP),
    .vld_in(s_axis_video3_TVALID),
    .ack_in(regslice_both_s_axis_video3_V_keep_V_U_ack_in),
    .data_out(s_axis_video3_TKEEP_int_regslice),
    .vld_out(regslice_both_s_axis_video3_V_keep_V_U_vld_out),
    .ack_out(s_axis_video3_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video3_V_keep_V_U_apdone_blk)
);

bd_quad_vmix_dp_v_mix_0_0_regslice_both #(
    .DataWidth( 6 ))
regslice_both_s_axis_video3_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video3_TSTRB),
    .vld_in(s_axis_video3_TVALID),
    .ack_in(regslice_both_s_axis_video3_V_strb_V_U_ack_in),
    .data_out(s_axis_video3_TSTRB_int_regslice),
    .vld_out(regslice_both_s_axis_video3_V_strb_V_U_vld_out),
    .ack_out(s_axis_video3_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video3_V_strb_V_U_apdone_blk)
);

bd_quad_vmix_dp_v_mix_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video3_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video3_TUSER),
    .vld_in(s_axis_video3_TVALID),
    .ack_in(regslice_both_s_axis_video3_V_user_V_U_ack_in),
    .data_out(s_axis_video3_TUSER_int_regslice),
    .vld_out(regslice_both_s_axis_video3_V_user_V_U_vld_out),
    .ack_out(s_axis_video3_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video3_V_user_V_U_apdone_blk)
);

bd_quad_vmix_dp_v_mix_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video3_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video3_TLAST),
    .vld_in(s_axis_video3_TVALID),
    .ack_in(regslice_both_s_axis_video3_V_last_V_U_ack_in),
    .data_out(s_axis_video3_TLAST_int_regslice),
    .vld_out(regslice_both_s_axis_video3_V_last_V_U_vld_out),
    .ack_out(s_axis_video3_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video3_V_last_V_U_apdone_blk)
);

bd_quad_vmix_dp_v_mix_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video3_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video3_TID),
    .vld_in(s_axis_video3_TVALID),
    .ack_in(regslice_both_s_axis_video3_V_id_V_U_ack_in),
    .data_out(s_axis_video3_TID_int_regslice),
    .vld_out(regslice_both_s_axis_video3_V_id_V_U_vld_out),
    .ack_out(s_axis_video3_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video3_V_id_V_U_apdone_blk)
);

bd_quad_vmix_dp_v_mix_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video3_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video3_TDEST),
    .vld_in(s_axis_video3_TVALID),
    .ack_in(regslice_both_s_axis_video3_V_dest_V_U_ack_in),
    .data_out(s_axis_video3_TDEST_int_regslice),
    .vld_out(regslice_both_s_axis_video3_V_dest_V_U_vld_out),
    .ack_out(s_axis_video3_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video3_V_dest_V_U_apdone_blk)
);

bd_quad_vmix_dp_v_mix_0_0_regslice_both #(
    .DataWidth( 48 ))
regslice_both_s_axis_video4_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video4_TDATA),
    .vld_in(s_axis_video4_TVALID),
    .ack_in(regslice_both_s_axis_video4_V_data_V_U_ack_in),
    .data_out(s_axis_video4_TDATA_int_regslice),
    .vld_out(s_axis_video4_TVALID_int_regslice),
    .ack_out(s_axis_video4_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video4_V_data_V_U_apdone_blk)
);

bd_quad_vmix_dp_v_mix_0_0_regslice_both #(
    .DataWidth( 6 ))
regslice_both_s_axis_video4_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video4_TKEEP),
    .vld_in(s_axis_video4_TVALID),
    .ack_in(regslice_both_s_axis_video4_V_keep_V_U_ack_in),
    .data_out(s_axis_video4_TKEEP_int_regslice),
    .vld_out(regslice_both_s_axis_video4_V_keep_V_U_vld_out),
    .ack_out(s_axis_video4_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video4_V_keep_V_U_apdone_blk)
);

bd_quad_vmix_dp_v_mix_0_0_regslice_both #(
    .DataWidth( 6 ))
regslice_both_s_axis_video4_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video4_TSTRB),
    .vld_in(s_axis_video4_TVALID),
    .ack_in(regslice_both_s_axis_video4_V_strb_V_U_ack_in),
    .data_out(s_axis_video4_TSTRB_int_regslice),
    .vld_out(regslice_both_s_axis_video4_V_strb_V_U_vld_out),
    .ack_out(s_axis_video4_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video4_V_strb_V_U_apdone_blk)
);

bd_quad_vmix_dp_v_mix_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video4_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video4_TUSER),
    .vld_in(s_axis_video4_TVALID),
    .ack_in(regslice_both_s_axis_video4_V_user_V_U_ack_in),
    .data_out(s_axis_video4_TUSER_int_regslice),
    .vld_out(regslice_both_s_axis_video4_V_user_V_U_vld_out),
    .ack_out(s_axis_video4_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video4_V_user_V_U_apdone_blk)
);

bd_quad_vmix_dp_v_mix_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video4_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video4_TLAST),
    .vld_in(s_axis_video4_TVALID),
    .ack_in(regslice_both_s_axis_video4_V_last_V_U_ack_in),
    .data_out(s_axis_video4_TLAST_int_regslice),
    .vld_out(regslice_both_s_axis_video4_V_last_V_U_vld_out),
    .ack_out(s_axis_video4_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video4_V_last_V_U_apdone_blk)
);

bd_quad_vmix_dp_v_mix_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video4_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video4_TID),
    .vld_in(s_axis_video4_TVALID),
    .ack_in(regslice_both_s_axis_video4_V_id_V_U_ack_in),
    .data_out(s_axis_video4_TID_int_regslice),
    .vld_out(regslice_both_s_axis_video4_V_id_V_U_vld_out),
    .ack_out(s_axis_video4_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video4_V_id_V_U_apdone_blk)
);

bd_quad_vmix_dp_v_mix_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_axis_video4_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_axis_video4_TDEST),
    .vld_in(s_axis_video4_TVALID),
    .ack_in(regslice_both_s_axis_video4_V_dest_V_U_ack_in),
    .data_out(s_axis_video4_TDEST_int_regslice),
    .vld_out(regslice_both_s_axis_video4_V_dest_V_U_vld_out),
    .ack_out(s_axis_video4_TREADY_int_regslice),
    .apdone_blk(regslice_both_s_axis_video4_V_dest_V_U_apdone_blk)
);

bd_quad_vmix_dp_v_mix_0_0_regslice_both #(
    .DataWidth( 48 ))
regslice_both_m_axis_video_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(m_axis_video_TDATA_int_regslice),
    .vld_in(grp_VMixHlsDataFlowFunction_fu_676_m_axis_video_TVALID),
    .ack_in(m_axis_video_TREADY_int_regslice),
    .data_out(m_axis_video_TDATA),
    .vld_out(regslice_both_m_axis_video_V_data_V_U_vld_out),
    .ack_out(m_axis_video_TREADY),
    .apdone_blk(regslice_both_m_axis_video_V_data_V_U_apdone_blk)
);

bd_quad_vmix_dp_v_mix_0_0_regslice_both #(
    .DataWidth( 6 ))
regslice_both_m_axis_video_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(m_axis_video_TKEEP_int_regslice),
    .vld_in(grp_VMixHlsDataFlowFunction_fu_676_m_axis_video_TVALID),
    .ack_in(regslice_both_m_axis_video_V_keep_V_U_ack_in_dummy),
    .data_out(m_axis_video_TKEEP),
    .vld_out(regslice_both_m_axis_video_V_keep_V_U_vld_out),
    .ack_out(m_axis_video_TREADY),
    .apdone_blk(regslice_both_m_axis_video_V_keep_V_U_apdone_blk)
);

bd_quad_vmix_dp_v_mix_0_0_regslice_both #(
    .DataWidth( 6 ))
regslice_both_m_axis_video_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(m_axis_video_TSTRB_int_regslice),
    .vld_in(grp_VMixHlsDataFlowFunction_fu_676_m_axis_video_TVALID),
    .ack_in(regslice_both_m_axis_video_V_strb_V_U_ack_in_dummy),
    .data_out(m_axis_video_TSTRB),
    .vld_out(regslice_both_m_axis_video_V_strb_V_U_vld_out),
    .ack_out(m_axis_video_TREADY),
    .apdone_blk(regslice_both_m_axis_video_V_strb_V_U_apdone_blk)
);

bd_quad_vmix_dp_v_mix_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_m_axis_video_V_user_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(m_axis_video_TUSER_int_regslice),
    .vld_in(grp_VMixHlsDataFlowFunction_fu_676_m_axis_video_TVALID),
    .ack_in(regslice_both_m_axis_video_V_user_V_U_ack_in_dummy),
    .data_out(m_axis_video_TUSER),
    .vld_out(regslice_both_m_axis_video_V_user_V_U_vld_out),
    .ack_out(m_axis_video_TREADY),
    .apdone_blk(regslice_both_m_axis_video_V_user_V_U_apdone_blk)
);

bd_quad_vmix_dp_v_mix_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_m_axis_video_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(m_axis_video_TLAST_int_regslice),
    .vld_in(grp_VMixHlsDataFlowFunction_fu_676_m_axis_video_TVALID),
    .ack_in(regslice_both_m_axis_video_V_last_V_U_ack_in_dummy),
    .data_out(m_axis_video_TLAST),
    .vld_out(regslice_both_m_axis_video_V_last_V_U_vld_out),
    .ack_out(m_axis_video_TREADY),
    .apdone_blk(regslice_both_m_axis_video_V_last_V_U_apdone_blk)
);

bd_quad_vmix_dp_v_mix_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_m_axis_video_V_id_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(m_axis_video_TID_int_regslice),
    .vld_in(grp_VMixHlsDataFlowFunction_fu_676_m_axis_video_TVALID),
    .ack_in(regslice_both_m_axis_video_V_id_V_U_ack_in_dummy),
    .data_out(m_axis_video_TID),
    .vld_out(regslice_both_m_axis_video_V_id_V_U_vld_out),
    .ack_out(m_axis_video_TREADY),
    .apdone_blk(regslice_both_m_axis_video_V_id_V_U_apdone_blk)
);

bd_quad_vmix_dp_v_mix_0_0_regslice_both #(
    .DataWidth( 1 ))
regslice_both_m_axis_video_V_dest_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(m_axis_video_TDEST_int_regslice),
    .vld_in(grp_VMixHlsDataFlowFunction_fu_676_m_axis_video_TVALID),
    .ack_in(regslice_both_m_axis_video_V_dest_V_U_ack_in_dummy),
    .data_out(m_axis_video_TDEST),
    .vld_out(regslice_both_m_axis_video_V_dest_V_U_vld_out),
    .ack_out(m_axis_video_TREADY),
    .apdone_blk(regslice_both_m_axis_video_V_dest_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_grp_VMixHlsDataFlowFunction_fu_676_ap_done <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
            ap_sync_reg_grp_VMixHlsDataFlowFunction_fu_676_ap_done <= 1'b0;
        end else if ((grp_VMixHlsDataFlowFunction_fu_676_ap_done == 1'b1)) begin
            ap_sync_reg_grp_VMixHlsDataFlowFunction_fu_676_ap_done <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_grp_VMixHlsDataFlowFunction_fu_676_ap_ready <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
            ap_sync_reg_grp_VMixHlsDataFlowFunction_fu_676_ap_ready <= 1'b0;
        end else if ((grp_VMixHlsDataFlowFunction_fu_676_ap_ready == 1'b1)) begin
            ap_sync_reg_grp_VMixHlsDataFlowFunction_fu_676_ap_ready <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_VMixHlsDataFlowFunction_fu_676_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state3) | ((ap_sync_grp_VMixHlsDataFlowFunction_fu_676_ap_ready == 1'b0) & (1'b1 == ap_CS_fsm_state4)))) begin
            grp_VMixHlsDataFlowFunction_fu_676_ap_start_reg <= 1'b1;
        end else if ((grp_VMixHlsDataFlowFunction_fu_676_ap_ready == 1'b1)) begin
            grp_VMixHlsDataFlowFunction_fu_676_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i11_fu_486 <= 3'd0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        i11_fu_486 <= i_fu_1270_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        HwReg_layerEnableFlag_1_reg_1764 <= HwReg_layerEnableFlag_1_fu_1126_p3;
        HwReg_layerEnableFlag_2_reg_1749 <= HwReg_layerEnableFlag_2_fu_1102_p3;
        HwReg_layerEnableFlag_3_reg_1744 <= HwReg_layerEnableFlag_3_fu_1094_p3;
        HwReg_layerEnableFlag_4_reg_1729 <= HwReg_layerEnableFlag_4_fu_1070_p3;
        HwReg_layerEnableFlag_5_fu_386 <= HwReg_layerEnableFlag_4_fu_1070_p3;
        HwReg_layerEnableFlag_6_fu_390 <= HwReg_layerEnableFlag_3_fu_1094_p3;
        HwReg_layerEnableFlag_7_fu_394 <= HwReg_layerEnableFlag_2_fu_1102_p3;
        HwReg_layerEnableFlag_8_fu_398 <= HwReg_layerEnableFlag_1_fu_1126_p3;
        HwReg_layerEnableFlag_9_fu_402 <= HwReg_layerEnableFlag_fu_1150_p3;
        HwReg_layerEnableFlag_reg_1779 <= HwReg_layerEnableFlag_fu_1150_p3;
        HwReg_layerHeight_1_reg_1769 <= HwReg_layerHeight_1_fu_1134_p3;
        HwReg_layerHeight_2_reg_1754 <= HwReg_layerHeight_2_fu_1110_p3;
        HwReg_layerHeight_3_reg_1734 <= HwReg_layerHeight_3_fu_1078_p3;
        HwReg_layerHeight_reg_1784 <= HwReg_layerHeight_fu_1158_p3;
        HwReg_layerScaleFactor_1_reg_1824 <= HwReg_layerScaleFactor_1_fu_1222_p3;
        HwReg_layerScaleFactor_2_reg_1809 <= HwReg_layerScaleFactor_2_fu_1198_p3;
        HwReg_layerScaleFactor_3_reg_1794 <= HwReg_layerScaleFactor_3_fu_1174_p3;
        HwReg_layerScaleFactor_reg_1839 <= HwReg_layerScaleFactor_fu_1246_p3;
        HwReg_layerStartX_1_reg_1834 <= HwReg_layerStartX_1_fu_1238_p3;
        HwReg_layerStartX_2_reg_1819 <= HwReg_layerStartX_2_fu_1214_p3;
        HwReg_layerStartX_3_reg_1804 <= HwReg_layerStartX_3_fu_1190_p3;
        HwReg_layerStartX_reg_1849 <= HwReg_layerStartX_fu_1262_p3;
        HwReg_layerStartY_1_reg_1829 <= HwReg_layerStartY_1_fu_1230_p3;
        HwReg_layerStartY_2_reg_1814 <= HwReg_layerStartY_2_fu_1206_p3;
        HwReg_layerStartY_3_reg_1799 <= HwReg_layerStartY_3_fu_1182_p3;
        HwReg_layerStartY_reg_1844 <= HwReg_layerStartY_fu_1254_p3;
        HwReg_layerWidth_1_reg_1774 <= HwReg_layerWidth_1_fu_1142_p3;
        HwReg_layerWidth_2_reg_1759 <= HwReg_layerWidth_2_fu_1118_p3;
        HwReg_layerWidth_3_reg_1739 <= HwReg_layerWidth_3_fu_1086_p3;
        HwReg_layerWidth_reg_1789 <= HwReg_layerWidth_fu_1166_p3;
        empty_100_fu_438 <= HwReg_layerScaleFactor_3_fu_1174_p3;
        empty_101_fu_442 <= HwReg_layerStartY_3_fu_1182_p3;
        empty_102_fu_446 <= HwReg_layerStartX_3_fu_1190_p3;
        empty_103_fu_450 <= HwReg_layerScaleFactor_2_fu_1198_p3;
        empty_104_fu_454 <= HwReg_layerStartY_2_fu_1206_p3;
        empty_105_fu_458 <= HwReg_layerStartX_2_fu_1214_p3;
        empty_106_fu_462 <= HwReg_layerScaleFactor_1_fu_1222_p3;
        empty_107_fu_466 <= HwReg_layerStartY_1_fu_1230_p3;
        empty_108_fu_470 <= HwReg_layerStartX_1_fu_1238_p3;
        empty_109_fu_474 <= HwReg_layerScaleFactor_fu_1246_p3;
        empty_110_fu_478 <= HwReg_layerStartY_fu_1254_p3;
        empty_111_fu_482 <= HwReg_layerStartX_fu_1262_p3;
        empty_93_fu_410 <= HwReg_layerWidth_3_fu_1086_p3;
        empty_94_fu_414 <= HwReg_layerHeight_2_fu_1110_p3;
        empty_95_fu_418 <= HwReg_layerWidth_2_fu_1118_p3;
        empty_96_fu_422 <= HwReg_layerHeight_1_fu_1134_p3;
        empty_97_fu_426 <= HwReg_layerWidth_1_fu_1142_p3;
        empty_98_fu_430 <= HwReg_layerHeight_fu_1158_p3;
        empty_99_fu_434 <= HwReg_layerWidth_fu_1166_p3;
        empty_fu_406 <= HwReg_layerHeight_3_fu_1078_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        layerEnable_read_reg_1569 <= layerEnable;
        layerHeight_0_read_reg_1679 <= layerHeight_0;
        layerHeight_1_read_reg_1684 <= layerHeight_1;
        layerHeight_2_read_reg_1689 <= layerHeight_2;
        layerHeight_3_read_reg_1694 <= layerHeight_3;
        layerHeight_4_read_reg_1699 <= layerHeight_4;
        layerScaleFactor_0_read_reg_1704 <= layerScaleFactor_0;
        layerScaleFactor_1_read_reg_1709 <= layerScaleFactor_1;
        layerScaleFactor_2_read_reg_1714 <= layerScaleFactor_2;
        layerScaleFactor_3_read_reg_1719 <= layerScaleFactor_3;
        layerScaleFactor_4_read_reg_1724 <= layerScaleFactor_4;
        layerStartX_0_read_reg_1604 <= layerStartX_0;
        layerStartX_1_read_reg_1609 <= layerStartX_1;
        layerStartX_2_read_reg_1614 <= layerStartX_2;
        layerStartX_3_read_reg_1619 <= layerStartX_3;
        layerStartX_4_read_reg_1624 <= layerStartX_4;
        layerStartY_0_read_reg_1629 <= layerStartY_0;
        layerStartY_1_read_reg_1634 <= layerStartY_1;
        layerStartY_2_read_reg_1639 <= layerStartY_2;
        layerStartY_3_read_reg_1644 <= layerStartY_3;
        layerStartY_4_read_reg_1649 <= layerStartY_4;
        layerWidth_0_read_reg_1654 <= layerWidth_0;
        layerWidth_1_read_reg_1659 <= layerWidth_1;
        layerWidth_2_read_reg_1664 <= layerWidth_2;
        layerWidth_3_read_reg_1669 <= layerWidth_3;
        layerWidth_4_read_reg_1674 <= layerWidth_4;
        trunc_ln1812_1_reg_1579 <= trunc_ln1812_1_fu_799_p1;
        trunc_ln1812_2_reg_1584 <= trunc_ln1812_2_fu_803_p1;
        trunc_ln1812_3_reg_1589 <= trunc_ln1812_3_fu_807_p1;
        trunc_ln1812_4_reg_1594 <= trunc_ln1812_4_fu_811_p1;
        trunc_ln1812_5_reg_1599 <= trunc_ln1812_5_fu_815_p1;
        trunc_ln1812_reg_1574 <= trunc_ln1812_fu_795_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_VMixHlsDataFlowFunction_fu_676_m_axis_video_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        m_axis_video_TDATA_reg <= grp_VMixHlsDataFlowFunction_fu_676_m_axis_video_TDATA;
        m_axis_video_TDEST_reg <= grp_VMixHlsDataFlowFunction_fu_676_m_axis_video_TDEST;
        m_axis_video_TID_reg <= grp_VMixHlsDataFlowFunction_fu_676_m_axis_video_TID;
        m_axis_video_TKEEP_reg <= grp_VMixHlsDataFlowFunction_fu_676_m_axis_video_TKEEP;
        m_axis_video_TLAST_reg <= grp_VMixHlsDataFlowFunction_fu_676_m_axis_video_TLAST;
        m_axis_video_TSTRB_reg <= grp_VMixHlsDataFlowFunction_fu_676_m_axis_video_TSTRB;
        m_axis_video_TUSER_reg <= grp_VMixHlsDataFlowFunction_fu_676_m_axis_video_TUSER;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state4_on_subcall_done)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((regslice_both_m_axis_video_V_data_V_U_apdone_blk == 1'b1)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_m_axis_video_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_m_axis_video_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
        grp_VMixHlsDataFlowFunction_fu_676_ap_continue = 1'b1;
    end else begin
        grp_VMixHlsDataFlowFunction_fu_676_ap_continue = 1'b0;
    end
end

always @ (*) begin
    if (((grp_VMixHlsDataFlowFunction_fu_676_m_axis_video_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        m_axis_video_TDATA_int_regslice = grp_VMixHlsDataFlowFunction_fu_676_m_axis_video_TDATA;
    end else begin
        m_axis_video_TDATA_int_regslice = m_axis_video_TDATA_reg;
    end
end

always @ (*) begin
    if (((grp_VMixHlsDataFlowFunction_fu_676_m_axis_video_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        m_axis_video_TDEST_int_regslice = grp_VMixHlsDataFlowFunction_fu_676_m_axis_video_TDEST;
    end else begin
        m_axis_video_TDEST_int_regslice = m_axis_video_TDEST_reg;
    end
end

always @ (*) begin
    if (((grp_VMixHlsDataFlowFunction_fu_676_m_axis_video_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        m_axis_video_TID_int_regslice = grp_VMixHlsDataFlowFunction_fu_676_m_axis_video_TID;
    end else begin
        m_axis_video_TID_int_regslice = m_axis_video_TID_reg;
    end
end

always @ (*) begin
    if (((grp_VMixHlsDataFlowFunction_fu_676_m_axis_video_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        m_axis_video_TKEEP_int_regslice = grp_VMixHlsDataFlowFunction_fu_676_m_axis_video_TKEEP;
    end else begin
        m_axis_video_TKEEP_int_regslice = m_axis_video_TKEEP_reg;
    end
end

always @ (*) begin
    if (((grp_VMixHlsDataFlowFunction_fu_676_m_axis_video_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        m_axis_video_TLAST_int_regslice = grp_VMixHlsDataFlowFunction_fu_676_m_axis_video_TLAST;
    end else begin
        m_axis_video_TLAST_int_regslice = m_axis_video_TLAST_reg;
    end
end

always @ (*) begin
    if (((grp_VMixHlsDataFlowFunction_fu_676_m_axis_video_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        m_axis_video_TSTRB_int_regslice = grp_VMixHlsDataFlowFunction_fu_676_m_axis_video_TSTRB;
    end else begin
        m_axis_video_TSTRB_int_regslice = m_axis_video_TSTRB_reg;
    end
end

always @ (*) begin
    if (((grp_VMixHlsDataFlowFunction_fu_676_m_axis_video_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        m_axis_video_TUSER_int_regslice = grp_VMixHlsDataFlowFunction_fu_676_m_axis_video_TUSER;
    end else begin
        m_axis_video_TUSER_int_regslice = m_axis_video_TUSER_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        s_axis_video1_TREADY_int_regslice = grp_VMixHlsDataFlowFunction_fu_676_s_axis_video1_TREADY;
    end else begin
        s_axis_video1_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        s_axis_video2_TREADY_int_regslice = grp_VMixHlsDataFlowFunction_fu_676_s_axis_video2_TREADY;
    end else begin
        s_axis_video2_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        s_axis_video3_TREADY_int_regslice = grp_VMixHlsDataFlowFunction_fu_676_s_axis_video3_TREADY;
    end else begin
        s_axis_video3_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        s_axis_video4_TREADY_int_regslice = grp_VMixHlsDataFlowFunction_fu_676_s_axis_video4_TREADY;
    end else begin
        s_axis_video4_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        s_axis_video_TREADY_int_regslice = grp_VMixHlsDataFlowFunction_fu_676_s_axis_video_TREADY;
    end else begin
        s_axis_video_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln2626_fu_1276_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((regslice_both_m_axis_video_V_data_V_U_apdone_blk == 1'b0) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign HwReg_layerEnableFlag_1_fu_1126_p3 = ((icmp_ln2629_2_fu_1040_p2[0:0] == 1'b1) ? tobool_fu_1021_p3 : HwReg_layerEnableFlag_8_fu_398);

assign HwReg_layerEnableFlag_2_fu_1102_p3 = ((icmp_ln2629_1_fu_1034_p2[0:0] == 1'b1) ? tobool_fu_1021_p3 : HwReg_layerEnableFlag_7_fu_394);

assign HwReg_layerEnableFlag_3_fu_1094_p3 = ((icmp_ln2629_fu_1028_p2[0:0] == 1'b1) ? tobool_fu_1021_p3 : HwReg_layerEnableFlag_6_fu_390);

assign HwReg_layerEnableFlag_4_fu_1070_p3 = ((or_ln2629_2_fu_1064_p2[0:0] == 1'b1) ? HwReg_layerEnableFlag_5_fu_386 : tobool_fu_1021_p3);

assign HwReg_layerEnableFlag_fu_1150_p3 = ((icmp_ln2629_3_fu_1046_p2[0:0] == 1'b1) ? tobool_fu_1021_p3 : HwReg_layerEnableFlag_9_fu_402);

assign HwReg_layerHeight_1_fu_1134_p3 = ((icmp_ln2629_2_fu_1040_p2[0:0] == 1'b1) ? tmp_4_fu_971_p13 : empty_96_fu_422);

assign HwReg_layerHeight_2_fu_1110_p3 = ((icmp_ln2629_1_fu_1034_p2[0:0] == 1'b1) ? tmp_4_fu_971_p13 : empty_94_fu_414);

assign HwReg_layerHeight_3_fu_1078_p3 = ((or_ln2629_2_fu_1064_p2[0:0] == 1'b1) ? empty_fu_406 : tmp_4_fu_971_p13);

assign HwReg_layerHeight_fu_1158_p3 = ((icmp_ln2629_3_fu_1046_p2[0:0] == 1'b1) ? tmp_4_fu_971_p13 : empty_98_fu_430);

assign HwReg_layerScaleFactor_1_fu_1222_p3 = ((icmp_ln2629_2_fu_1040_p2[0:0] == 1'b1) ? HwReg_layerScaleFactor_4_fu_994_p13 : empty_106_fu_462);

assign HwReg_layerScaleFactor_2_fu_1198_p3 = ((icmp_ln2629_1_fu_1034_p2[0:0] == 1'b1) ? HwReg_layerScaleFactor_4_fu_994_p13 : empty_103_fu_450);

assign HwReg_layerScaleFactor_3_fu_1174_p3 = ((or_ln2629_2_fu_1064_p2[0:0] == 1'b1) ? empty_100_fu_438 : HwReg_layerScaleFactor_4_fu_994_p13);

assign HwReg_layerScaleFactor_4_fu_994_p11 = 'bx;

assign HwReg_layerScaleFactor_fu_1246_p3 = ((icmp_ln2629_3_fu_1046_p2[0:0] == 1'b1) ? HwReg_layerScaleFactor_4_fu_994_p13 : empty_109_fu_474);

assign HwReg_layerStartX_1_fu_1238_p3 = ((icmp_ln2629_2_fu_1040_p2[0:0] == 1'b1) ? HwReg_layerStartX_4_fu_902_p13 : empty_108_fu_470);

assign HwReg_layerStartX_2_fu_1214_p3 = ((icmp_ln2629_1_fu_1034_p2[0:0] == 1'b1) ? HwReg_layerStartX_4_fu_902_p13 : empty_105_fu_458);

assign HwReg_layerStartX_3_fu_1190_p3 = ((or_ln2629_2_fu_1064_p2[0:0] == 1'b1) ? empty_102_fu_446 : HwReg_layerStartX_4_fu_902_p13);

assign HwReg_layerStartX_4_fu_902_p11 = 'bx;

assign HwReg_layerStartX_fu_1262_p3 = ((icmp_ln2629_3_fu_1046_p2[0:0] == 1'b1) ? HwReg_layerStartX_4_fu_902_p13 : empty_111_fu_482);

assign HwReg_layerStartY_1_fu_1230_p3 = ((icmp_ln2629_2_fu_1040_p2[0:0] == 1'b1) ? HwReg_layerStartY_4_fu_925_p13 : empty_107_fu_466);

assign HwReg_layerStartY_2_fu_1206_p3 = ((icmp_ln2629_1_fu_1034_p2[0:0] == 1'b1) ? HwReg_layerStartY_4_fu_925_p13 : empty_104_fu_454);

assign HwReg_layerStartY_3_fu_1182_p3 = ((or_ln2629_2_fu_1064_p2[0:0] == 1'b1) ? empty_101_fu_442 : HwReg_layerStartY_4_fu_925_p13);

assign HwReg_layerStartY_4_fu_925_p11 = 'bx;

assign HwReg_layerStartY_fu_1254_p3 = ((icmp_ln2629_3_fu_1046_p2[0:0] == 1'b1) ? HwReg_layerStartY_4_fu_925_p13 : empty_110_fu_478);

assign HwReg_layerWidth_1_fu_1142_p3 = ((icmp_ln2629_2_fu_1040_p2[0:0] == 1'b1) ? tmp_s_fu_948_p13 : empty_97_fu_426);

assign HwReg_layerWidth_2_fu_1118_p3 = ((icmp_ln2629_1_fu_1034_p2[0:0] == 1'b1) ? tmp_s_fu_948_p13 : empty_95_fu_418);

assign HwReg_layerWidth_3_fu_1086_p3 = ((or_ln2629_2_fu_1064_p2[0:0] == 1'b1) ? empty_93_fu_410 : tmp_s_fu_948_p13);

assign HwReg_layerWidth_fu_1166_p3 = ((icmp_ln2629_3_fu_1046_p2[0:0] == 1'b1) ? tmp_s_fu_948_p13 : empty_99_fu_434);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_state4_on_subcall_done = ((ap_sync_reg_grp_VMixHlsDataFlowFunction_fu_676_ap_ready & ap_sync_reg_grp_VMixHlsDataFlowFunction_fu_676_ap_done) == 1'b0);
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_grp_VMixHlsDataFlowFunction_fu_676_ap_ready = (grp_VMixHlsDataFlowFunction_fu_676_ap_ready | ap_sync_reg_grp_VMixHlsDataFlowFunction_fu_676_ap_ready);

assign grp_VMixHlsDataFlowFunction_fu_676_ap_start = grp_VMixHlsDataFlowFunction_fu_676_ap_start_reg;

assign grp_VMixHlsDataFlowFunction_fu_676_m_axis_video_TREADY = (m_axis_video_TREADY_int_regslice & ap_CS_fsm_state4);

assign i_fu_1270_p2 = (i11_fu_486 + 3'd1);

assign icmp_ln2626_fu_1276_p2 = ((i11_fu_486 == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln2629_1_fu_1034_p2 = ((i11_fu_486 == 3'd1) ? 1'b1 : 1'b0);

assign icmp_ln2629_2_fu_1040_p2 = ((i11_fu_486 == 3'd2) ? 1'b1 : 1'b0);

assign icmp_ln2629_3_fu_1046_p2 = ((i11_fu_486 == 3'd3) ? 1'b1 : 1'b0);

assign icmp_ln2629_fu_1028_p2 = ((i11_fu_486 == 3'd0) ? 1'b1 : 1'b0);

assign layerVideoFormat_address0 = 3'd0;

assign layerVideoFormat_address1 = 3'd0;

assign layerVideoFormat_ce0 = 1'b0;

assign layerVideoFormat_ce1 = 1'b0;

assign layerVideoFormat_d0 = 8'd0;

assign layerVideoFormat_d1 = 8'd0;

assign layerVideoFormat_we0 = 1'b0;

assign layerVideoFormat_we1 = 1'b0;

assign m_axis_video_TVALID = regslice_both_m_axis_video_V_data_V_U_vld_out;

assign m_axis_video_TVALID_int_regslice = grp_VMixHlsDataFlowFunction_fu_676_m_axis_video_TVALID;

assign or_ln2629_1_fu_1058_p2 = (icmp_ln2629_fu_1028_p2 | icmp_ln2629_3_fu_1046_p2);

assign or_ln2629_2_fu_1064_p2 = (or_ln2629_fu_1052_p2 | or_ln2629_1_fu_1058_p2);

assign or_ln2629_fu_1052_p2 = (icmp_ln2629_2_fu_1040_p2 | icmp_ln2629_1_fu_1034_p2);

assign s_axis_video1_TREADY = regslice_both_s_axis_video1_V_data_V_U_ack_in;

assign s_axis_video2_TREADY = regslice_both_s_axis_video2_V_data_V_U_ack_in;

assign s_axis_video3_TREADY = regslice_both_s_axis_video3_V_data_V_U_ack_in;

assign s_axis_video4_TREADY = regslice_both_s_axis_video4_V_data_V_U_ack_in;

assign s_axis_video_TREADY = regslice_both_s_axis_video_V_data_V_U_ack_in;

assign tmp_4_fu_971_p11 = 'bx;

assign tmp_s_fu_948_p11 = 'bx;

assign tobool_fu_1021_p2 = i11_fu_486;

assign trunc_ln1812_1_fu_799_p1 = background_V_B[7:0];

assign trunc_ln1812_2_fu_803_p1 = background_U_G[7:0];

assign trunc_ln1812_3_fu_807_p1 = background_Y_R[7:0];

assign trunc_ln1812_4_fu_811_p1 = width[11:0];

assign trunc_ln1812_5_fu_815_p1 = height[11:0];

assign trunc_ln1812_fu_795_p1 = layerEnable[4:0];


reg find_df_deadlock = 0;
// synthesis translate_off
`include "bd_quad_vmix_dp_v_mix_0_0_hls_deadlock_detector.vh"
// synthesis translate_on

reg find_kernel_block = 0;
// synthesis translate_off
`include "bd_quad_vmix_dp_v_mix_0_0_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //bd_quad_vmix_dp_v_mix_0_0_v_mix

